---
title: "Simulation"
output: html_document
---


# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
library(ggh4x)
library(grid)
library(extraDistr)
library(brms)
library(posterior)
library(foreach)
library(doParallel)
library(stringr)
```


## Functions
```{r, }
#------------------------------------------------------------------------------
# CALCULATE PERCENTILE
calculate_percentile = function(true, predicted, S){
  percentiles = matrix(nrow = nrow(true), ncol = S)
  for(s in 1:S){
    for(i in 1:nrow(true)){
      percentiles[i,s] = mean(predicted[,s,i] < true[i,s])
    }
  }
  return(percentiles)
}


#------------------------------------------------------------------------------
# USE SOFTMAX TO OBTAIN CHOICE PROBABILITIES - USED IN SIMULATIONS
softmax = function(values){
  return(exp(values) / sum(exp(values)))
}


#------------------------------------------------------------------------------
# SIMULATION FUNCTION
simulate_RL = function(learning_rate = .5, n_trials = 100,
                       Sr_probs = c(.3, .7), label = "") {

  data = data.frame()
  A = learning_rate
  utility = rep(0,2)
    
  for(t in 1:n_trials){
    prob = softmax(c(utility[1], utility[2]))
    
    choice = sample(c(1,2), 1, prob = prob)
    
    outcome = rbinom(1, 1, Sr_probs[choice])
    
    data = data.frame(sim = label,
                      A = A,
                      trial = t,
                      prob_1 = prob[1],
                      prob_2 = prob[2],
                      utility_1 = utility[1],
                      utility_2 = utility[2],
                      outcome = outcome,
                      choice = choice) %>% 
      bind_rows(data)
    
    utility[choice] = utility[choice] + A * (outcome - utility[choice])
  }
  data %>%
    return()
}


#------------------------------------------------------------------------------
# GRABBING POSTERIOR FUNCTION
par_from_draws <- function(fit, par) {
  rvars_pars <- as_draws_rvars(
    fit$draws(
      c(par)
    )
  )
  return(lapply(rvars_pars, draws_of))
}
```


# -------------------------------------------
# Simulation
## Setup
```{r}
# -----------------------------------------------------------------------------------
# SPECIFY CONDITIONS FOR SIMULATION
n_iter      = 1000
n_warmup    = 500
n_chains    = 4
N           = 50
S           = 3
# clusters    = makeCluster(1)
clusters    = makeCluster(4)
sim_numbers = 1:100
conditions  = list.files(here("1_HLCM", "Data", "1_Simulations"))

for(f in conditions){
  dir.create(here("1_HLCM", "Data", "2_Fitted", f))
}
# BELOW IS JUST FOR TESTING
# n_iter      = 500
# n_warmup    = 200
# sim_numbers = 1:4


# -----------------------------------------------------------------------------------
# COMPILE MODELS
growth_model = data.frame(ID = 1:N) %>% group_by(ID) %>% summarise(session = 1:S) %>% 
  group_by(ID, session) %>% summarise(A_UT = 0) %>% 
      brm(A_UT ~ 1 + session + (1 + session|ID), data = ., seed = 43210,
          iter   = n_iter, warmup = n_warmup, chains = 0, cores  = 4,
          prior = c(set_prior("normal(0, 1)", class = "b"),
                    set_prior("normal(0, 1)", class = "Intercept"),
                    set_prior("lkj(1)", class = "cor"),
                    set_prior("normal(0, 1)", class = "sd"),
                    set_prior("normal(0, 1)", class = "sigma")))
HLCM_model   = cmdstan_model(here("1_HLCM", "Code", "Stan", "HLCM_Model.stan")) # Compile model
```


## Loop Through Conditions
```{r, }
start_timestamp = Sys.time()
registerDoParallel(clusters)


# -----------------------------------------------------------------------------------
# START SIMULATION
foreach(condition = conditions) %:% # LOOP THROUGH CONDITIONS
  foreach(sim = sim_numbers) %dopar% {
    # -----------------------------------------------------------------------------------
    # Setup for current simulation
    require(dplyr)
    require(posterior)
    simulation = readRDS(here::here("1_HLCM", "Data", "1_Simulations", condition,
                                    paste0("Data_", sim, ".RDS")))
    stan_data = simulation$stan_data
    mu_intercept_UT = simulation$mu_intercept_UT
    sd_intercept_UT = simulation$sd_intercept_UT
    mu_beta_UT = simulation$mu_beta_UT
    sd_beta_UT = simulation$sd_beta_UT
    int_slope_R = simulation$int_slope_R
    residual_sd = simulation$residual_sd
    parameters = simulation$parameters
    A_UTs = simulation$A_UTs
    As = simulation$As
    
    
    # -----------------------------------------------------------------------------------
    # Create initial data structure to fill during simulation
    RL_Simulations = data.frame()
    RL_Diagnostics = data.frame()
    RL_Characteristics = data.frame()
    
    HLCM_Simulations = data.frame()
    HLCM_Diagnostics = data.frame()
    HLCM_Characteristics = data.frame()
    
    
    # -----------------------------------------------------------------------------------
    # FIT HLCM MODEL TO EACH SESSION SEPARATELY
    ## Start with matrix to save data for growth model later
    unbounded_A_posterior = array(dim = c(n_iter*n_chains - (n_warmup*n_chains), S, N))
    A_posterior = array(dim = c(n_iter*n_chains - (n_warmup*n_chains), S, N))
    start_time = Sys.time()
    for(s in 1:S){
      RL_fit = HLCM_model$sample(
        data = list(N = stan_data$N,
                    T = stan_data$T,
                    S = 1,
                    choice = array(stan_data$choice[,,s], dim = c(stan_data$N, stan_data$T, 1)),
                    outcome = array(stan_data$outcome[,,s], dim = c(stan_data$N, stan_data$T, 1))),
                                 chains = n_chains,
                                 parallel_chains = 4,
                                 iter_warmup = n_warmup,
                                 iter_sampling = n_iter - n_warmup,
                                 seed = 43210)
      
      unbounded_A_posterior[,s,] = par_from_draws(RL_fit, "theta")$theta[,1,]
      A_posterior[,s,] = par_from_draws(RL_fit, "A")$A[,1,]
      # EXTRACT SUMMARY STATISTICS OF DATA
      RL_Summary = RL_fit$summary(variables = c("gamma00", "gamma10", "sigma_resid", "sigma_U",
                                                "beta0", "beta1", "theta", "A"),
                                  "mean", "sd", "rhat", "ess_bulk", "ess_tail",
                                  ~hBayesDM::HDIofMCMC(.x))
      # SAVE NON-RL DATA JUST IN CASE
      RL_Simulations =
        RL_Summary %>% 
        filter(stringr::str_detect(variable, "gamma00|gamma10|sigma_resid|sigma_U|beta0|beta1")) %>%
        select(parameter = variable, posterior_mean = mean, posterior_SD = sd,
               lower_HDI95 = `~hBayesDM::HDIofMCMC(.x).1`, upper_HDI95 = `~hBayesDM::HDIofMCMC(.x).2`) %>%
        mutate(hypermodel = "RL", model = paste0("RL_", s),
               condition = condition, simulation = sim,
               parameter_type = case_when(stringr::str_detect(parameter, "beta") ~ paste0("person_", parameter),
                                          T ~ "group"),
               parameter_type = stringr::str_remove(parameter_type, "beta0\\[|beta1\\["),
               parameter_type = stringr::str_remove(parameter_type, "\\]"),
               parameter = paste0("RL", s, "_", parameter),
               session = s,
               true_value = NA_real_, true_in_HDI95 = NA_real_, percentile = NA_real_) %>%
        bind_rows(RL_Simulations)
      # EXTRACT DIAGNOSTICS OF DATA
      RL_Diagnostics = RL_Summary %>% 
        dplyr::select(parameter = variable, rhat, ess_bulk, ess_tail) %>% 
        mutate(hypermodel = "RL", condition = condition, session = s, simulation = sim,
               parameter = paste0("RL", s, "_", parameter),
               parameter = case_when(stringr::str_detect(parameter, paste0("RL", s, "_theta|RL", s, "_A")) ~ 
                                       stringr::str_remove(parameter, paste0("RL", s, "_")), T ~ parameter),
               model = case_when(stringr::str_detect(parameter,
                                                     "gamma00|gamma10|sigma_resid|sigma_U|beta0|beta1") ~ paste0("RL_", s),
                                 T ~ "RL")) %>%
        bind_rows(RL_Diagnostics)
    }
    
    
    # -----------------------------------------------------------------------------------
    # FIT GROWTH MODEL
    growth_fit = data.frame(ID = 1:N, A_UTs = t(apply(unbounded_A_posterior, c(2, 3), mean))) %>%
      tidyr::pivot_longer(starts_with("A_UTs"), names_to = "session", values_to = "A_UT",
                   names_prefix = "A_UTs.", names_transform = list(session = as.numeric)) %>% 
      update(growth_model, newdata = ., recompile = F, seed   = 43210,
             iter   = n_iter, warmup = n_warmup, chains = n_chains, cores  = 4)
    
    sum_growth_model = data.frame(growth_fit)
    random_intercepts = dplyr::select(sum_growth_model, 
                                      starts_with("R_ID") & ends_with("Intercept.")) %>%
      as.matrix()
    random_slopes = dplyr::select(sum_growth_model, 
                                  starts_with("R_ID") & ends_with("session.")) %>%
      as.matrix()
    
    
    # -----------------------------------------------------------------------------------
    # SAVE GROUP-LEVEL GROWTH DATA
    ## Intercept
    cur_parameter = "intercept"
    cur_true_parameter = mu_intercept_UT
    cur_posterior = sum_growth_model$b_Intercept
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    RL_Simulations =
      data.frame(hypermodel = "RL", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(RL_Simulations)
    ## SD of Intercepts
    cur_parameter = "intercept_SD"
    cur_true_parameter = sd_intercept_UT
    cur_posterior = sum_growth_model$sd_ID__Intercept
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    RL_Simulations =
      data.frame(hypermodel = "RL", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(RL_Simulations)
    ## Slope
    cur_parameter = "slope"
    cur_true_parameter = mu_beta_UT
    cur_posterior = sum_growth_model$b_session
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    RL_Simulations =
      data.frame(hypermodel = "RL", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(RL_Simulations)
    ## SD of Slopes
    cur_parameter = "slope_SD"
    cur_true_parameter = sd_beta_UT
    cur_posterior = sum_growth_model$sd_ID__session
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    RL_Simulations =
      data.frame(hypermodel = "RL", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(RL_Simulations)
    ## Intercept-Slope Correlation
    cur_parameter = "int_slope_R"
    cur_true_parameter = int_slope_R
    cur_posterior = sum_growth_model$cor_ID__Intercept__session
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    RL_Simulations =
      data.frame(hypermodel = "RL", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(RL_Simulations)
    ## Residual
    cur_parameter = "residual_SD"
    cur_true_parameter = residual_sd
    cur_posterior = sum_growth_model$sigma
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    RL_Simulations =
      data.frame(hypermodel = "RL", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(RL_Simulations)
    
    
    # -----------------------------------------------------------------------------------
    # SAVE PERSON-LEVEL GROWTH DATA
    ## Intercepts
    cur_parameter = "intercept"
    cur_true_parameter = parameters[,1]
    cur_posterior = random_intercepts
    cur_hdi = t(apply(cur_posterior, 2, hBayesDM::HDIofMCMC))
    RL_Simulations =
      data.frame(hypermodel = "RL", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = paste0("person_", 1:N), session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = apply(cur_posterior, 2, mean),
                 posterior_SD = apply(cur_posterior, 2, sd),
                 lower_HDI95 = cur_hdi[,1], upper_HDI95 = cur_hdi[,2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[,1] & cur_true_parameter < cur_hdi[,2],
                 percentile = calculate_percentile(as.matrix(cur_true_parameter),
                                                   array(cur_posterior, dim = c(nrow(cur_posterior), 1, N)),
                                                   1)) %>% 
      bind_rows(RL_Simulations)
    ## Slopes
    cur_parameter = "slope"
    cur_true_parameter = parameters[,2]
    cur_posterior = random_slopes
    cur_hdi = t(apply(cur_posterior, 2, hBayesDM::HDIofMCMC))
    RL_Simulations =
      data.frame(hypermodel = "RL", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = paste0("person_", 1:N), session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = apply(cur_posterior, 2, mean),
                 posterior_SD = apply(cur_posterior, 2, sd),
                 lower_HDI95 = cur_hdi[,1], upper_HDI95 = cur_hdi[,2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[,1] & cur_true_parameter < cur_hdi[,2],
                 percentile = calculate_percentile(as.matrix(cur_true_parameter),
                                                   array(cur_posterior, dim = c(nrow(cur_posterior), 1, N)),
                                                   1)) %>% 
      bind_rows(RL_Simulations)
    
    
    # -----------------------------------------------------------------------------------
    # SAVE PERSON-LEVEL RL DATA
    ## Unbounded Learning Rates
    cur_parameter = "unbounded_A"
    cur_true_parameter = A_UTs
    cur_posterior = unbounded_A_posterior
    RL_Simulations =
      data.frame(hypermodel = "RL", model = "RL",
                 condition = condition, simulation = sim,
                 parameter_type = paste0("person_", 1:N),
                 true_value = cur_true_parameter, 
                 posterior_mean = t(apply(cur_posterior, c(2,3), mean)),
                 posterior_SD = t(apply(cur_posterior, c(2,3), sd)),
                 percentile = calculate_percentile(cur_true_parameter, cur_posterior, S),
                 aperm(apply(cur_posterior, c(2,3), hBayesDM::HDIofMCMC), c(3, 1, 2))) %>%
      dplyr::select(X1.1 = X1, X2.1 = X2, X1.2 = X3, X2.2 = X4, X1.3 = X5, X2.3 = X6,
                    everything()) %>% 
      tidyr::pivot_longer(starts_with(c("true", "posterior", "percentile", "X")), values_to = "value",
                   names_to = c("parameter", "session"), names_sep = "\\.",
                   names_transform = list(session = as.numeric)) %>%
      mutate(parameter = case_when(parameter == "X1" ~ "lower_HDI95",
                                   parameter == "X2" ~ "upper_HDI95",
                                   T ~ parameter)) %>%
      tidyr::pivot_wider(names_from = "parameter", values_from = "value") %>%
      mutate(parameter = cur_parameter,
             true_in_HDI95 = true_value > lower_HDI95 & true_value < upper_HDI95) %>% 
      bind_rows(RL_Simulations)
    ## Learning Rates
    cur_parameter = "A"
    cur_true_parameter = As
    cur_posterior = A_posterior
    RL_Simulations =
      data.frame(hypermodel = "RL", model = "RL",
                 condition = condition, simulation = sim,
                 parameter_type = paste0("person_", 1:N),
                 true_value = cur_true_parameter, 
                 posterior_mean = t(apply(cur_posterior, c(2,3), mean)),
                 posterior_SD = t(apply(cur_posterior, c(2,3), sd)),
                 percentile = calculate_percentile(cur_true_parameter, cur_posterior, S),
                 aperm(apply(cur_posterior, c(2,3), hBayesDM::HDIofMCMC), c(3, 1, 2))) %>%
      dplyr::select(X1.1 = X1, X2.1 = X2, X1.2 = X3, X2.2 = X4, X1.3 = X5, X2.3 = X6,
                    everything()) %>% 
      tidyr::pivot_longer(starts_with(c("true", "posterior", "percentile", "X")), values_to = "value",
                   names_to = c("parameter", "session"), names_sep = "\\.",
                   names_transform = list(session = as.numeric)) %>%
      mutate(parameter = case_when(parameter == "X1" ~ "lower_HDI95",
                                   parameter == "X2" ~ "upper_HDI95",
                                   T ~ parameter)) %>%
      tidyr::pivot_wider(names_from = "parameter", values_from = "value") %>%
      mutate(parameter = cur_parameter,
             true_in_HDI95 = true_value > lower_HDI95 & true_value < upper_HDI95) %>%
      bind_rows(RL_Simulations)
    
    saveRDS(dplyr::select(RL_Simulations,
                          hypermodel, model,
                          condition, simulation, session, parameter, parameter_type,
                          true_value, posterior_mean, posterior_SD, percentile,
                          lower_HDI95, upper_HDI95, true_in_HDI95),
            here::here("1_HLCM", "Data", "2_Fitted", condition, paste0("RL_Simulation_", sim, ".RDS")))
    
    
    # -----------------------------------------------------------------------------------
    # SAVE DIAGNOSTIC DATA
    # Growth Model Diagnostics
    rhats = rhat(growth_fit)
    growth_draws = as_draws_df(growth_fit)
    ESS = data.frame(parameter = names(growth_draws),
                     ess_bulk = sapply(growth_draws, posterior::ess_bulk),
                     ess_tail = sapply(growth_draws, posterior::ess_tail))
    RL_growth_diagnostics = data.frame(parameter = names(rhats), rhat = rhats) %>% 
      left_join(ESS) %>% 
      filter(!(parameter %in% c("lprior", "lp__")))
    RL_Diagnostics =
      RL_growth_diagnostics %>% 
      mutate(parameter = case_when(parameter == "b_Intercept" ~ "gamma00",
                                   parameter == "b_session" ~ "gamma10",
                                   parameter == "sd_ID__Intercept" ~ "sigma_U[1]",
                                   parameter == "sd_ID__session" ~ "sigma_U[2]",
                                   parameter == "sigma" ~ "sigma_resid",
                                   parameter == "cor_ID__Intercept__session" ~ "R_theta[2,1]",
                                   T ~ parameter),
             person_parameter = case_when(stringr::str_detect(parameter, ",Intercept") ~ "beta0",
                                          stringr::str_detect(parameter, ",session") ~ "beta1"),
             person_number = stringr::str_remove(parameter, "r_ID\\["),
             person_number = stringr::str_remove(person_number, ",Intercept\\]"),
             person_number = stringr::str_remove(person_number, ",session\\]"),
             parameter = case_when(!is.na(person_parameter) ~ paste0(person_parameter,"[",person_number,"]"),
                                   T ~ parameter),
             hypermodel = "RL", model = "growth", condition = condition,
             simulation = sim, session = 0) %>% 
      dplyr::select(hypermodel, condition, simulation, model, session, parameter, rhat, ess_bulk, ess_tail) %>% 
      bind_rows(RL_Diagnostics)
    
    saveRDS(dplyr::select(RL_Diagnostics,
                          hypermodel, model,
                          condition, simulation, model, session, parameter,
                          rhat, ess_bulk, ess_tail),
            here::here("1_HLCM", "Data", "2_Fitted", condition, paste0("RL_Diagnostics_", sim, ".RDS")))
    
    
    # -----------------------------------------------------------------------------------
    # SAVE CHARACTERISTICS OF SIMULATION
    RL_Characteristics = data.frame(
      hypermodel    = "RL",
      data_seed     = simulation$data_seed,
      condition     = condition,
      simulation    = sim,
      start         = start_time,
      end           = Sys.time(),
      duration      = difftime(Sys.time(), start_time),
      S             = S,
      N             = N,
      n_iter        = n_iter,
      n_warmup      = n_warmup,
      n_chains      = n_chains) %>% 
      bind_rows(RL_Characteristics)
    
    saveRDS(RL_Characteristics,
            here::here("1_HLCM", "Data", "2_Fitted", condition, paste0("RL_Characteristics_", sim, ".RDS")))
    
    
    # -----------------------------------------------------------------------------------
    # FIT HIERARCHICAL RL MODEL & EXTRACT ESTIMATES
    start_time = Sys.time()
    HLCM_fit = HLCM_model$sample(data = stan_data,
                                 chains = n_chains,
                                 parallel_chains = 4,
                                 iter_warmup = n_warmup,
                                 iter_sampling = n_iter - n_warmup,
                                 seed = 43210)
    
    
    # -----------------------------------------------------------------------------------
    # SAVE GROUP-LEVEL GROWTH DATA
    ## Intercept
    cur_parameter = "intercept"
    cur_true_parameter = mu_intercept_UT
    cur_posterior = par_from_draws(HLCM_fit, "gamma00")$gamma00
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    HLCM_Simulations =
      data.frame(hypermodel = "HLCM", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(HLCM_Simulations)
    ## SD of Intercepts
    cur_parameter = "intercept_SD"
    cur_true_parameter = sd_intercept_UT
    cur_posterior = par_from_draws(HLCM_fit, "sigma_U")$sigma_U[,1]
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    HLCM_Simulations =
      data.frame(hypermodel = "HLCM", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(HLCM_Simulations)
    ## Slopes
    cur_parameter = "slope"
    cur_true_parameter = mu_beta_UT
    cur_posterior = par_from_draws(HLCM_fit, "gamma10")$gamma10
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    HLCM_Simulations =
      data.frame(hypermodel = "HLCM", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(HLCM_Simulations)
    ## SD of Slopes
    cur_parameter = "slope_SD"
    cur_true_parameter = sd_beta_UT
    cur_posterior = par_from_draws(HLCM_fit, "sigma_U")$sigma_U[,2]
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    HLCM_Simulations =
      data.frame(hypermodel = "HLCM", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(HLCM_Simulations)
    ## Intercept-Slope Correlation
    cur_parameter = "int_slope_R"
    cur_true_parameter = int_slope_R
    cur_posterior = par_from_draws(HLCM_fit, "R_theta")$R_theta[,2,1]
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    HLCM_Simulations =
      data.frame(hypermodel = "HLCM", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(HLCM_Simulations)
    ## Residual
    cur_parameter = "residual_SD"
    cur_true_parameter = residual_sd
    cur_posterior = par_from_draws(HLCM_fit, "sigma_resid")$sigma_resid
    cur_hdi = hBayesDM::HDIofMCMC(cur_posterior)
    HLCM_Simulations =
      data.frame(hypermodel = "HLCM", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = "group", session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = mean(cur_posterior),
                 posterior_SD = sd(cur_posterior),
                 lower_HDI95 = cur_hdi[1], upper_HDI95 = cur_hdi[2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[1] & cur_true_parameter < cur_hdi[2],
                 percentile = mean(cur_posterior < cur_true_parameter)) %>% 
      bind_rows(HLCM_Simulations)
    
    
    # -----------------------------------------------------------------------------------
    # SAVE PERSON-LEVEL GROWTH DATA
    ## Intercepts
    cur_parameter = "intercept"
    cur_true_parameter = parameters[,1]
    cur_posterior = par_from_draws(HLCM_fit, "beta0")$beta0
    cur_hdi = t(apply(cur_posterior, 2, hBayesDM::HDIofMCMC))
    HLCM_Simulations =
      data.frame(hypermodel = "HLCM", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = paste0("person_", 1:N), session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = apply(cur_posterior, 2, mean),
                 posterior_SD = apply(cur_posterior, 2, sd),
                 lower_HDI95 = cur_hdi[,1], upper_HDI95 = cur_hdi[,2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[,1] & cur_true_parameter < cur_hdi[,2],
                 percentile = calculate_percentile(as.matrix(cur_true_parameter),
                                                   array(cur_posterior, dim = c(nrow(cur_posterior), 1, N)),
                                                   1)) %>% 
      bind_rows(HLCM_Simulations)
    ## Slopes
    cur_parameter = "slope"
    cur_true_parameter = parameters[,2]
    cur_posterior = par_from_draws(HLCM_fit, "beta1")$beta1
    cur_hdi = t(apply(cur_posterior, 2, hBayesDM::HDIofMCMC))
    HLCM_Simulations =
      data.frame(hypermodel = "HLCM", model = "growth",
                 condition = condition, simulation = sim, parameter = cur_parameter,
                 parameter_type = paste0("person_", 1:N), session = 0,
                 true_value = cur_true_parameter,
                 posterior_mean = apply(cur_posterior, 2, mean),
                 posterior_SD = apply(cur_posterior, 2, sd),
                 lower_HDI95 = cur_hdi[,1], upper_HDI95 = cur_hdi[,2],
                 true_in_HDI95 = cur_true_parameter > cur_hdi[,1] & cur_true_parameter < cur_hdi[,2],
                 percentile = calculate_percentile(as.matrix(cur_true_parameter),
                                                   array(cur_posterior, dim = c(nrow(cur_posterior), 1, N)),
                                                   1)) %>% 
      bind_rows(HLCM_Simulations)
    
    
    # -----------------------------------------------------------------------------------
    # SAVE PERSON-LEVEL RL DATA
    ## Unbounded Learning Rates
    cur_parameter = "unbounded_A"
    cur_true_parameter = A_UTs
    cur_posterior = par_from_draws(HLCM_fit, "theta")$theta
    HLCM_Simulations =
      data.frame(hypermodel = "HLCM", model = "RL",
                 condition = condition, simulation = sim,
                 parameter_type = paste0("person_", 1:N),
                 true_value = cur_true_parameter, 
                 posterior_mean = t(apply(cur_posterior, c(2,3), mean)),
                 posterior_SD = t(apply(cur_posterior, c(2,3), sd)),
                 percentile = calculate_percentile(cur_true_parameter, cur_posterior, S),
                 aperm(apply(cur_posterior, c(2,3), hBayesDM::HDIofMCMC), c(3, 1, 2))) %>%
      dplyr::select(lower_HDI95.1 = X1, upper_HDI95.1 = X2,
                    lower_HDI95.2 = X3, upper_HDI95.2 = X4,
                    lower_HDI95.3 = X5, upper_HDI95.3 = X6, everything()) %>% 
      tidyr::pivot_longer(starts_with(c("true", "posterior", "percentile", "lower", "upper")), values_to = "value",
                   names_to = c("parameter", "session"), names_sep = "\\.",
                   names_transform = list(session = as.numeric)) %>%
      tidyr::pivot_wider(names_from = "parameter", values_from = "value") %>%
      mutate(parameter = cur_parameter,
             true_in_HDI95 = true_value > lower_HDI95 & true_value < upper_HDI95) %>% 
      bind_rows(HLCM_Simulations)
    ## Learning Rates
    cur_parameter = "A"
    cur_true_parameter = As
    cur_posterior = par_from_draws(HLCM_fit, "A")$A
    HLCM_Simulations =
      data.frame(hypermodel = "HLCM", model = "RL",
                 condition = condition, simulation = sim,
                 parameter_type = paste0("person_", 1:N),
                 true_value = cur_true_parameter, 
                 posterior_mean = t(apply(cur_posterior, c(2,3), mean)),
                 posterior_SD = t(apply(cur_posterior, c(2,3), sd)),
                 percentile = calculate_percentile(cur_true_parameter, cur_posterior, S),
                 aperm(apply(cur_posterior, c(2,3), hBayesDM::HDIofMCMC), c(3, 1, 2))) %>%
      dplyr::select(lower_HDI95.1 = X1, upper_HDI95.1 = X2,
                    lower_HDI95.2 = X3, upper_HDI95.2 = X4,
                    lower_HDI95.3 = X5, upper_HDI95.3 = X6, everything()) %>% 
      tidyr::pivot_longer(starts_with(c("true", "posterior", "percentile", "lower", "upper")), values_to = "value",
                   names_to = c("parameter", "session"), names_sep = "\\.",
                   names_transform = list(session = as.numeric)) %>%
      tidyr::pivot_wider(names_from = "parameter", values_from = "value") %>%
      mutate(parameter = cur_parameter,
             true_in_HDI95 = true_value > lower_HDI95 & true_value < upper_HDI95) %>% 
      bind_rows(HLCM_Simulations)
    
    saveRDS(dplyr::select(HLCM_Simulations,
                          hypermodel, model,
                          condition, simulation, session, parameter, parameter_type,
                          true_value, posterior_mean, posterior_SD, percentile,
                          lower_HDI95, upper_HDI95, true_in_HDI95),
            here::here("1_HLCM", "Data", "2_Fitted", condition, paste0("HLCM_Simulation_", sim, ".RDS")))
    
    
    # -----------------------------------------------------------------------------------
    # SAVE DIAGNOSTIC DATA
    HLCM_Diagnostics = HLCM_fit$summary(variables = c("gamma00", "gamma10", "sigma_resid", "sigma_U",
                                                      "beta0", "beta1", "theta", "A","R_theta")) %>% 
      dplyr::select(parameter = variable, rhat, ess_bulk, ess_tail) %>%
      filter(!(parameter %in% c("R_theta[1,1]", "R_theta[1,2]", "R_theta[2,2]"))) %>% 
      mutate(hypermodel = "HLCM", model = case_when(parameter %in% c("theta", "A") ~ "RL", T ~ "growth"),
             condition = condition, simulation = sim,
             model = case_when(stringr::str_starts(parameter, "theta|A") ~ "RL", T ~ "growth"),
             session = case_when(stringr::str_detect(parameter, "\\[1,") ~ 1,
                                 stringr::str_detect(parameter, "\\[2,") ~ 2,
                                 stringr::str_detect(parameter, "\\[3,") ~ 3,
                                 T ~ 0)) %>% 
      bind_rows(HLCM_Diagnostics)
    
    saveRDS(dplyr::select(HLCM_Diagnostics,
                          hypermodel, model,
                          condition, simulation, model, session, parameter,
                          rhat, ess_bulk, ess_tail),
            here::here("1_HLCM", "Data", "2_Fitted", condition, paste0("HLCM_Diagnostics_", sim, ".RDS")))
    
    
    # -----------------------------------------------------------------------------------
    # SAVE CHARACTERISTICS OF SIMULATION
    HLCM_Characteristics = data.frame(
      hypermodel    = "HLCM",
      data_seed     = simulation$data_seed,
      condition     = condition,
      simulation    = sim,
      start         = start_time,
      end           = Sys.time(),
      duration      = difftime(Sys.time(), start_time),
      S             = S,
      N             = N,
      n_iter        = n_iter,
      n_warmup      = n_warmup,
      n_chains      = n_chains) %>% 
      bind_rows(HLCM_Characteristics)
    
    saveRDS(HLCM_Characteristics,
            here::here("1_HLCM", "Data", "2_Fitted", condition, paste0("HLCM_Characteristics_", sim, ".RDS")))
    
    # STOP TIME
    return(paste("Finished at", Sys.time()))
  }
stopCluster(clusters)


# -----------------------------------------------------------------------------------
# RECORD TIMESTAMPS
saveRDS(list(start = start_timestamp,
             end = Sys.time(),
             duration = difftime(Sys.time(), start_timestamp)),
        here::here("1_HLCM", "Data", "TimeStamp.RDS"))
```



# -------------------------------------------




