---
title: "Fitting RL HLCM"
output: html_document
---


# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
# library(wBoot)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
source(here("1_IGT_PP", "Code", "R", "3_other", "helpful_functions.R"))
library(MASS)
library(ggh4x)
library(grid)
library(extraDistr)
```


# -------------------------------------------
# Check Priors
```{r, eval = F}
iterations = 1000

gamma00 = vector(length = iterations)
gamma10 = vector(length = iterations)
sigma_U = matrix(data = NA, nrow = iterations, ncol = 2)
errors = vector(length = iterations)
corr = array(data = NA, c(2, 2, iterations))
beta = array(data = NA, c(iterations, 2, iterations))

for(i in 1:iterations){
  gamma00[i] = rnorm(1, mean = 0, sd = 1)
  gamma10[i] = rnorm(1, mean = 0, sd = .05)
  sigma_U[i,] = rhnorm(2, sigma = .05)
  errors[i] = rnorm(1, mean = 0, sd = .05)
  corr[,,i] = rethinking::rlkjcorr(1, K = 2, eta = 1)
  VC = diag(sigma_U[i,]) %*% corr[,,i] %*% diag(sigma_U[i,])
  
  beta[,,i] = mvrnorm(iterations, mu = c(gamma00[i], gamma10[i]), Sigma = VC) + errors[i]
}
hist(corr[1,2,], main = "Correlation", xlab = "r")
par(mfrow = c(2, 5))
for(s in 1:5){
  # GROUP-LEVEL PRIOR SESSION MEANS FOR LEARNING RATE
  hist(pnorm(gamma00+gamma10*(s-1)),
       main = paste("Group-Level As\nSession", s),
       xlab = "A")
}
for(s in 1:5){
  # PERSON-LEVEL PRIOR FOR LEARNING RATE ON EACH SESSION
  hist(pnorm(beta[,1,]+beta[,2,]*(s-1)),
       main = paste("Person-Level As\nSession", s),
       xlab = "A")
}
```


# -------------------------------------------
# Fitting RL Model
## Check Model
```{r, eval = F}
model_code = cmdstan_model(here("1_HLCM", "Code", "Stan",
                                "HLCM_RL_Model.stan"),
                           compile = F)

model_code$check_syntax(quiet = T)
```


## Fit Model
```{r, eval = T}
# -----------------------------------------------------------------------------------
RL_model = stan_model(here("1_HLCM", "Code", "Stan", "HLCM_RL_Model.stan")) # Compile model


# -----------------------------------------------------------------------------------
# Fit model
for(condition in c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR")){
  stan_data = readRDS(here("1_HLCM", "Data", "1_Stan",
                           paste0("RL_choices_", condition, ".RDS")))
  
  timestamp = list()
  timestamp$start = Sys.time()
  RL_fit = sampling(RL_model, 
                    data   = stan_data, 
                    iter   = 5000, 
                    warmup = 1000, 
                    chains = 4, 
                    cores  = 4,
                    seed   = 43210,
                    save_warmup = F)
  timestamp$end = Sys.time()
  
  saveRDS(timestamp, here("1_HLCM", "Data", "2_Fitted", paste0("HLCM_RL_", condition),
                          paste0("HLCM_RL_", condition, "_Timestamp.RDS")))
  saveRDS(RL_fit, here("1_HLCM", "Data", "2_Fitted", paste0("HLCM_RL_", condition),
                       paste0("HLCM_RL_", condition, "_Fit.RDS")))
  
  # -----------------------------------------------------------------------------------
  # save posteriors
  RL_posteriors = extract(RL_fit)
  saveRDS(RL_posteriors, here("1_HLCM", "Data", "2_Fitted", paste0("HLCM_RL_", condition),
                              paste0("HLCM_RL_", condition, "_Posteriors.RDS")))
  
  # -----------------------------------------------------------------------------------
  # save rhats
  RL_rhats = rhat(RL_fit, pars = c("gamma00", "gamma10", "R", "R_chol", "sigma_U", "z_U",
                                   "beta0", "beta1", "U", "theta", "A", "utility", "R_theta")) %>%
                    data.frame() %>% mutate(parameter = rownames(.))
  saveRDS(RL_rhats, here("1_HLCM", "Data", "2_Fitted", paste0("HLCM_RL_", condition),
                         paste0("HLCM_RL_", condition, "_Fhats.RDS")))
}
```


# -------------------------------------------
# Check Model
## Specify Condition
```{r}
condition = "LoB_LoR"
# condition = "HiB_LoR"
# condition = "LoB_HiR"
# condition = "HiB_HiR"
```


## Load Data
```{r}
parameters = readRDS(here("1_HLCM", "Data", "0_Simulated_RL",
                          paste0("RL_parameters_", condition, ".RDS")))
stan_data = readRDS(here("1_HLCM", "Data", "1_Stan",
                         paste0("RL_choices_", condition, ".RDS")))
```


# -------------------------------------------
# Diagnostics
```{r}

```


```{r}
pairs(RL_fit, pars = c("gamma00", "gamma10", "R", "R_chol", "sigma_U"))
```


```{r}
timestamp = readRDS(here("1_HLCM", "Data", "2_Fitted", paste0("HLCM_RL_", condition), "RL_HLCM_Timestamp.RDS"))
RL_fit = readRDS(here("1_HLCM", "Data", "2_Fitted", paste0("HLCM_RL_", condition), "RL_HLCM_Fit.RDS"))
RL_posteriors = readRDS(here("1_HLCM", "Data", "2_Fitted", paste0("HLCM_RL_", condition), "RL_HLCM_Posteriors.RDS"))
RL_rhats = readRDS(here("1_HLCM", "Data", "2_Fitted", paste0("HLCM_RL_", condition), "RL_HLCM_Rhats.RDS"))
```


# -------------------------------------------
# Assess Recovery
## Group-Level Parameters
```{r}
paste("Group-Level Intercept:",
      "True =", round(parameters$mu_intercept_UT, 3), "&",
      "Estimated =", round(mean(RL_posteriors$gamma00), 3))
paste("Group-Level Slope:",
      "True =", round(parameters$mu_beta_UT, 3), "&",
      "Estimated =", round(mean(RL_posteriors$gamma10), 3))


paste("Residual SD:",
      "True =", round(parameters$residual_sd, 3), "&",
      "Estimated =", round(mean(RL_posteriors$R), 3))
paste("SD for Intercepts:",
      "True =", round(parameters$sd_intercept_UT, 3), "&",
      "Estimated =", round(mean(RL_posteriors$sigma_U[,1]), 3))
paste("SD for Slopes:",
      "True =", round(parameters$sd_beta_UT, 3), "&",
      "Estimated  =", round(mean(RL_posteriors$sigma_U[,2]), 3))


paste("Correlation Between RIs & RSs:",
      "True =", round(parameters$int_slope_R, 3), "&",
      "Estimated =", round(mean(RL_posteriors$R_A[,2,1]), 3))
```


## Person-Level Parameters
```{r}
regression_parameters = data.frame(true_beta0 = parameters$parameters[,1],
                                   true_beta1 = parameters$parameters[,2],
                                   est_beta0 = apply(RL_posteriors$beta0, 2, mean),
                                   est_beta1 = apply(RL_posteriors$beta1, 2, mean))


est_A_UTs = data.frame(iteration = 1:nrow(RL_posteriors$beta0),
                      beta0 = RL_posteriors$beta0,
                      beta1 = RL_posteriors$beta1) %>% 
  pivot_longer(cols = starts_with("beta"), names_to = c("parameter", "ID"),
               values_to = "estimate", names_sep = "\\.",
               names_transform = list("ID" = as.integer)) %>%
  pivot_wider(names_from = "parameter", values_from = "estimate") %>% 
  cbind(data.frame(session1 = 1, session2 = 2, session3 = 3, 
                   session4 = 4, session5 = 5)) %>% 
  pivot_longer(starts_with("session"), names_to = "discard", values_to = "session") %>% 
  mutate(est_A_UT = beta0 + beta1*(session-1)) %>% 
  group_by(ID, session) %>% 
  summarise(est_A_UT = mean(est_A_UT))


RL_parameters = data.frame(ID = 1:N,
                           true_A = parameters$As,
                           true_A_UT = parameters$A_UTs,
                           est_A = t(apply(RL_posteriors$A, c(2, 3), mean))) %>% 
  pivot_longer(starts_with(c("true","est")),
               names_to = c("parameter", "session"), values_to = "estimate",
               names_sep = "\\.", names_transform = list("session" = as.integer)) %>% 
  pivot_wider(names_from = "parameter", values_from = "estimate") %>% 
  left_join(est_A_UTs) %>% 
  pivot_longer(starts_with(c("true", "est")),
               names_to = "parameter", values_to = "estimate") %>% 
  mutate(type = case_when(str_detect(parameter, "true") ~ "true", T ~ "est"),
         parameter = str_remove(parameter, "true_|est_")) %>% 
  pivot_wider(names_from = "type", values_from = "estimate") %>% 
  group_by(session, parameter) %>% 
  mutate(r = cor(true, est),
         r_lab = paste0("r=.", round(r*100)))
```


```{r}
person_level_plot = RL_parameters %>% 
    mutate(session_lab = case_when(parameter == "A_UT" ~ paste0("T", session), T ~ "")) %>% 
    ggplot(aes(x = true, y = est)) +
      ggpp::geom_text_npc(aes(npcx = "right", npcy = "bottom", label = session_lab),
                          hjust = .95, vjust = .25, size = 7) +
      geom_point() +
      geom_smooth(method = "lm", formula = y~x, se = F) +
      geom_text_npc(aes(npcx = "left", npcy = "top", label = r_lab), check_overlap = T) +
      scale_x_continuous(expand = expansion(mult = .025)) +
      scale_y_continuous(expand = expansion(mult = .025)) +
      labs(x = "True Person-Level Estimate", y = "Estimated Person-Level Estimate") +
      theme_classic() +
      theme(axis.text = element_blank(),
            axis.title = element_text(size = 16),
            strip.text = element_blank(),
            plot.margin = unit(c(1, .5, .5, .5), units = "cm")) +
      lemon::facet_rep_wrap(session~parameter, scales = "free", ncol = 2)

tiff(here("1_HLCM", "Figs_Tables", paste0("HLCM_RL_", condition),
          "RL True v Est Person-Level Parameters.tiff"),
     width = 10, height = 22, units = "cm", res = 300)

  # plot
  grid.newpage()
  pushViewport(viewport(x = .5, y = .5, width = 1, height = 1))
  grid.draw(person_level_plot)
  
  # text
  grid.text(c(expression(italic(A)), expression(paste("Unbounded ", italic(A)))),
            x = c(.325, .75), y = .98,
            gp = gpar(fontsize = 18))
  
dev.off()
```







