---
title: "Fitting RL"
output: html_document
---


# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
# library(wBoot)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
source(here("1_IGT_PP", "Code", "R", "3_other", "helpful_functions.R"))
library(MASS)
library(ggh4x)
library(grid)
library(extraDistr)
library(lme4)
```


## Specify Condition
```{r}
# condition = "LoB_LoR"
# condition = "HiB_LoR"
condition = "LoB_HiR"
# condition = "HiB_HiR"
```


## Load Data
```{r}
parameters = readRDS(here("1_HLCM", "Data", "0_Simulated_RL",
                          paste0("RL_parameters_", condition, ".RDS")))
stan_data = readRDS(here("1_HLCM", "Data", "1_Stan",
                         paste0("RL_choices_", condition, ".RDS")))
```


# -------------------------------------------
# Check Priors
```{r, eval = F}
iterations = 1000

gamma00 = rnorm(iterations, mean = 0, sd = 1)
sigma_U = rhnorm(iterations, sigma = .2)

theta = matrix(data = NA, nrow = iterations, ncol = iterations)
for(i in 1:iterations){
  theta[,i] = rnorm(iterations, mean = gamma00[i], sd = sigma_U[i])
}
par(mfrow = c(1, 2))
hist(pnorm(gamma00), main = "Group-Level A", xlab = "A") # GROUP-LEVEL PRIOR
hist(pnorm(theta), main = "Person-Level A", xlab = "A")  # PERSON-LEVEL PRIOR
```


# -------------------------------------------
# Fitting RL Model
## Check Model
```{r, eval = F}
model_code = cmdstan_model(here("1_HLCM", "Code", "Stan",
                                "RL_Model.stan"),
                           compile = F)

model_code$check_syntax(quiet = T)
```


## Fit Model
```{r, eval = F}
# -----------------------------------------------------------------------------------
RL_model = stan_model(here("1_HLCM", "Code", "Stan", "RL_Model.stan")) # Compile model


for(s in 1:stan_data$S){
  # -----------------------------------------------------------------------------------
  # Fit model
  timestamp = list()
  timestamp$start = Sys.time()
  RL_fit = sampling(RL_model, 
                    data   = list(N = stan_data$N,
                                  T = stan_data$T,
                                  choice = stan_data$choice[,,s],
                                  outcome = stan_data$outcome[,,s]), 
                    iter   = 5000, 
                    warmup = 1000, 
                    chains = 4, 
                    cores  = 4,
                    seed   = 43210,
                    save_warmup = F)
  timestamp$end = Sys.time()
  timestamp$diff = diff.POSIXt(c(timestamp$start, timestamp$end))
  
  saveRDS(timestamp, here("1_HLCM", "Data", "2_Fitted", paste0("RL_", condition),
                          paste0("S", s, "_Timestamp.RDS")))
  saveRDS(RL_fit, here("1_HLCM", "Data", "2_Fitted", paste0("RL_", condition),
                       paste0("S", s, "_Fit.RDS")))
  
  # -----------------------------------------------------------------------------------
  # save posteriors
  RL_posteriors = extract(RL_fit)
  saveRDS(RL_posteriors, here("1_HLCM", "Data", "2_Fitted", paste0("RL_", condition),
                              paste0("S", s, "_Posteriors.RDS")))
  
  # -----------------------------------------------------------------------------------
  # save rhats
  RL_rhats = rhat(RL_fit, pars = c("gamma00", "sigma_U", "z_U",
                                   "U", "theta", "A", "utility")) %>%
    data.frame() %>% mutate(parameter = rownames(.))
  saveRDS(RL_rhats, here("1_HLCM", "Data", "2_Fitted", paste0("RL_", condition),
                         paste0("S", s, "_Rhats.RDS")))
}
```


## Load Posteriors & Rhats
```{r}
timestamps = list()
RL_fit = list()
RL_posteriors = list()
RL_rhats = list()

for(s in 1:stan_data$S){
  # load timestamps
  timestamps[[paste0("S", s)]] =
    readRDS(here("1_HLCM", "Data", "2_Fitted", paste0("RL_", condition),
                 paste0("S", s, "_Timestamp.RDS")))
  
  # save fits
  RL_fit[[paste0("S", s)]] =
    readRDS(here("1_HLCM", "Data", "2_Fitted", paste0("RL_", condition),
                 paste0("S", s, "_Fit.RDS")))
  
  # load posteriors
  RL_posteriors[[paste0("S", s)]] =
    readRDS(here("1_HLCM", "Data", "2_Fitted", paste0("RL_", condition),
                 paste0("S", s, "_Posteriors.RDS")))
  
  # load rhats
  RL_rhats[[paste0("S", s)]] =
    readRDS(here("1_HLCM", "Data", "2_Fitted", paste0("RL_", condition),
                 paste0("S", s, "_Rhats.RDS")))
  View(RL_rhats[[paste0("S", s)]], title = paste("Session", s, "Rhats"))
}
```


# -------------------------------------------
# Diagnostics
## Traceplots
```{r, eval = T}
tiff(here("1_HLCM", "Figs_Tables", paste0("RL_", condition),
          "Group_Traceplots.tiff"),
     width = 20, height = 25, units = "cm", res = 300)
  egg::ggarrange(traceplot(RL_fit$S1, pars = c("gamma00", "sigma_U")) + labs(title = "Session 1"),
                 traceplot(RL_fit$S2, pars = c("gamma00", "sigma_U")) + labs(title = "Session 2"),
                 traceplot(RL_fit$S3, pars = c("gamma00", "sigma_U")) + labs(title = "Session 3"),
                 traceplot(RL_fit$S4, pars = c("gamma00", "sigma_U")) + labs(title = "Session 4"),
                 traceplot(RL_fit$S5, pars = c("gamma00", "sigma_U")) + labs(title = "Session 5"),
                 nrow = 5)
dev.off()
  
for(s in 1:stan_data$S){
  for(i in c("z_U", "U", "theta", "A")){
    tiff(here("1_HLCM", "Figs_Tables", paste0("RL_", condition),
              paste0("S", s, "_", i, "_traceplots.tiff")),
         width = 50, height = 50, units = "cm", res = 300)
      traceplot(RL_fit[[paste0("S", s)]], pars = i ) %>% print()
      dev.off()
  }
}
```


# -------------------------------------------
# Assess ORL Parameter Recovery
## Group-Level Parameters
```{r}
for(s in 1:stan_data$S){
  print(paste("Session", s))
  paste("   Group-Level Means:",
        "True =", round(parameters$mu_intercept_UT + parameters$mu_beta_UT*(s-1), 3), "&",
        "Estimated =", round(mean(RL_posteriors[[paste0("S", s)]]$gamma00), 3)) %>% 
    print()
  
  paste("   SD for Intercepts:",
        "True =", round(parameters$sd_intercept_UT, 3), "&",
        "Estimated =", round(mean(RL_posteriors[[paste0("S", s)]]$sigma_U), 3)) %>% 
    print()
}
```


## Person-Level Parameters
```{r}
RL_parameters = data.frame()
for(s in 1:stan_data$S){
  RL_parameters = data.frame(ID = 1:stan_data$N, session = s,
                             true_theta = parameters$A_UTs[,s],
                             est_theta = apply(RL_posteriors[[paste0("S",s)]]$theta, 2, mean),
                             true_A = parameters$As[,s],
                             est_A = apply(RL_posteriors[[paste0("S",s)]]$A, 2, mean)) %>% 
    bind_rows(RL_parameters)
}

RL_parameters = RL_parameters %>% 
  pivot_longer(starts_with(c("true", "est")),
               names_to = "parameter", values_to = "estimate") %>% 
  mutate(type = case_when(str_detect(parameter, "true") ~ "true", T ~ "est"),
         parameter = str_remove(parameter, "true_|est_")) %>% 
  pivot_wider(names_from = "type", values_from = "estimate") %>% 
  group_by(session, parameter) %>% 
  mutate(r = cor(true, est),
         r_lab = paste0("r=.", round(r*100)))
```


```{r}
person_level_plot = RL_parameters %>% 
    mutate(session_lab = case_when(parameter == "A_UT" ~ paste0("T", session), T ~ "")) %>% 
    ggplot(aes(x = true, y = est)) +
      ggpp::geom_text_npc(aes(npcx = "right", npcy = "bottom", label = session_lab),
                          hjust = .95, vjust = .25, size = 7) +
      geom_point() +
      geom_smooth(method = "lm", formula = y~x, se = F) +
      geom_text_npc(aes(npcx = "left", npcy = "top", label = r_lab), check_overlap = T) +
      scale_x_continuous(expand = expansion(mult = .025)) +
      scale_y_continuous(expand = expansion(mult = .025)) +
      labs(x = "True Person-Level Estimate", y = "Estimated Person-Level Estimate") +
      theme_classic() +
      theme(axis.text = element_blank(),
            axis.title = element_text(size = 16),
            strip.text = element_blank(),
            plot.margin = unit(c(1, .5, .5, .5), units = "cm")) +
      lemon::facet_rep_wrap(session~parameter, scales = "free", ncol = 2)

tiff(here("1_HLCM", "Figs_Tables", paste0("RL_", condition),
          "True v Est Person-Level Parameters.tiff"),
     width = 10, height = 22, units = "cm", res = 300)

  # plot
  grid.newpage()
  pushViewport(viewport(x = .5, y = .5, width = 1, height = 1))
  grid.draw(person_level_plot)
  
  # text
  grid.text(c(expression(italic(A)), expression(paste("Unbounded ", italic(A)))),
            x = c(.325, .75), y = .98,
            gp = gpar(fontsize = 18))
  
dev.off()
```


# -------------------------------------------
# Assess Growth Parameter Recovery
## Fit LMER Model
```{r}
growth_model = RL_parameters %>% 
  filter(parameter == "theta") %>% 
  lmer(est ~ session + (session|ID),
             data = ., REML = T)
growth_model
```


## Quantitative Comparison
```{r}
paste0("Intercept: ",
       "True = ", round(parameters$mu_intercept_UT, 3), " & ",
       "Estimated = ", round(summary(growth_model)$coefficients["(Intercept)", "Estimate"], 3))

cur_p = round(car::Anova(growth_model, type = "III")["session", "Pr(>Chisq)"], 3)
cur_p = ifelse(cur_p == 0, "< .05", paste0("= ", cur_p))
paste0("Slope: ",
       "True = ", round(parameters$mu_beta_UT, 3), " & ",
       "Estimated = ", round(summary(growth_model)$coefficients["session", "Estimate"], 3),
       ", p = ", cur_p)

paste("Intercept-Slope Correlation:",
      "True =", round(parameters$int_slope_R, 3), "&",
      "Estimated =", round(attr(VarCorr(growth_model)$ID, "correlation")["(Intercept)", "session"], 3))
```


## Visual Comparison
```{r}
RL_parameters %>% 
  # PREP DATA
  ungroup() %>% filter(parameter == "theta") %>% 
  dplyr::select(ID, session, true, est) %>% 
  pivot_longer(c("true", "est"), values_to = "theta",
               names_to = "type") %>%  
  # PLOT
  ggplot(aes(x = session, y = theta, group = interaction(session, type),
             color = type, fill = type)) +
    # GEOMS
    geom_violin(position = position_dodge(width = .5), trim = F, alpha = .05,
                linewidth = .5, width = 1) +
    geom_point(position = position_dodge(width = .5), alpha = .5) +
    geom_abline(intercept = parameters$mu_intercept_UT, slope = parameters$mu_beta_UT,
                color = "dodgerblue3", size = 1) +
    geom_abline(intercept = summary(growth_model)$coefficients["(Intercept)", "Estimate"],
                slope = summary(growth_model)$coefficients["session", "Estimate"],
                color = "goldenrod3", size = 1) +
    # SCALES
    scale_color_manual(values = c("goldenrod3", "dodgerblue3"), 
                       labels = c("est" = "Estimated", "true" = "True")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3"), 
                      labels = c("est" = "Estimated", "true" = "True")) +
    # THEMES
    labs(x = "Session", y = expression(italic(A))) +
    theme_classic() +
    theme(axis.text = element_text(color = "black"),
          legend.title = element_blank(),
          legend.position = c(.1, .9))
```









