---
title: "Fitting RL HLCM"
output: html_document
---


# -------------------------------------------
# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
# library(wBoot)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
source(here("1_IGT_PP", "Code", "R", "3_other", "helpful_functions.R"))
library(MASS)
library(ggh4x)
library(grid)
library(extraDistr)
```


# -------------------------------------------
# Check Priors
```{r, eval = T}
iterations = 1000

gamma00 = vector(length = iterations)
gamma10 = vector(length = iterations)
sigma_U = matrix(data = NA, nrow = iterations, ncol = 2)
errors = vector(length = iterations)
corr = vector(length = iterations)
beta = array(data = NA, c(iterations, 2, iterations))

for(i in 1:iterations){
  gamma00[i] = rnorm(1, mean = 0, sd = 1)
  gamma10[i] = rnorm(1, mean = 0, sd = 1)
  sigma_U[i,] = rhnorm(2, sigma = 1)
  errors[i] = rnorm(1, mean = 0, sd = 1)
  corr[i] = ggdist::rlkjcorr_marginal(1, K = 2, eta = 1)
  VC = diag(sigma_U[i,]) %*% matrix(c(1, corr[i], corr[i], 1), nrow = 2) %*% diag(sigma_U[i,])
  
  beta[,,i] = mvrnorm(iterations, mu = c(gamma00[i], gamma10[i]), Sigma = VC) + errors[i]
}
hist(corr, main = "Correlation", xlab = "r")
par(mfrow = c(2, 3))
for(s in 1:3){
  # GROUP-LEVEL PRIOR SESSION MEANS FOR LEARNING RATE
  hist(pnorm(gamma00+gamma10*(s-1)),
       main = paste("Group-Level As\nSession", s),
       xlab = "A")
}
for(s in 1:3){
  # PERSON-LEVEL PRIOR FOR LEARNING RATE ON EACH SESSION
  hist(pnorm(beta[,1,]+beta[,2,]*(s-1)),
       main = paste("Person-Level As\nSession", s),
       xlab = "A")
}
```


# -------------------------------------------



