---
title: "Process RL Simulation"
output: 
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: true
---


```{css, echo = F}
#TOC {
    max-width: fit-content;
    white-space: nowrap;
  }
  
  div:has(> #TOC) {
    display: flex;
    flex-direction: row-reverse;
}
div.tocify {
width: 100%;
}
```


# -------------------------------------------
# Setup
## Load Packages
```{r setup, include = F}
knitr::opts_chunk$set(echo = F, warning = F, message = F, fig.align = "center")

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
library(MASS)
library(ggh4x)
library(grid)
library(extraDistr)
library(lme4)
library(kableExtra)
```


## Import Models
```{r}
conditions  = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR")
sim_numbers = 1:100

characteristics = data.frame()
diagnostics     = data.frame()
simulations     = data.frame()

for(condition in conditions){
  for(sim in sim_numbers){
    characteristics = bind_rows(characteristics,
                                readRDS(here("1_HLCM", "Data", "2_Fitted", condition,
                                             paste0("RL_Characteristics_", sim, ".RDS"))),
                                readRDS(here("1_HLCM", "Data", "2_Fitted", condition,
                                             paste0("HLCM_Characteristics_", sim, ".RDS"))))
    diagnostics = bind_rows(diagnostics,
                            readRDS(here("1_HLCM", "Data", "2_Fitted", condition,
                                         paste0("RL_Diagnostics_", sim, ".RDS"))),
                            readRDS(here("1_HLCM", "Data", "2_Fitted", condition,
                                         paste0("HLCM_Diagnostics_", sim, ".RDS"))))
    simulations = bind_rows(simulations,
                            readRDS(here("1_HLCM", "Data", "2_Fitted", condition,
                                         paste0("RL_Simulation_", sim, ".RDS"))),
                            readRDS(here("1_HLCM", "Data", "2_Fitted", condition,
                                         paste0("HLCM_Simulation_", sim, ".RDS"))))
  }
}
```


## Check Data
```{r, eval = F}
checks = data.frame()

for(cond in conditions){
  for(sim in 1:5){
    data = readRDS(here::here("1_HLCM", "Data", "1_Simulations", cond,
                              paste0("Data_", sim, ".RDS")))
    check_data = readRDS(here::here("1_HLCM", "Data", "1_Simulations", "Check", cond,
                                    paste0("Data_", sim, ".RDS")))
    
    
    # INTERCEPTS & SLOPES
    checks = data.frame(ID = 1:50,
               cur = data$parameters,
               check = check_data$parameters) %>%
      pivot_longer(starts_with(c("cur", "check")), values_to = "datum",
                   names_to = c("type", "parameter"), names_sep = "\\.") %>% 
      pivot_wider(names_from = "type", values_from = "datum") %>% 
      mutate(diff = cur-check) %>% 
      summarise(simulation = sim,
                parameter = "int-slope",
                check = mean(diff)) %>% 
      bind_rows(checks)
    
    
    # UNBOUNDED As
    data.frame(ID = 1:50,
               cur = data$A_UTs,
               check = check_data$A_UTs) %>%
      pivot_longer(starts_with(c("cur", "check")), values_to = "datum",
                   names_to = c("type", "parameter"), names_sep = "\\.") %>% 
      pivot_wider(names_from = "type", values_from = "datum") %>% 
      mutate(diff = cur-check) %>% 
      summarise(simulation = sim,
                parameter = "Unbounded As",
                check = mean(diff)) %>% 
      bind_rows(checks)
    
    
    # BOUNDED As
    data.frame(ID = 1:50,
               cur = data$As,
               check = check_data$As) %>%
      pivot_longer(starts_with(c("cur", "check")), values_to = "datum",
                   names_to = c("type", "parameter"), names_sep = "\\.") %>% 
      pivot_wider(names_from = "type", values_from = "datum") %>% 
      mutate(diff = cur-check) %>% 
      summarise(simulation = sim,
                parameter = "Bounded As",
                check = mean(diff)) %>% 
      bind_rows(checks)
    
    # CHOICE
    data.frame(ID = 1:50,
               cur = data$stan_data$choice,
               check = check_data$stan_data$choice) %>%
      pivot_longer(starts_with(c("cur", "check")), values_to = "datum",
                   names_to = c("type", "parameter"), names_sep = "\\.") %>% 
      pivot_wider(names_from = "type", values_from = "datum") %>% 
      mutate(diff = cur-check) %>% 
      summarise(simulation = sim,
                parameter = "Choice",
                check = mean(diff)) %>% 
      bind_rows(checks)
  }
}
```


# -------------------------------------------
# Distribution of Durations
```{r, fig.height=6, fig.width=6}
summarized_durations = characteristics %>%
  group_by(hypermodel) %>% 
  summarise(total = round(sum(as.numeric(duration, units = "hours")), 2),
            avg = round(mean(as.numeric(duration, units = "mins")), 2)) %>% 
  pivot_wider(names_from = "hypermodel", values_from = c("total", "avg"))

characteristics %>% 
  group_by(hypermodel, condition) %>% 
  mutate(duration = as.numeric(duration, units = "mins"),
         mean_duration = mean(duration)) %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = duration, fill = hypermodel)) +
    # GEOMS
    geom_histogram(color = "black", linewidth = .75, bins = 50) +
    geom_hline(yintercept = 0) +
    geom_vline(aes(xintercept = mean_duration, color = hypermodel),
               linewidth = .75, linetype = "dashed", show.legend = F) +
    # SCALES
    scale_x_continuous(n.breaks = 4, expand = expansion(mult = .05)) +
    scale_y_continuous(limits = c(0,NA), expand = expansion(mult = c(0, .1)), n.breaks = 3) +
    scale_color_manual(values = c("goldenrod3", "dodgerblue3")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(x = "Fit Duration (Mins)", y = "Frequency",
         caption = paste0("RL Duration: Total = ", summarized_durations$total_RL, " hours, Mean/Simulation = ",
                          summarized_durations$avg_RL, " mins \n",
                          "HLCM Duration: Total = ", summarized_durations$total_HLCM, " hours, Mean/Simulation = ",
                          summarized_durations$avg_HLCM, " mins")) +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title = element_text(size = 14),
          legend.title = element_blank(),
          plot.caption = element_text(hjust = 0),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing = unit(.5, "cm"),
          strip.text = element_text(size = 14),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_grid(condition_lab~hypermodel, scales = "free",
                   labeller = label_parsed)
```


# -------------------------------------------
# Group-Level Growth Parameters
## Posterior Means
```{r, fig.height=10, fig.width=9}
simulations %>% 
  filter(parameter_type == "group") %>%
  group_by(hypermodel, condition, parameter) %>% 
  mutate(mean_posterior_mean = mean(posterior_mean)) %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = posterior_mean, fill = hypermodel)) +
    # GEOMS
    geom_histogram(color = "black", linewidth = .75, bins = 50) +
    geom_hline(yintercept = 0) +
    geom_vline(aes(xintercept = true_value), color = "red2", linewidth = .75) +
    geom_vline(aes(xintercept = mean_posterior_mean, color = hypermodel), 
               linewidth = .75, linetype = "dashed", show.legend = F) +
    # SCALES
    scale_x_continuous(n.breaks = 3, expand = expansion(mult = .05)) +
    scale_y_continuous(limits = c(0,NA), expand = expansion(mult = c(0, .1)), n.breaks = 3) +
    scale_color_manual(values = c("goldenrod3", "dodgerblue3")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(x = "Posterior Mean", y = "Frequency") +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title = element_text(size = 14),
          legend.title = element_blank(),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing = unit(.05, "cm"),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_wrap(parameter~condition_lab, scales = "free", ncol = 4,
                   labeller = label_parsed)
```


## Percentiles
```{r, fig.height=10, fig.width=9}
simulations %>% 
  filter(parameter_type == "group") %>%
  group_by(hypermodel, condition, parameter) %>% 
  mutate(mean_percentile = mean(percentile)) %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = percentile, fill = hypermodel)) +
    # GEOMS
    geom_histogram(color = "black", linewidth = .75, bins = 50) +
    geom_vline(xintercept = .5, color = "red2", linewidth = .75) +
    geom_vline(aes(xintercept = mean_percentile, color = hypermodel),
               linewidth = .75, linetype = "dashed", show.legend = F) +
    geom_hline(yintercept = 0) +
    # SCALES
    scale_x_continuous(limits = c(-.05, 1.05), expand = c(0, 0),
                       breaks = c(0, .5, 1), labels = c("0", ".5", "1")) +
    scale_y_continuous(limits = c(0,NA), expand = expansion(mult = c(0, .1)), n.breaks = 3) +
    scale_color_manual(values = c("goldenrod3", "dodgerblue3")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(x = "Percentile", y = "Frequency") +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title = element_text(size = 14),
          legend.title = element_blank(),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing = unit(.25, "cm"),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_grid(parameter~condition_lab, scales = "free", labeller = label_parsed)
```


## True in HDI
```{r, fig.height=10, fig.width=9}
simulations %>% 
  filter(parameter_type == "group") %>%
  group_by(condition, parameter, hypermodel) %>% 
  summarise(true_in_HDI95 = mean(true_in_HDI95)*100) %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = parameter, y = true_in_HDI95, fill = hypermodel)) +
    # GEOMS
    geom_bar(color = "black", linewidth = .75, stat = "identity") +
    geom_text(aes(label = paste0(round(true_in_HDI95), "%")), vjust = -.5) +
    # SCALES
    scale_y_continuous(limits = c(0,100), expand = c(0,0)) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(y = "Percent True Parameter in 95% HDI") +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text.x = element_text(color = "black", size = 12, angle = 90, vjust = .5),
          axis.text.y = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title.y = element_text(size = 14),
          axis.title.x = element_blank(),
          legend.title = element_blank(),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing.x = unit(.25, "cm"),
          panel.spacing.y = unit(1, "cm"),
          strip.text = element_text(size = 14),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_grid(condition_lab~hypermodel, scales = "free", labeller = label_parsed)
```


# -------------------------------------------
# Person-Level Parameters
## True vs. Estimated Correlations
### Intercepts
```{r, fig.height=8, fig.width=7}
simulations %>% 
  filter(parameter_type != "group" & parameter == "intercept") %>%
  group_by(simulation, condition, hypermodel, parameter) %>% 
  summarise(r = cor(true_value, posterior_mean)) %>% 
  group_by(hypermodel, condition, parameter) %>% 
  mutate(mean_r = mean(r)) %>% ungroup() %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = r, fill = hypermodel)) +
    # GEOMS
    geom_histogram(color = "black", linewidth = .75, bins = 50) +
    geom_hline(yintercept = 0) +
    geom_vline(aes(xintercept = mean_r, color = hypermodel),
               linewidth = .75, linetype = "dashed", show.legend = F) +
    geom_text_npc(aes(npcx = "left", npcy = "top", label = paste0("r = ", round(mean_r, 2)))) +
    # SCALES
    scale_x_continuous(limits = c(-1,1), expand = expansion(mult = .05)) +
    scale_y_continuous(limits = c(0,NA), expand = expansion(mult = c(0, .1)), n.breaks = 3) +
    scale_color_manual(values = c("goldenrod3", "dodgerblue3")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(x = "Correlation B/w True & Estimated Parameter", y = "Frequency") +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title = element_text(size = 14),
          legend.title = element_blank(),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing = unit(.5, "cm"),
          strip.text = element_text(size = 14),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_grid(condition_lab~hypermodel, scales = "free",
                   labeller = label_parsed)
```


### Slopes
```{r, fig.height=8, fig.width=7}
simulations %>% 
  filter(parameter_type != "group" & parameter == "slope") %>%
  group_by(simulation, condition, hypermodel, parameter) %>% 
  summarise(r = cor(true_value, posterior_mean)) %>% 
  group_by(hypermodel, condition, parameter) %>% 
  mutate(mean_r = mean(r)) %>% ungroup() %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = r, fill = hypermodel)) +
    # GEOMS
    geom_histogram(color = "black", linewidth = .75, bins = 50) +
    geom_hline(yintercept = 0) +
    geom_vline(aes(xintercept = mean_r, color = hypermodel),
               linewidth = .75, linetype = "dashed", show.legend = F) +
    geom_text_npc(aes(npcx = "left", npcy = "top", label = paste0("r = ", round(mean_r, 2)))) +
    # SCALES
    scale_x_continuous(limits = c(-1,1), expand = expansion(mult = .05)) +
    scale_y_continuous(limits = c(0,NA), expand = expansion(mult = c(0, .1)), n.breaks = 3) +
    scale_color_manual(values = c("goldenrod3", "dodgerblue3")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(x = "Correlation B/w True & Estimated Parameter", y = "Frequency") +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title = element_text(size = 14),
          legend.title = element_blank(),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing = unit(.5, "cm"),
          strip.text = element_text(size = 14),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_grid(condition_lab~hypermodel, scales = "free",
                   labeller = label_parsed)
```


### Unbounded A
```{r, fig.height=8, fig.width=7}
simulations %>% 
  filter(parameter_type != "group" & parameter == "unbounded_A") %>%
  group_by(simulation, condition, hypermodel, parameter) %>% 
  summarise(r = cor(true_value, posterior_mean)) %>% 
  group_by(hypermodel, condition, parameter) %>% 
  mutate(mean_r = mean(r)) %>% ungroup() %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = r, fill = hypermodel)) +
    # GEOMS
    geom_histogram(color = "black", linewidth = .75, bins = 50) +
    geom_hline(yintercept = 0) +
    geom_vline(aes(xintercept = mean_r, color = hypermodel),
               linewidth = .75, linetype = "dashed", show.legend = F) +
    geom_text_npc(aes(npcx = "left", npcy = "top", label = paste0("r = ", round(mean_r, 2)))) +
    # SCALES
    scale_x_continuous(limits = c(-1,1), expand = expansion(mult = .05)) +
    scale_y_continuous(limits = c(0,NA), expand = expansion(mult = c(0, .1)), n.breaks = 3) +
    scale_color_manual(values = c("goldenrod3", "dodgerblue3")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(x = "Correlation B/w True & Estimated Parameter", y = "Frequency") +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title = element_text(size = 14),
          legend.title = element_blank(),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing = unit(.5, "cm"),
          strip.text = element_text(size = 14),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_grid(condition_lab~hypermodel, scales = "free",
                   labeller = label_parsed)
```


### A
```{r, fig.height=8, fig.width=7}
simulations %>% 
  filter(parameter_type != "group" & parameter == "A") %>%
  group_by(simulation, condition, hypermodel, parameter) %>% 
  summarise(r = cor(true_value, posterior_mean)) %>% 
  group_by(hypermodel, condition, parameter) %>% 
  mutate(mean_r = mean(r)) %>% ungroup() %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = r, fill = hypermodel)) +
    # GEOMS
    geom_histogram(color = "black", linewidth = .75, bins = 50) +
    geom_hline(yintercept = 0) +
    geom_vline(aes(xintercept = mean_r, color = hypermodel),
               linewidth = .75, linetype = "dashed", show.legend = F) +
    geom_text_npc(aes(npcx = "left", npcy = "top", label = paste0("r = ", round(mean_r, 2)))) +
    # SCALES
    scale_x_continuous(limits = c(-1,1), expand = expansion(mult = .05)) +
    scale_y_continuous(limits = c(0,NA), expand = expansion(mult = c(0, .1)), n.breaks = 3) +
    scale_color_manual(values = c("goldenrod3", "dodgerblue3")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(x = "Correlation B/w True & Estimated Parameter", y = "Frequency") +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title = element_text(size = 14),
          legend.title = element_blank(),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing = unit(.5, "cm"),
          strip.text = element_text(size = 14),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_grid(condition_lab~hypermodel, scales = "free",
                   labeller = label_parsed)
```


## Percentiles
```{r, fig.height=10, fig.width=9}
simulations %>% 
  filter(parameter_type != "group") %>%
  group_by(hypermodel, condition, parameter) %>% 
  mutate(mean_percentile = mean(percentile)) %>% ungroup() %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = percentile, fill = hypermodel)) +
    # GEOMS
    geom_histogram(color = "black", linewidth = .75, bins = 50) +
    geom_vline(xintercept = .5, color = "red2", linewidth = .75) +
    geom_hline(yintercept = 0) +
    geom_vline(aes(xintercept = mean_percentile, color = hypermodel),
               linewidth = .75, linetype = "dashed", show.legend = F) +
    # SCALES
    scale_x_continuous(limits = c(-.05, 1.05), expand = c(0, 0)) +
    scale_y_continuous(limits = c(0,NA), expand = expansion(mult = c(0, .1)), n.breaks = 3) +
    scale_color_manual(values = c("goldenrod3", "dodgerblue3")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(x = "Percentile", y = "Frequency") +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title = element_text(size = 14),
          legend.title = element_blank(),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing = unit(.5, "cm"),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_grid(parameter~condition_lab, labeller = label_parsed,
                   scales = "free")
```


## True in HDI
```{r, fig.height=10, fig.width=9}
simulations %>% 
  filter(parameter_type != "group") %>%
  group_by(condition, parameter, hypermodel) %>% 
  summarise(true_in_HDI95 = mean(true_in_HDI95)*100) %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = parameter, y = true_in_HDI95, fill = hypermodel)) +
    # GEOMS
    geom_bar(color = "black", linewidth = .75, stat = "identity") +
    geom_text(aes(label = paste0(round(true_in_HDI95), "%")), vjust = -.5) +
    # SCALES
    scale_y_continuous(limits = c(0,100), expand = c(0,0)) +
    scale_color_manual(values = c("goldenrod3", "dodgerblue3")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(y = "Percent True Parameter in 95% HDI") +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text.x = element_text(color = "black", size = 12, angle = 90, vjust = .5),
          axis.text.y = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title.y = element_text(size = 14),
          axis.title.x = element_blank(),
          legend.title = element_blank(),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing.x = unit(.25, "cm"),
          panel.spacing.y = unit(1, "cm"),
          strip.text = element_text(size = 14),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_grid(condition_lab~hypermodel, scales = "free", labeller = label_parsed)
```


# -------------------------------------------
# Diagnostics
```{r, fig.height=6, fig.width=6}
summarized_durations = characteristics %>%
  group_by(hypermodel) %>% 
  summarise(total = round(sum(as.numeric(duration, units = "hours")), 2),
            avg = round(mean(as.numeric(duration, units = "mins")), 2)) %>% 
  pivot_wider(names_from = "hypermodel", values_from = c("total", "avg"))

characteristics %>% 
  group_by(hypermodel, condition) %>% 
  mutate(duration = as.numeric(duration, units = "mins"),
         mean_duration = mean(duration)) %>% 
  mutate(hypermodel = factor(hypermodel, levels = c("RL", "HLCM"), ordered = T),
         condition_lab = factor(condition, levels = c("LoB_LoR", "HiB_LoR", "LoB_HiR", "HiB_HiR"),
                                labels = c(expression("Lo~\u03B2~Lo~r"),
                                           expression("Hi~\u03B2~Lo~r"),
                                           expression("Lo~\u03B2~Hi~r"),
                                           expression("Hi~\u03B2~Hi~r")))) %>% 
  ggplot(aes(x = duration, fill = hypermodel)) +
    # GEOMS
    geom_histogram(color = "black", linewidth = .75, bins = 50) +
    geom_hline(yintercept = 0) +
    geom_vline(aes(xintercept = mean_duration, color = hypermodel),
               linewidth = .75, linetype = "dashed", show.legend = F) +
    # SCALES
    scale_x_continuous(n.breaks = 4, expand = expansion(mult = .05)) +
    scale_y_continuous(limits = c(0,NA), expand = expansion(mult = c(0, .1)), n.breaks = 3) +
    scale_color_manual(values = c("goldenrod3", "dodgerblue3")) +
    scale_fill_manual(values = c("goldenrod3", "dodgerblue3")) +
    # THEMES
    labs(x = "Fit Duration (Mins)", y = "Frequency",
         caption = paste0("RL Duration: Total = ", summarized_durations$total_RL, " hours, Mean/Simulation = ",
                          summarized_durations$avg_RL, " mins \n",
                          "HLCM Duration: Total = ", summarized_durations$total_HLCM, " hours, Mean/Simulation = ",
                          summarized_durations$avg_HLCM, " mins")) +
    coord_cartesian(clip = "off") +
    theme_classic() +
    theme(axis.text = element_text(color = "black", size = 12),
          axis.ticks = element_line(color = "black", linewidth = .75),
          axis.line = element_line(linewidth = .75),
          axis.title = element_text(size = 14),
          legend.title = element_blank(),
          plot.caption = element_text(hjust = 0),
          plot.margin = unit(c(.1, .3, .1, .3), "cm"),
          panel.spacing = unit(.5, "cm"),
          strip.text = element_text(size = 14),
          strip.background = element_rect(fill = "transparent", colour = "transparent"),
          panel.background = element_rect(fill = "transparent", colour = "transparent"),
          plot.background = element_rect(fill = "transparent", color = "transparent")) +
    facet_rep_grid(condition_lab~hypermodel, scales = "free",
                   labeller = label_parsed)
```


# -------------------------------------------




