---
title: "Preprocess IGT & SIGT"
output: html_document
---


# --------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(here)
```


## Import Raw Data
```{r}
raw_IGT_AB = as.data.frame(read_excel(here("1_SIGT_PP", "Data", "0_Raw", "IGT_AB_Merged.xlsx"))) %>% 
  filter(Subject != 7156, # 7156 completed IGT version 2 & SIGT on the same day, but then 
                            # has data for IGT version 1 a week later, so I am deleting
                            # task data for sub 7156 from the IGT_AB dataframe (IGT version 1) 
         Subject != 7034) # 7034 played IGT version 2 at 7:39pm & IGT version 1 at 8:20pm,
                            # so I am removing their IGT version 1 data
raw_IGT_BD = as.data.frame(read_excel(here("1_SIGT_PP", "Data", "0_Raw", "IGT_BD_Merged.xlsx"))) %>% 
  filter(Subject != 7081) # Something is wrong with this datafile - incomplete and always played


raw_SIGT_AB = as.data.frame(read_excel(here("1_SIGT_PP", "Data", "0_Raw", "SIGT_AB_Merge_all.xlsx")))
raw_SIGT_BD = as.data.frame(read_excel(here("1_SIGT_PP", "Data", "0_Raw", "SIGT_BD_Merged_all.xlsx")))
```


# --------------------------------------
# Process Data
## Prep IGT Data
```{r}
IGT_data = bind_rows(raw_IGT_AB, raw_IGT_BD) %>% 
  filter(Procedure != "Knowledge") %>%  # remove knowledge checks
  select(ID = Subject, version = ExperimentName, date = SessionDate, 
         trial = Block, cardname, outcome = absmoney1, choice = card.RESP) %>% 
  mutate(task = "monetary",
         version = case_when(str_detect(version, "Version 1") ~ "AB", T ~ "BD"),
         trial = case_when(trial <= 40 ~ trial,
                           trial <= 80 ~ trial - 1,
                           T ~ trial - 2),
         card = case_when(version == "AB" & cardname == "A" ~ 1,
                          version == "AB" & cardname == "B" ~ 2,
                          version == "AB" & cardname == "C" ~ 3,
                          version == "AB" & cardname == "D" ~ 4,
                          version == "BD" & cardname == "A" ~ 3,
                          version == "BD" & cardname == "B" ~ 1,
                          version == "BD" & cardname == "C" ~ 4,
                          version == "BD" & cardname == "D" ~ 2),
         # these are all the same so that the same data-making function can be used
         outcome1 = case_when(is.na(outcome) ~ 0, T ~ outcome / 100),
         outcome2 = case_when(is.na(outcome) ~ 0, T ~ outcome / 100),
         outcome3 = case_when(is.na(outcome) ~ 0, T ~ outcome / 100),
         sign1 = case_when(is.na(outcome) ~ 0, T ~ sign(outcome)),
         sign2 = case_when(is.na(outcome) ~ 0, T ~ sign(outcome)),
         sign3 = case_when(is.na(outcome) ~ 0, T ~ sign(outcome)),
         choice = case_when(choice == 1 ~ 1, # plays
                            T ~ 2))          # passes (including skipped trials)
```


## Prep SIGT Data
```{r}
SIGT_data = bind_rows(raw_SIGT_AB, raw_SIGT_BD) %>% 
  filter(Procedure != "Knowledge") %>%  # remove knowledge checks
  select(ID = Subject, version = ExperimentName, date = SessionDate, 
         trial = Block, cardname, outcome = SocReward1, winlose = winlose1, choice = card.RESP) %>% 
  mutate(task = "social",
         version = case_when(str_detect(version, "Version 1") ~ "AB", T ~ "BD"),
         trial = case_when(trial <= 40 ~ trial,
                           trial <= 80 ~ trial - 1,
                           T ~ trial - 2),
         card = case_when(version == "AB" & cardname == "A" ~ 1,
                          version == "AB" & cardname == "B" ~ 2,
                          version == "AB" & cardname == "C" ~ 3,
                          version == "AB" & cardname == "D" ~ 4,
                          version == "BD" & cardname == "A" ~ 3,
                          version == "BD" & cardname == "B" ~ 1,
                          version == "BD" & cardname == "C" ~ 4,
                          version == "BD" & cardname == "D" ~ 2),
         choice = case_when(choice == 1 ~ 1, # plays
                            T ~ 2),          # passes (including skipped trials)
         # extract % +(happy)/-(angry) face
         outcome = (as.numeric(substr(outcome, 10, 12))),
         outcome = case_when(is.na(outcome) ~ 0, T ~ outcome / 100),
         
         # OPTION 1 - neutral face outcome = 25% & neutral face sign = 0
         #          - pass is the only true 0 (i.e., no outcome)
         outcome1 = outcome,
         sign1 = case_when(is.na(winlose) ~ 0, 
                          winlose == "You lose" ~ -1,
                          winlose == "You win" ~ +1,
                          winlose == "No change" ~ 0),
         
         # OPTION 2 - neutral face outcome = 0% & neutral face sign = 0
         #          - pass is the only true 0 (i.e., no outcome)
         outcome2 = outcome - .25,
         sign2 = case_when(is.na(winlose) ~ 0, 
                          winlose == "You lose" ~ -1,
                          winlose == "You win" ~ +1,
                          winlose == "No change" ~ 0),
         
         # OPTION 3 - neutral face outcome = 25% BUT neutral face sign = +1
         #          - pass is the only true 0 (i.e., no outcome)
         outcome3 = outcome,
         sign3 = case_when(is.na(winlose) ~ 0, 
                          winlose == "You lose" ~ -1,
                          winlose == "You win" ~ +1,
                          winlose == "No change" ~ +1))
```


## Check Data
```{r}
#------------------------------------------------------------
# CHECK HOW MANY TASKS EACH PARTICIPANT COMPLETED
bind_rows(IGT_data, SIGT_data) %>% 
  group_by(ID, task) %>% reframe(fix = 1) %>% 
  pivot_wider(names_from = "task", values_from = "fix",
              values_fill = 0) %>% 
  mutate(both = case_when(social + monetary == 2 ~ 1, T ~ 0)) %>%
  ungroup() %>% 
  reframe(monetary = sum(monetary), social = sum(social), both = sum(both))


#------------------------------------------------------------
# CHECK HOW MANY TRIALS EACH PARTICIPANT HAD
bind_rows(IGT_data, SIGT_data) %>% 
  group_by(ID, task) %>% reframe(n_trials = n()) %>% 
  group_by(task, n_trials) %>% 
  reframe(n = n())
```


## Function for Creating Data
```{r, eval = T}
create_data = function(data){

  IDs = unique(data$ID)
  N = length(IDs)
  T = max(data$trial)
  tasks = unique(data$task)
  S = length(tasks)
  Tsubj = array(data = 0, dim = c(N, S))
  
  card = choice = array(data = -1, dim = c(N, T, S))
  outcome1 = outcome2 = outcome3 = array(data = -1, dim = c(N, T, S))
  sign1 = sign2 = sign3 = array(data = -1, dim = c(N, T, S))
    
  
  for(i in 1:N){
    for(s in 1:S){
      cur_data = filter(data, ID == IDs[i] & task == tasks[s]) %>% 
        arrange(trial)
      if(nrow(cur_data) == 120){
        card[i,,s] = cur_data$card
        Tsubj[i,s] = length(cur_data$trial)
        choice[i,,s] = cur_data$choice
        outcome1[i,,s] = cur_data$outcome1
        outcome2[i,,s] = cur_data$outcome2
        outcome3[i,,s] = cur_data$outcome3
        sign1[i,,s] = cur_data$sign1
        sign2[i,,s] = cur_data$sign2
        sign3[i,,s] = cur_data$sign3
      }
    }
  }
  
  list(IDs = IDs,
       N = N,
       T = T,
       S = S,
       card = card,
       Tsubj = Tsubj,
       choice = choice,
       outcome1 = outcome1,
       outcome2 = outcome2,
       outcome3 = outcome3,
       sign1 = sign1,
       sign2 = sign2,
       sign3 = sign3) %>% 
    return()
}
```


## Create Data
```{r}
IGT_only = create_data(IGT_data)
SIGT_only = create_data(SIGT_data)
IGT_SIGT = create_data(bind_rows(IGT_data, SIGT_data))
```


## Save Data
```{r, eval = T}
saveRDS(IGT_only, here("1_SIGT_PP", "Data", "1_Preprocessed",
                       "IGT_only.RDS"))
saveRDS(SIGT_only, here("1_SIGT_PP", "Data", "1_Preprocessed",
                        "SIGT_only.RDS"))
saveRDS(IGT_SIGT, here("1_SIGT_PP", "Data", "1_Preprocessed",
                       "IGT_SIGT.RDS"))
```







