---
title: "IGT Preprocessing"
output: html_document
author: "Jeremy Haynes"
---



# --------------------------------------
# Setup
## Load Packages
```{r}
library(tidyverse)
library(here)
library(haven)
library(lubridate)
library(readxl)
```



# --------------------------------------
# Questionnaire Data
## Import Data
```{r}
raw_questionnaire_data = read_sav(here("1_SIGT_PP", "Data", "0_Raw",
                                       "FINAL Questionnaire Data- Summary Scales Only - 9.11.18.sav")) %>% 
  filter(Subject != 7156, # 7156 completed IGT version 2 & SIGT on the same day, but then 
                            # has data for IGT version 1 a week later, so I am deleting
                            # task data for sub 7156 from the IGT_AB dataframe (IGT version 1) 
         Subject != 7034, # 7034 played IGT version 2 at 7:39pm & IGT version 1 at 8:20pm,
                            # so I am removing their IGT version 1 data
         Subject != 7081) # Something is wrong with this datafile - incomplete and always
```



## Prep Data
```{r}
questionnaire_data = raw_questionnaire_data %>% 
  select(ID = Subject, sex, ethnicity = Ethnicity,
         bastot = bastot0, basdrive = basdriv0, basfunsk = basfuns0,
         basrewres = basrewr0, bis = bis0,
         panas_pa = panasPA, panas_na = panasNA,
         masqGDA = masqGDA, masqAA = masqAA, masqGDD = masqGDD,
         masqAD = masqAD, shaps_tot = shaps_tot, prdep_tot = prmd_tot
         ) %>% 
  mutate(sex = case_when(sex == 1 ~ "male", sex == 2 ~ "female"))
```



# --------------------------------------
# IGT Data
## Import Data
```{r}
raw_AB = read_excel(here("1_SIGT_PP", "Data", "0_Raw", "IGT_AB_Merged.xlsx")) %>% 
  filter(Subject != 7156, # 7156 completed IGT version 2 & SIGT on the same day, but then 
                            # has data for IGT version 1 a week later, so I am deleting
                            # task data for sub 7156 from the IGT_AB dataframe (IGT version 1) 
         Subject != 7034) # 7034 played IGT version 2 at 7:39pm & IGT version 1 at 8:20pm,
                            # so I am removing their IGT version 1 data
raw_BD = read_excel(here("1_SIGT_PP", "Data", "0_Raw", "IGT_BD_Merged.xlsx")) %>% 
  filter(Subject != 7081) # Something is wrong with this datafile - incomplete and always played
```



## Prep Data
```{r}
IGT_data = bind_rows(raw_AB, raw_BD) %>% 
  filter(Procedure != "Knowledge") %>%  # remove knowledge checks
  select(ID = Subject, version = ExperimentName, date = SessionDate, 
         trial = Block, cardname, outcome = absmoney1, choice = card.RESP) %>% 
  mutate(version = case_when(str_detect(version, "Version 1") ~ "AB", T ~ "BD"),
         trial = case_when(trial <= 40 ~ trial,
                           trial <= 80 ~ trial - 1,
                           T ~ trial - 2),
         card = case_when(version == "AB" & cardname == "A" ~ 1, version == "AB" & cardname == "B" ~ 2,
                          version == "AB" & cardname == "C" ~ 3, version == "AB" & cardname == "D" ~ 4,
                          version == "BD" & cardname == "A" ~ 3, version == "BD" & cardname == "B" ~ 1,
                          version == "BD" & cardname == "C" ~ 4, version == "BD" & cardname == "D" ~ 2),
         outcome = case_when(is.na(outcome) ~ 0, T ~ outcome / 100),
         sign = case_when(is.na(outcome) ~ 0, T ~ sign(outcome)),
         choice = case_when(choice == 1 ~ 1, # plays
                            T ~ 2))          # passes (including skipped trials)
```



# --------------------------------------
# Stan Data
## Join Data
```{r}
combined_data = inner_join(questionnaire_data, IGT_data) %>% 
  select(ID, bastot, basdrive, basfunsk, basrewres, bis,
         panas_pa, panas_na, masqGDA, masqAA, masqGDD,
         masqAD, shaps_tot, prdep_tot, trial, card, outcome, sign, choice)
# 7 participants do not have complete data after filtering others out above:
  # No IGT data: 7047 7108, 7165
  # No questionnaire data: 4074, 7034, 7136, 7156")
```



## Create IGT Stan Data
```{r, eval = T}
create_data = function(data){

  IDs = unique(data$ID)
  N = length(IDs)
  T = max(data$trial)
  
  card = matrix(data = -1, nrow = N, ncol = T)
  Tsubj = vector(length = N)
  choice = matrix(data = -1, nrow = N, ncol = T)
  outcome = matrix(data = -1, nrow = N, ncol = T)
  sign = matrix(data = -1, nrow = N, ncol = T)
  bastot = vector(length = N)
  basdrive = vector(length = N) 
  basfunsk = vector(length = N) 
  basrewres = vector(length = N)
  bis = vector(length = N)
  panas_pa = vector(length = N) 
  panas_na = vector(length = N) 
  masqGDA = vector(length = N) 
  masqAA = vector(length = N) 
  masqGDD = vector(length = N)
  masqAD = vector(length = N) 
  shaps_tot = vector(length = N) 
  prdep_tot = vector(length = N)
  
  for(i in 1:N){
    card[i,] = data$card[data$ID == IDs[i]]
    Tsubj[i] = length(data$trial[data$ID == IDs[i]])
    choice[i,] = data$choice[data$ID == IDs[i]]
    outcome[i,] = data$outcome[data$ID == IDs[i]]
    sign[i,] = data$sign[data$ID == IDs[i]]
    bastot[i] = data$bastot[data$ID == IDs[i]]
    basdrive[i] = data$basdrive[data$ID == IDs[i]]
    basfunsk[i] = data$basfunsk[data$ID == IDs[i]]
    basrewres[i] = data$basrewres[data$ID == IDs[i]]
    bis[i] = data$bis[data$ID == IDs[i]]
    panas_pa[i] = data$panas_pa[data$ID == IDs[i]]
    panas_na[i] = data$panas_na[data$ID == IDs[i]]
    masqGDA[i] = data$masqGDA[data$ID == IDs[i]]
    masqAA[i] = data$masqAA[data$ID == IDs[i]]
    masqGDD[i] = data$masqGDD[data$ID == IDs[i]]
    masqAD[i] = data$masqAD[data$ID == IDs[i]]
    shaps_tot[i] = data$shaps_tot[data$ID == IDs[i]]
    prdep_tot[i] = data$prdep_tot[data$ID == IDs[i]]
  }
  
  stan_data = list(IDs = IDs,
                   N = N,
                   T = T,
                   card = card,
                   Tsubj = Tsubj,
                   choice = choice,
                   outcome = outcome,
                   sign = sign,
                   bastot = bastot,
                   basdrive = basdrive, 
                   basfunsk = basfunsk, 
                   basrewres = basrewres,
                   bis = bis,
                   panas_pa = panas_pa, 
                   panas_na = panas_na, 
                   masqGDA = masqGDA, 
                   masqAA = masqAA, 
                   masqGDD = masqGDD,
                   masqAD = masqAD, 
                   shaps_tot = shaps_tot, 
                   prdep_tot = prdep_tot)
}
```



## Save Data
```{r, eval = T}
orl_stan_data = create_data(combined_data)

saveRDS(orl_stan_data, here("1_SIGT_PP", "Data", "1_Preprocessed",
                            "IGT_SR_stan_data.RDS"))
```



# --------------------------------------
# Correlations
```{r}
library(wBoot)
#------------------------------------------------------------------------------
# RUN AND CLEAN UP CORRELATIONS
run_cor = function(cur_data, cor_type, x_nam, y_nam){
  cor = boot.cor.bca(
    x = cur_data[[x_nam]], y = cur_data[[y_nam]],
    alternative = c("two.sided", "less", "greater"),
    null.hyp = NULL, conf.level = 0.95, type = NULL, R = 9999)
  return(data.frame(
    cor_type = cor_type,
    x = x_nam, y = y_nam,
    r = cor$Observed,
    CI = cor$Confidence.interval))
}
```


```{r}
SR_orl = data.frame(ID = orl_stan_data$subjIDs,
                    Arew = apply(orl_posteriors$Arew, 2, mean),
                    Apun = apply(orl_posteriors$Apun, 2, mean),
                    betaF = apply(orl_posteriors$betaF, 2, mean),
                    betaP = apply(orl_posteriors$betaP, 2, mean),
                    K = apply(orl_posteriors$K, 2, mean),
                    bastot = orl_stan_data$bastot,
                    basdrive = orl_stan_data$basdrive, 
                    basfunsk = orl_stan_data$basfunsk, 
                    basrewres = orl_stan_data$basrewres,
                    bis = orl_stan_data$bis,
                    panas_pa = orl_stan_data$panas_pa, 
                    panas_na = orl_stan_data$panas_na, 
                    masqGDA = orl_stan_data$masqGDA, 
                    masqAA = orl_stan_data$masqAA, 
                    masqGDD = orl_stan_data$masqGDD,
                    masqAD = orl_stan_data$masqAD, 
                    shaps_tot = orl_stan_data$shaps_tot, 
                    prdep_tot = orl_stan_data$prdep_tot) %>% 
  mutate(ratio = Apun/Arew)

```



```{r}
for(scale in c("bastot", "basdrive", "basfunsk", "basrewres", "bis", 
               "shaps_tot", "prdep_tot", "panas_pa", "panas_na", 
               "masqGDA", "masqAA", "masqGDD", "masqAD")){
  for(parameter in c("Arew", "Apun", "betaF", "betaP", "K")){
    cur_data = SR_orl %>% 
      select(ID, all_of(scale), all_of(parameter)) %>% 
      na.omit()
    
    if(nrow(cur_data)!=0){
      SR_ORL_correlations = run_cor(cur_data, "SR-ORL", scale, parameter) %>% 
        bind_rows(SR_ORL_correlations)
    }
  }
}
```



















