---
title: "Fitting ORL w/Updated Fictive Learning"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(wBoot)
library(cmdstanr)
library(grid)
library('devtools')
source_url("https://raw.githubusercontent.com/MatthewBJane/theme_barbie/main/theme_barbie.R")
source(here("1_SIGT_PP", "Code", "R", "3_Other", "helpful_functions.R"))
```



## Load Data
```{r}
stan_data = readRDS(here("1_SIGT_PP", "Data", "1_Preprocessed", "IGT_pre.rds"))
```



# -------------------------------------------
# Check Model
```{r, eval = F}
model_code = cmdstan_model(here("1_SIGT_PP", "Code", "Stan", 
                                "igt_orl_playfic.stan"), compile = F)

model_code$check_syntax(quiet = T)
```



# Fit Model
```{r, eval = F}
# Compile model
orl_model = stan_model(here("1_SIGT_PP", "Code", "Stan", "igt_orl_playfic.stan"))


# Fit model
orl_fit = sampling(orl_model, 
                   data   = stan_data, 
                   iter   = 5000, 
                   warmup = 1000, 
                   chains = 4, 
                   cores  = 4,
                   seed   = 43210)


#save the fitted model as an .rds file
saveRDS(orl_fit, here("1_SIGT_PP", "Data", "2_Fitted", "ORL_playfic",
                      "orl_pp_playfic_fit.rds"))
```



```{r}
orl_fit = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", "ORL_playfic",
                       "orl_pp_playfic_fit.rds"))

iterations = orl_fit@sim$chains * (orl_fit@sim$iter - orl_fit@sim$warmup)
```



# -------------------------------------------
# Model Diagnostics
```{r}
# orl_posteriors <- extract(orl_fit)
# saveRDS(orl_posteriors, here("1_SIGT_PP", "Data", "2_Fitted", "ORL_playfic",
#                              "orl_pp_playfic_posteriors.rds"))
orl_posteriors = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", "ORL_playfic",
                              "orl_pp_playfic_posteriors.rds"))


focal_parameters <- c(
  "mu_Arew", "mu_Apun", "mu_K", "mu_betaF", "mu_betaP", 
  "sigma_Arew", "sigma_Apun", "sigma_K", "sigma_betaF", "sigma_betaP", 
  "Arew", "Apun", "K", "betaF", "betaP"
)

group_parameters <- grep("mu|sigma", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma", focal_parameters, value=TRUE, invert=TRUE)
```



## Rhat
```{r, eval = F}
# rhats = rhat(orl_fit, pars = focal_parameters) %>%
#   data.frame() %>% mutate(parameter = rownames(.))
saveRDS(rhats, here("1_SIGT_PP", "Data", "2_Fitted", "ORL_playfic",
                    "orl_pp_playfic_rhats.rds"))
rhats = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", "ORL_playfic",
                     "orl_pp_playfic_rhats.rds"))
```



## Traceplots
```{r, eval = F}
tiff(here("1_SIGT_PP", "Figs_Tables", "ORL_playfic",
          "orl_pp_playfic_group_traceplots.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  traceplot(
    orl_fit,
    pars = group_parameters
)
dev.off()


for(i in person_parameters){
  tiff(here("1_SIGT_PP", "Figs_Tables", "ORL_playfic",
            paste("orl_pp_playfic_", i, "_traceplots.tiff", sep = "")),
       width = 35, height = 25, units = "cm", res = 300)
    traceplot(orl_fit,
              pars = i
              ) %>% print()
    dev.off()
}
```



## Pairs
```{r, eval = F}
tiff(here("1_SIGT_PP", "Figs_Tables", "ORL_playfic",
          "orl_pp_playfic_group_pairs.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  pairs(
    orl_fit,
    pars = group_parameters
)
dev.off()
```



# -------------------------------------------
# Inspect Parameters
## Means +/- PI
```{r, eval = F}
tiff(here("1_SIGT_PP", "Figs_Tables", "ORL_playfic",
          "orl_pp_playfic_posterior_means.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  plot(orl_fit, pars = group_parameters)
dev.off()
```



## Posterior Distributions
```{r, eval = F}
tiff(here("1_SIGT_PP", "Figs_Tables", "ORL_playfic",
          "orl_pp_playfic_posterior_distributions.tiff"),
     width = 30, height = 20, units = "cm", res = 300)
  par(mfrow = c(5, 5))
  # Mus & Sigmas
  for(i in grep("mu|sigma", group_parameters, value = T)){
    plot(density(orl_posteriors[[i]]), main = i)
    abline(v = mean(orl_posteriors[[i]]))
  }
dev.off()
```



# -------------------------------------------
# Results
## PPCs
```{r}
PPCs = make_PPCs(orl_fit, stan_data)

tiff(here("1_SIGT_PP", "Figs_Tables", "ORL_playfic", "PPC.tiff"),
     width = 15, height = 7.5, units = "cm", res = 300)

  grid.newpage()
  pushViewport(viewport(x = .5, y = .5, width = .9, height = .9))
  grid.draw(PPCs)
  popViewport()
  
  
  # x axis
  grid.text("Trial",
            x = .52, y = .05,
            gp = gpar(fontsize = 14))
  # y axis
  grid.text("Proportion Play",
            x = .0225, y = .5,
            gp = gpar(fontsize = 14),
            rot = 90)
dev.off()
```




# -------------------------------------------



















