---
title: "Fitting ORL"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
library(loo)
```



## Load Data
```{r}
IGT = readRDS(here("1_SIGT_PP", "Data", "1_Preprocessed", "IGT_only.RDS"))
SIGT = readRDS(here("1_SIGT_PP", "Data", "1_Preprocessed", "SIGT_only.RDS"))
IGT_SIGT = readRDS(here("1_SIGT_PP", "Data", "1_Preprocessed", "IGT_SIGT.RDS"))
```


# Compile model
```{r}
ORL_model = cmdstan_model(here("1_SIGT_PP", "Code", "Stan", "Joint_ORL.stan"))
```


# -------------------------------------------
# Fit Models
## IGT
```{r, eval = F}
IGT$outcome = IGT$outcome1
IGT$sign = IGT$sign1
IGT_fit = ORL_model$sample(data = IGT,
                           chains = 4,
                           parallel_chains = 4,
                           iter_warmup = 1000,
                           iter_sampling = 1000,
                           seed = 43210)
IGT_fit$save_object(file = here("1_SIGT_PP", "Data", "2_Fitted", "IGT_fit.RDS"))
```


## SIGT
### Outcome 1
```{r, eval = F}
SIGT$outcome = SIGT$outcome1
SIGT$sign = SIGT$sign1
SIGT1_fit = ORL_model$sample(data = SIGT,
                             chains = 4,
                             parallel_chains = 4,
                             iter_warmup = 1000,
                             iter_sampling = 1000,
                             seed = 43210)
SIGT1_fit$save_object(file = here("1_SIGT_PP", "Data", "2_Fitted", "SIGT1_fit.RDS"))
```


### Outcome 2
```{r, eval = F}
SIGT$outcome = SIGT$outcome2
SIGT$sign = SIGT$sign2
SIGT2_fit = ORL_model$sample(data = SIGT,
                             chains = 4,
                             parallel_chains = 4,
                             iter_warmup = 1000,
                             iter_sampling = 1000,
                             seed = 43210)
SIGT2_fit$save_object(file = here("1_SIGT_PP", "Data", "2_Fitted", "SIGT2_fit.RDS"))
```


### Outcome 3
```{r, eval = F}
SIGT$outcome = SIGT$outcome3
SIGT$sign = SIGT$sign3
SIGT3_fit = ORL_model$sample(data = SIGT,
                             chains = 4,
                             parallel_chains = 4,
                             iter_warmup = 1000,
                             iter_sampling = 1000,
                             seed = 43210)
SIGT3_fit$save_object(file = here("1_SIGT_PP", "Data", "2_Fitted", "SIGT3_fit.RDS"))
```


### Compare SIGT Models
```{r, eval = F}
loo_compare(list("SIGT 1" = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", "SIGT1_fit.RDS"))$loo(), 
                 "SIGT 2" = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", "SIGT2_fit.RDS"))$loo(),
                 "SIGT 3" = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", "SIGT3_fit.RDS"))$loo()))
```


## IGT-SIGT
```{r, eval = F}
IGT_SIGT$outcome = IGT_SIGT$outcome2
IGT_SIGT$sign = IGT_SIGT$sign2
IGT_SIGT_fit = ORL_model$sample(data = IGT_SIGT,
                                chains = 1,
                                parallel_chains = 4,
                                iter_warmup = 200,
                                iter_sampling = 200,
                                seed = 43210)
IGT_SIGT_fit$save_object(file = here("1_SIGT_PP", "Data", "2_Fitted", "IGT_SIGT_fit.RDS"))
```


## Import Models
```{r, eval = F}
IGT_fit      = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", "IGT_fit.RDS"))
SIGT2_fit    = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", "SIGT2_fit.RDS"))
IGT_SIGT_fit = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", "IGT_SIGT_fit.RDS"))
```


# -------------------------------------------
# Model Diagnostics
## IGT-SIGT
```{r, eval = F}
focal_parameters = c("lp__", "mu_p",
                     "mu_Arew", "mu_Apun", "mu_betaF", "mu_betaB",
                     "sigma_Arew", "sigma_Apun", "sigma_betaF", "sigma_betaB",
                     "R_Arew", "R_Apun", "R_betaF", "R_betaB",
                     "Arew", "Apun", "betaF", "betaB")

mcmc_trace(IGT_SIGT_fit$draws(grep("lp__|mu|sigma|R", focal_parameters, value=TRUE)))
mcmc_pairs(IGT_SIGT_fit$draws(grep("lp__|mu|sigma|R", focal_parameters, value=TRUE)),
           size = 1)
mcmc_rhat_hist(summarise_draws(IGT_SIGT_fit$draws(focal_parameters), "rhat")$rhat)
```



```{r}
orl_posteriors = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", 
                              "ORL", "ORL_posteriors.rds"))

focal_parameters <- c(
  "mu_Arew", "mu_Apun", "mu_K", "mu_betaF", "mu_betaP", 
  "sigma_Arew", "sigma_Apun", "sigma_K", "sigma_betaF", "sigma_betaP", 
  "Arew", "Apun", "K", "betaF", "betaP"
)

group_parameters <- grep("mu|sigma", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma", focal_parameters, value=TRUE, invert=TRUE)
```



## Rhat
```{r, eval = F}
rhats = rhat(orl_fit, pars = focal_parameters) %>%
  data.frame() %>% mutate(parameter = rownames(.))
saveRDS(rhats, here("1_SIGT_PP", "Data", "2_Fitted", 
                    "ORL", "ORL_rhats.rds"))
```



```{r, eval = T}
rhats = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", 
                     "ORL", "ORL_rhats.rds"))
```



## Traceplots
```{r, eval = F}
tiff(here("1_SIGT_PP", "Figs_Tables", 
          "ORL", "ORL_group_traceplots.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  traceplot(
    orl_fit,
    pars = group_parameters
)
dev.off()


for(i in person_parameters){
  tiff(here("1_SIGT_PP", "Figs_Tables", 
            "ORL", "ORL_", i, "_traceplots.tiff", sep = ""),
       width = 50, height = 50, units = "cm", res = 300)
    traceplot(orl_fit,
              pars = i
              ) %>% print()
    dev.off()
}
```



# -------------------------------------------
# Inspect Parameters
## Means +/- PI
```{r, eval = F}
tiff(here("1_SIGT_PP", "Figs_Tables", 
          "ORL", "ORL_posterior_means.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  plot(orl_fit, pars = group_parameters)
dev.off()
```



## Posterior Distributions
```{r, eval = F}
tiff(here("1_SIGT_PP", "Figs_Tables", 
          "ORL", "ORL_posterior_distributions.tiff"),
     width = 30, height = 20, units = "cm", res = 300)
  par(mfrow = c(5, 5))
  # Mus & Sigmas
  for(i in grep("mu|sigma", group_parameters, value = T)){
    plot(density(orl_posteriors[[i]]), main = i)
    abline(v = mean(orl_posteriors[[i]]))
  }
dev.off()
```



# -------------------------------------------
# Correlations with Self-Report
## Correlation Function
```{r}
run_cor = function(cur_data, cor_type, x_nam, y_nam){
  cor = boot.cor.bca(
    x = cur_data[[x_nam]], y = cur_data[[y_nam]],
    alternative = c("two.sided", "less", "greater"),
    null.hyp = NULL, conf.level = 0.95, type = NULL, R = 9999)
  return(data.frame(
    cor_type = cor_type,
    x = x_nam, y = y_nam,
    r = cor$Observed,
    CI = cor$Confidence.interval))
}
```



## Prep Data
```{r}
orl_sr = data.frame(ID = stan_data$IDs,
                    Arew = apply(orl_posteriors$Arew, 2, mean),
                    Apun = apply(orl_posteriors$Apun, 2, mean),
                    betaF = apply(orl_posteriors$betaF, 2, mean),
                    betaP = apply(orl_posteriors$betaP, 2, mean),
                    K = apply(orl_posteriors$K, 2, mean),
                    bastot = stan_data$bastot,
                    basdrive = stan_data$basdrive,
                    basfunsk = stan_data$basfunsk,
                    basrewres = stan_data$basrewres,
                    bis = stan_data$bis,
                    panas_pa = stan_data$panas_pa,
                    panas_na = stan_data$panas_na,
                    masqGDA = stan_data$masqGDA,
                    masqAA = stan_data$masqAA,
                    masqGDD = stan_data$masqGDD,
                    masqAD = stan_data$masqAD,
                    shaps_tot = stan_data$shaps_tot,
                    prdep_tot = stan_data$prdep_tot)
```



## Calculate Correlations
```{r}
correlations = data.frame()

for(parameter in c("Arew", "Apun", "betaF", "betaP", "K")){
  for(scale in c("bastot", "basdrive", "basfunsk", "basrewres", "bis",
                 "panas_pa", "panas_na", "masqGDA", "masqAA", "masqGDD",
                 "masqAD", "shaps_tot", "prdep_tot")){
    cur_data = orl_sr %>% 
        select(ID, all_of(parameter), all_of(scale)) %>% 
        na.omit()
    
    correlations = run_cor(cur_data, "ORL-SR", parameter, scale) %>% 
      bind_rows(correlations)
  }
}

orl_sr_correlations = correlations %>% 
  separate(col = "CI", into = c("lower", "upper"), sep = ",") %>% 
  mutate(lower = as.numeric(str_remove(lower, "\\(")),
         upper = as.numeric(str_remove(upper, "\\)")),
         sig = case_when(lower < 0 & upper < 0 ~ "*",
                         lower > 0 & upper > 0 ~ "*",
                         lower < 0 & upper < .01 ~ "#",
                         lower > .01 & upper > 0 ~ "#",
                         T ~ ""))
```




















