---
title: "Fitting ORL"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(wBoot)
library(cmdstanr)
library(lemon)
source(here("1_SIGT_PP", "Code", "R", "3_Other", "helpful_functions.R"))
```



## Load Data
```{r}
stan_data = readRDS(here("1_SIGT_PP", "Data", "1_Preprocessed", "IGT_stan_data.rds"))
```



## Specify Model Name
```{r}
model_name = "orl_pp"
```



# -------------------------------------------
# Check Model
```{r, eval = T}
model_code = cmdstan_model(here("1_SIGT_PP", "Code", "Stan", 
                                paste0("igt_", model_name, ".stan")), compile = F)

model_code$check_syntax(quiet = T)
```



# Fit Model
```{r, eval = T}
# Compile model
orl_model = stan_model(here("1_SIGT_PP", "Code", "Stan",
                            paste0("igt_", model_name, ".stan")))


# Fit model
orl_fit = sampling(orl_model, 
                   data   = stan_data, 
                   iter   = 5000, 
                   warmup = 1000, 
                   chains = 4,
                   cores  = 4,
                   seed   = 43210)


#save the fitted model as an .rds file
saveRDS(orl_fit, here("1_SIGT_PP", "Data", "2_Fitted", model_name,
                      paste0(model_name, "_fit.rds")))
```



```{r}
orl_fit = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", model_name,
                      paste0(model_name, "_fit.rds")))

iterations = orl_fit@sim$chains * (orl_fit@sim$iter - orl_fit@sim$warmup)
```



# -------------------------------------------
# Model Diagnostics
```{r, eval = T}
orl_posteriors <- extract(orl_fit)
saveRDS(orl_posteriors, here("1_SIGT_PP", "Data", "2_Fitted", model_name,
                             paste0(model_name, "_posteriors.rds")))
```



```{r}
orl_posteriors = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", model_name,
                              paste0(model_name, "_posteriors.rds")))


focal_parameters <- c(
  "mu_Arew", "mu_Apun", "mu_K", "mu_betaF", "mu_betaP", 
  "sigma_Arew", "sigma_Apun", "sigma_K", "sigma_betaF", "sigma_betaP", 
  "Arew", "Apun", "K", "betaF", "betaP"
)

group_parameters <- grep("mu|sigma", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma", focal_parameters, value=TRUE, invert=TRUE)
```



## Rhat
```{r, eval = T}
rhats = rhat(orl_fit, pars = focal_parameters) %>%
  data.frame() %>% mutate(parameter = rownames(.))
saveRDS(rhats, here("1_SIGT_PP", "Data", "2_Fitted", model_name,
                              paste0(model_name, "_rhats.rds")))
```



```{r}
rhats = readRDS(here("1_SIGT_PP", "Data", "2_Fitted", model_name,
                     paste0(model_name, "_rhats.rds")))
```



## Traceplots
```{r}
tiff(here("1_SIGT_PP", "Figs_Tables", model_name,
          paste0(model_name, "_group_traceplots.tiff")),
     width = 35, height = 25, units = "cm", res = 300)
  traceplot(
    orl_fit,
    pars = group_parameters
)
dev.off()


for(i in person_parameters){
  tiff(here("1_SIGT_PP", "Figs_Tables", model_name,
          paste0(model_name, "_", i, "_traceplots.tiff")),
       width = 35, height = 25, units = "cm", res = 300)
    traceplot(orl_fit,
              pars = i
              ) %>% print()
    dev.off()
}
```



# -------------------------------------------
# Results
## Parameter Means +/- CI
```{r}
tiff(here("1_SIGT_PP", "Figs_Tables", model_name,
          paste0(model_name, "_posterior_means.tiff")),
     width = 35, height = 25, units = "cm", res = 300)
  plot(orl_fit, pars = group_parameters)
dev.off()
```



## Parameter Posterior Distributions
```{r}
tiff(here("1_SIGT_PP", "Figs_Tables", model_name,
          paste0(model_name, "_posterior_distributions.tiff")),
     width = 30, height = 20, units = "cm", res = 300)
  par(mfrow = c(5, 5))
  # Mus & Sigmas
  for(i in grep("mu|sigma", group_parameters, value = T)){
    plot(density(orl_posteriors[[i]]), main = i)
    abline(v = mean(orl_posteriors[[i]]))
  }
dev.off()
```



## PPC Plot
```{r}
choice_proportions = calculate_proportions(orl_posteriors, stan_data,
                                           data_type = "data.frame"
                                           # data_type = "list_of_matrices"
                                           )

simplified_data = choice_proportions %>% 
  group_by(trial, deck) %>% 
  summarise(observed = mean(observed), mu = mean(mu),
            lower50 = mean(lower50), upper50 = mean(upper50),
            lower95 = mean(lower95), upper95 = mean(upper95))
```



```{r}
tiff(here("1_SIGT_PP", "Figs_Tables", model_name,
          paste0(model_name, "_PPC.tiff")),
     width = 15, height = 8, units = "cm", res = 300)

  # simplify data
  choice_proportions %>% 
    group_by(trial, deck) %>% 
    summarise(observed = mean(observed), mu = mean(mu),
              lower50 = mean(lower50), upper50 = mean(upper50),
              lower95 = mean(lower95), upper95 = mean(upper95)) %>%
    # plotting
    ggplot(aes(x = trial,
               group = trial)) +
    geom_linerange(aes(ymin = lower95, ymax = upper95),
                   linewidth = .35, color = "goldenrod3", alpha = .5) +
    geom_linerange(aes(ymin = lower50, ymax = upper50),
                   linewidth = .35, color = "goldenrod3") +
    geom_point(aes(y = mu), shape = 21,
               color = "goldenrod3", fill = "white",
               size = .75) +
    geom_point(aes(y = observed), size = .75) +
    scale_y_continuous(limits = c(0,1), expand = c(0,0),
                       breaks = seq(0,1,.25)) +
    labs(x = "Trial", y = "Proportion Play") +
    theme_classic() +
    theme(axis.text = element_text(color = "black"),
          strip.background = element_blank(),
          ) +
    facet_rep_wrap(deck~.,
                   labeller = labeller(deck = c("A" = "Deck A", "B" = "Deck B",
                                                "C" = "Deck C", "D" = "Deck D")))
dev.off()
```






# -------------------------------------------



















