---
title: "Fitting ORL"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
library(grid)
# source(here("Code", "R", "3_Other", "helpful_functions.R"))
```



## RMD Setup
```{r}
model_name = "Covariate_Joint_ORL_Bias"

focal_parameters = c(
  "mu_Arew", "mu_Apun", "mu_betaF", "mu_betaB", 
  "sigma_Arew", "sigma_Apun", "sigma_betaF", "sigma_betaB", 
  "Arew", "Apun", "betaF", "betaB", 
  "beta_Arew", "beta_Apun", "beta_betaF", "beta_betaB", 
  "R_Arew", "R_Apun", "R_betaF", "R_betaB"
)


group_parameters <- grep("mu|sigma|R", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma|R", focal_parameters, value=TRUE, invert=TRUE)
```



# -------------------------------------------
# Check Model
```{r, eval = T}
model_code = cmdstan_model(here("1_TADS_Parents_PP", "Code", "Stan", 
                                paste0(model_name, ".stan")), compile = F)

model_code$check_syntax(quiet = T)
```



# Fit Model
```{r, eval = T}
# Compile model
orl_model = stan_model(here("1_TADS_Parents_PP", "Code", "Stan",
                            paste0(model_name, ".stan")))
  
# for(sample in c("T1_parent", "T2_parent", "T3_parent", "T4_parent", "T5_parent")) {
for(sample in c("T1_parent_Anx_Dep_SUD")) {
  # -----------------------------------------------------------------------------------
  # load data
  stan_data = readRDS(here("1_TADS_Parents_PP", "Data", "1_Stan",
                           paste("design", sample, "IGT.RDS", sep = "_")))
  
  # -----------------------------------------------------------------------------------
  # Fit model
  orl_fit = sampling(orl_model, 
                     data   = stan_data, 
                     iter   = 5000, 
                     warmup = 1000, 
                     chains = 4, 
                     cores  = 4,
                     seed   = 43210,
                     save_warmup = F)
  saveRDS(orl_fit, here("1_TADS_Parents_PP", "Data", "2_Fitted",
                        model_name,
                        paste(sample, model_name, "fit.rds", sep = "_")))
  
  # -----------------------------------------------------------------------------------
  # save posteriors
  saveRDS(extract(orl_fit), here("1_TADS_Parents_PP", "Data", "2_Fitted",
                                 model_name,
                                 paste(sample, model_name, "posteriors.rds", sep = "_")))
  
  # -----------------------------------------------------------------------------------
  # save rhats
  rhat(orl_fit, pars = focal_parameters) %>%
    data.frame() %>% mutate(parameter = rownames(.)) %>% 
    saveRDS(here("1_TADS_Parents_PP", "Data", "2_Fitted",
                 model_name,
                 paste(sample, model_name, "rhats.rds", sep = "_")))
}
```



# -------------------------------------------





















