---
title: "Manuscript Plots"
output: html_document
date: "2023-03-09"
---



# ---------------------------------------
# Setup
## Loading Packages & Data
```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(foreach)
library(tidybayes)
library(patchwork)
library(abind)
library(zoo)
library(here)
library(ggpubr)
library(egg)
library(grid)
library(tidyverse)
library(lemon)
library(ggpp)
library(wBoot)
library(stringi)

fit = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint", "orl_pp_joint_fit.rds"))
stan_data <- readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "stan_ready_ORL_IGT.rds"))
orl_posteriors = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint", 
                              "orl_pp_joint_posteriors.rds"))
```



# ---------------------------------------
# Posterior Predictive Checks
## Prep Data
```{r}
# Card matrix
cards = stan_data$card


# Recode choice data
choices = ifelse(stan_data$choice == 2, 0, ifelse(stan_data$choice == 1, 1, NA))


# Trial matrix (to skip when participant wasn't there)
trials = stan_data$Tsubj


# Extract parameters
predicted_values = ifelse(orl_posteriors$choice_pred == 2, 0, 1)


# For binding together posterior predictions
acomb = function(...) abind(..., along=3)
bcomb = function(...) abind(..., along=4)
```



### Choice Data
```{r}
# Calculates group-level choice proportions into a 30 (trial) x 4 (card) x 2 (session) matrix
choice_proportions = foreach(s = 1:2, .combine = "acomb") %do% {
  foreach(c = 1:4, .combine = "cbind") %do% {
    temp = foreach(i = 1:49, .combine = "rbind") %do% {
        choices[i, cards[i, , s] == c, s]
    } %>% colMeans(na.rm = T)
  }
}
```



### Predicted Values
```{r}
predicted_proportions = foreach(s = 1:2, .combine = "bcomb") %do% {
  foreach(c = 1:4, .combine = "acomb") %do% {
    foreach(i = 1:49, .combine = "acomb") %do% {
      if(trials[i, s] > 0){
        predicted_values[ , i, cards[i, , s] == c, s]
      }
    } %>% 
      apply(., c(1,2), mean)
  }
}
```




## Plot Function
```{r}
make_plot = function(y_data, yrep_data, top, right,
                     x_axis_txt, y_axis_txt, deck){
  if(top){
    custom_margin = margin(t = 1, r = -.5, b = -.5, l = -.5, unit = "lines")
  } else {
    custom_margin = margin(t = -.5, r = -.5, b = 1, l = -.5, unit = "lines")
  }
  if(right == 1 | right == 2){
    session_text = paste("Session", right)
  } else {
    session_text = ""
  }
  
  ppc_intervals(x = 1:length(y_data),
                y = y_data*100,
                yrep = yrep_data*100,
                prob = 0.50, 
                prob_outer = .80) +
    geom_text(aes(x = 30, y = 5, label = session_text),
              color = "black", hjust = 1, vjust = 0, check_overlap = T) +
    scale_x_continuous(expand = c(0, 0), limits = c(0, 31), breaks = seq(0, 30, 5)) +
    scale_y_continuous(expand = c(0, 0), limits = c(0, 100), breaks = seq(0, 100, 25)) +
    theme_classic() +
    labs(x = "Trial", y = "Proportion Played", title = deck) +
    theme(legend.position = "none",
          axis.title = element_blank(),
          axis.text.x = element_text(color = x_axis_txt, size = 12),
          axis.text.y = element_text(color = y_axis_txt, size = 12),
          plot.title = element_text(hjust = .5, size = 12),
          plot.margin = custom_margin,
          plot.background = element_rect(fill = "transparent", colour = "transparent"))
}
```



## Make Plot
```{r}
# Set color scheme for bayesplot (it is a global setting)
color_scheme_set("viridisC")

plots = ggarrange(make_plot(choice_proportions[, 1, 1], predicted_proportions[,, 1, 1],
                            T, 0, "transparent", "black", "Deck A"),
                  make_plot(choice_proportions[, 2, 1], predicted_proportions[,, 2, 1],
                            T, 0, "transparent", "transparent", "Deck B"),
                  make_plot(choice_proportions[, 3, 1], predicted_proportions[,, 3, 1],
                            T, 0, "transparent", "transparent", "Deck C"),
                  make_plot(choice_proportions[, 4, 1], predicted_proportions[,, 4, 1],
                            T, 1, "transparent", "transparent", "Deck D"),
                  
                  make_plot(choice_proportions[, 1, 2], predicted_proportions[,, 1, 2],
                            F, 0, "black", "black", ""),
                  make_plot(choice_proportions[, 2, 2], predicted_proportions[,, 2, 2],
                            F, 0, "black", "transparent", ""),
                  make_plot(choice_proportions[, 3, 2], predicted_proportions[,, 3, 2],
                            F, 0, "black", "transparent", ""),
                  make_plot(choice_proportions[, 4, 2], predicted_proportions[,, 4, 2],
                            F, 2, "black", "transparent", ""),
                  nrow = 2, ncol = 4)
```



## Save Plot
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "Manuscript_Plots", "PPC.tiff"),
     width = 25, height = 10, units = "cm", res = 300)

  grid.newpage()
  pushViewport(viewport(x = .5, y = .5, width = .9, height = .9))
  grid.draw(plots)
  popViewport()
  
  
  # x axis
  grid.text("Trial",
            x = .5125, y = .05,
            gp = gpar(fontsize = 16))
  # y axis
  grid.text("% Played",
            x = .0225, y = .5,
            gp = gpar(fontsize = 16),
            rot = 90)
dev.off()
```



# ---------------------------------------
# Correlations with Behavior
## Calculate Person-Level Choice Proportions
```{r}
card_proportions = array(data = NA, dim = c(49, 4, 2))
good_proportions = matrix(data = NA, nrow = 49, ncol = 2)
bad_proportions = matrix(data = NA, nrow = 49, ncol = 2)
play_proportions = matrix(data = NA, nrow = 49, ncol = 2)

for(i in 1:49){
  for(s in 1:2){
    good_proportions[i,s] = mean(choices[i,,s][stan_data$card[i,,s] == 3 | stan_data$card[i,,s] == 4], na.rm = T)
    bad_proportions[i,s] = mean(choices[i,,s][stan_data$card[i,,s] == 1 | stan_data$card[i,,s] == 2], na.rm = T)
    play_proportions[i,s] = mean(choices[i,,s] == 1, na.rm = T)
    for(c in 1:4){
      card_proportions[i,c,s] = mean(choices[i,,s][stan_data$card[i,,s] == c], na.rm = T)
    }
  }
}
dimnames(card_proportions) = list(c(1:49), c(1:4), c(1:2))
```



## Calculate Person-Level Estimates
```{r}
orl_posterior_means = list()

for(parameter in c("Arew", "Apun", "K", "betaF", "betaP")){
  orl_posterior_means[[parameter]] = apply(orl_posteriors[[parameter]], c(2,3), mean)
}
```



## Calculate Correlations
```{r, eval = F}
set.seed(20230630)
correlations = data.frame()

for(s in 1:2){
  for(parameter in c("Arew", "Apun", "K", "betaF", "betaP")){
    
    # good proportions
    curr_orl = orl_posterior_means[[parameter]][,s][!is.na(good_proportions[,s])]
    curr_bx = good_proportions[,s][!is.na(good_proportions[,s])]
    corr = boot.cor.bca(x = curr_orl,
                        y = curr_bx,
                        null.hyp = NULL,
                        alternative = c("two.sided", "less", "greater"),
                        conf.level = 0.95, type = NULL, R = 9999)
    
    correlations = data.frame(proportion = "good",
                              session = s,
                              card = NA,
                              parameter = parameter,
                              r = corr$Observed,
                              CI = corr$Confidence.interval) %>%
      bind_rows(correlations)
    
    # bad proportions
    curr_orl = orl_posterior_means[[parameter]][,s][!is.na(bad_proportions[,s])]
    curr_bx = bad_proportions[,s][!is.na(bad_proportions[,s])]
    corr = boot.cor.bca(x = curr_orl,
                        y = curr_bx,
                        null.hyp = NULL,
                        alternative = c("two.sided", "less", "greater"),
                        conf.level = 0.95, type = NULL, R = 9999)
    
    correlations = data.frame(proportion = "bad",
                              session = s,
                              card = NA,
                              parameter = parameter,
                              r = corr$Observed,
                              CI = corr$Confidence.interval) %>%
      bind_rows(correlations)
    
    # play proportions
    curr_orl = orl_posterior_means[[parameter]][,s][!is.na(play_proportions[,s])]
    curr_bx = abs(play_proportions[,s][!is.na(play_proportions[,s])]-.5)
    corr = boot.cor.bca(x = curr_orl,
                        y = curr_bx,
                        null.hyp = NULL,
                        alternative = c("two.sided", "less", "greater"),
                        conf.level = 0.95, type = NULL, R = 9999)
    
    correlations = data.frame(proportion = "play",
                              session = s,
                              card = NA,
                              parameter = parameter,
                              r = corr$Observed,
                              CI = corr$Confidence.interval) %>%
      bind_rows(correlations)
      
    for(c in 1:4){
      # card proportions
      curr_orl = orl_posterior_means[[parameter]][,s][!is.na(card_proportions[,c,s])]
      curr_bx = card_proportions[,c,s][!is.na(card_proportions[,c,s])]
      corr = boot.cor.bca(x = curr_orl,
                          y = curr_bx,
                          null.hyp = NULL,
                          alternative = c("two.sided", "less", "greater"),
                          conf.level = 0.95, type = NULL, R = 9999)
      
      correlations = data.frame(proportion = "card",
                                session = s,
                                card = c,
                                parameter = parameter,
                                r = corr$Observed,
                                CI = corr$Confidence.interval) %>%
        bind_rows(correlations)
    }
  }
}
saveRDS(correlations, here("1_IGT_PP", "Figs_Tables", "Manuscript_Plots", "bx_correlations.RDS"))
```



## Plot
```{r}
correlations = readRDS(here("1_IGT_PP", "Figs_Tables", "Manuscript_Plots", "bx_correlations.RDS")) %>% 
    # label parameters with specific text %>% 
    separate(col = "CI", into = c("lower", "upper"), sep = ",") %>% 
    mutate(card_lab = recode(card, "1" = "A", "2" = "B", "3" = "C", "4" = "D"),
           card_lab = case_when(parameter == "K" ~ card_lab),
           r = round(r,2),
           r_lab = paste(ifelse(sign(r)==1," ","-"), stri_pad_right(str_remove(abs(r), "^0+"),
                                                                     width = 3, pad = "0"),sep=""), 
           lower = round(as.numeric(str_remove(lower, "\\(")),2),
           upper = round(as.numeric(str_remove(upper, "\\)")),2),
           
           lower_lab = paste(ifelse(sign(lower)==1,"","-"), stri_pad_right(str_remove(abs(lower), "^0+"),
                                                                     width = 3, pad = "0"),sep=""), 
           
           upper_lab = paste(ifelse(sign(upper)==1,"","-"), stri_pad_right(str_remove(abs(upper), "^0+"),
                                                                     width = 3, pad = "0"),sep=""),
           rCI = paste("=",r_lab," (",lower_lab,",",upper_lab,")",sep=""))
```



```{r}
orl_df = data.frame(orl_posterior_means) %>%
  mutate(ID = rownames(.)) %>%
  pivot_longer(cols = c(everything(), -ID),
               names_to = c("parameter", "session"),
               names_sep = "\\.",
               names_transform = list(parameter = as.character,
                                      session = as.numeric),
               values_to = "estimate")
```



### Card Proportion
```{r}
# labels = function(x) round(x, 2),
card_df = 
  data.frame(card_proportions[,,]) %>% 
  mutate(ID = rownames(.)) %>% 
  pivot_longer(cols = c(everything(), -ID),
               names_to = c("card", "session"),
               names_sep = "\\.", names_prefix = "X",
               names_transform = list(card = as.numeric,
                                      session = as.numeric),
               values_to = "proportion")


for(sess in 1:2){
  tiff(here("1_IGT_PP", "Figs_Tables", "Manuscript_Plots",
            paste0("Card_Proportions_Session", sess, ".tiff")),
       width = 15, height = 12.5, units = "cm", res = 300)
    # display plot in tiff
    print(
      # data
      # temp =
        filter(correlations, proportion == "card") %>% 
        select(-proportion) %>% 
        left_join(orl_df) %>% left_join(card_df) %>% 
        filter(session == sess) %>% 
        # label parameters with specific text
        mutate(card_lab = recode(card, "1" = "A", "2" = "B", "3" = "C", "4" = "D"),
               card_lab = case_when(parameter == "K" ~ card_lab),
               parameter = factor(parameter,
                                  levels = c("Arew", "Apun", "betaF", "betaP", "K"),
                                  labels = c(expression(paste(italic(A),"+",sep="")),
                                             expression(paste(italic(A),"-",sep="")),
                                             expression(paste("\u03B2",italic(f),sep="")),
                                             expression(paste("\u03B2",italic(p),sep="")),
                                             expression(italic(K))))) %>% 
        # plot
        ggplot(aes(x = estimate, y = (proportion*100))) +
          # geoms
          geom_point(size = 1, color = "gray25") +
          geom_smooth(method = "lm", formula = "y ~ x", color = "black", se = F, size = .5,
                    fullrange = T) +
          # scales
          scale_x_continuous(labels = function(x) sprintf("%.2f", round(x, 2)),
                             n.breaks = 3) +
          scale_y_continuous(breaks = c(25, 50, 75, 100), limits = c(25, 100)) +
          # themes
          geom_text_npc(aes(npcx = "right", npcy = "top", label = card_lab), hjust = 0) +
          geom_text_npc(aes(npcx = "middle", npcy = "top",
                            label = rCI), size = 2, vjust = -1) +
          geom_text_npc(aes(npcx = "left", npcy = "top"), label = expression(italic(r)),
                        size = 2, hjust = -1.25, vjust = -1.425) +
          labs(x = "Estimate", y = "% Played") +
          coord_cartesian(clip = "off") +
          theme_classic() +
          theme(axis.text.x = element_text(color = "black"),
                axis.text.y = element_text(color = "black"),
                plot.margin = unit(c(.3, .3, .3, .3), "cm"),
                panel.spacing = unit(0, "cm"),
                strip.background = element_rect(fill = "transparent", colour = "transparent"),
                strip.text.x = element_text(size = 12, vjust = 1.5),
                strip.text.y = element_blank(),
                panel.background = element_rect(fill = "transparent", colour = "transparent"),
                plot.background = element_rect(fill = "transparent", color = "transparent"),
                aspect.ratio = 1) +
          facet_rep_grid(card~parameter, scales = "free",
                         labeller = label_parsed)
    )
  dev.off()
}
```



### Good Proportion
```{r}
# labels = function(x) round(x, 2),
good_df = 
  data.frame(good_proportions) %>% 
  mutate(ID = rownames(.)) %>% 
  pivot_longer(cols = c(everything(), -ID),
               names_to = "session",
               names_prefix = "X",
               names_transform = list(session = as.numeric),
               values_to = "proportion")


tiff(here("1_IGT_PP", "Figs_Tables", "Manuscript_Plots", "Good_Proportions.tiff"),
     width = 15, height = 6.25, units = "cm", res = 300)
  # display plot in tiff
  print(
    # data
    # temp =
      filter(correlations, proportion == "good") %>% 
      select(-proportion) %>% 
      left_join(orl_df) %>% left_join(good_df) %>% 
      # label parameters with specific text
      mutate(sess_lab = case_when(parameter == "K" ~ session),
             parameter = factor(parameter,
                                levels = c("Arew", "Apun", "betaF", "betaP", "K"),
                                labels = c(expression(paste(italic(A),"+",sep="")),
                                           expression(paste(italic(A),"-",sep="")),
                                           expression(paste("\u03B2",italic(f),sep="")),
                                           expression(paste("\u03B2",italic(p),sep="")),
                                           expression(italic(K))))) %>% 
      # plot
      ggplot(aes(x = estimate, y = (proportion*100))) +
        # geoms
        geom_point(size = 1, color = "gray25") +
        geom_smooth(method = "lm", formula = "y ~ x", color = "black", se = F, size = .5,
                    fullrange = T) +
        # scales
        scale_x_continuous(labels = function(x) sprintf("%.1f", round(x, 1)),
                           n.breaks = 3) +
        scale_y_continuous(breaks = c(25, 50, 75, 100), limits = c(25, 100)) +
        # themes
        geom_text_npc(aes(npcx = "right", npcy = "top", label = sess_lab), hjust = 0) +
        geom_text_npc(aes(npcx = "middle", npcy = "top",
                          label = rCI), size = 2, vjust = -1) +
        geom_text_npc(aes(npcx = "left", npcy = "top"), label = expression(italic(r)),
                      size = 2, hjust = 0, vjust = -1.425) +
        labs(x = "Estimate", y = "% Good Deck Played") +
        coord_cartesian(clip = "off") +
        theme_classic() +
        theme(axis.text.x = element_text(color = "black"),
              axis.text.y = element_text(color = "black"),
              plot.margin = unit(c(.3, .3, .3, .3), "cm"),
              panel.spacing = unit(0, "cm"),
              strip.background = element_rect(fill = "transparent", colour = "transparent"),
              strip.text.x = element_text(size = 12, vjust = 1.5),
              strip.text.y = element_blank(),
              panel.background = element_rect(fill = "transparent", colour = "transparent"),
              plot.background = element_rect(fill = "transparent", color = "transparent"),
              aspect.ratio = 1) +
        facet_rep_grid(session~parameter, scales = "free",
                       labeller = label_parsed)
  )
dev.off()
```



### Bad Proportion
```{r}
# labels = function(x) round(x, 2),
bad_df = 
  data.frame(bad_proportions) %>% 
  mutate(ID = rownames(.)) %>% 
  pivot_longer(cols = c(everything(), -ID),
               names_to = "session",
               names_prefix = "X",
               names_transform = list(session = as.numeric),
               values_to = "proportion")


tiff(here("1_IGT_PP", "Figs_Tables", "Manuscript_Plots", "Bad_Proportions.tiff"),
     width = 15, height = 6.25, units = "cm", res = 300)
  # display plot in tiff
  print(
    # data
    # temp =
      filter(correlations, proportion == "bad") %>% 
      select(-proportion) %>% 
      left_join(orl_df) %>% left_join(bad_df) %>% 
      # label parameters with specific text
      mutate(sess_lab = case_when(parameter == "K" ~ session),
             parameter = factor(parameter,
                                levels = c("Arew", "Apun", "betaF", "betaP", "K"),
                                labels = c(expression(paste(italic(A),"+",sep="")),
                                           expression(paste(italic(A),"-",sep="")),
                                           expression(paste("\u03B2",italic(f),sep="")),
                                           expression(paste("\u03B2",italic(p),sep="")),
                                           expression(italic(K))))) %>% 
      # plot
      ggplot(aes(x = estimate, y = (proportion*100))) +
        # geoms
        geom_point(size = 1, color = "gray25") +
        geom_smooth(method = "lm", formula = "y ~ x", color = "black", se = F, size = .5,
                    fullrange = T) +
        # scales
        scale_x_continuous(labels = function(x) sprintf("%.1f", round(x, 1)),
                           n.breaks = 3) +
        scale_y_continuous(breaks = c(25, 50, 75, 100), limits = c(25, 100)) +
        # themes
        geom_text_npc(aes(npcx = "right", npcy = "top", label = sess_lab), hjust = 0) +
        geom_text_npc(aes(npcx = "middle", npcy = "top",
                          label = rCI), size = 2, vjust = -1) +
        geom_text_npc(aes(npcx = "left", npcy = "top"), label = expression(italic(r)),
                      size = 2, hjust = 0, vjust = -1.425) +
        labs(x = "Estimate", y = "% Bad Deck Played") +
        coord_cartesian(clip = "off") +
        theme_classic() +
        theme(axis.text.x = element_text(color = "black"),
              axis.text.y = element_text(color = "black"),
              plot.margin = unit(c(.3, .3, .3, .3), "cm"),
              panel.spacing = unit(0, "cm"),
              strip.background = element_rect(fill = "transparent", colour = "transparent"),
              strip.text.x = element_text(size = 12, vjust = 1.5),
              strip.text.y = element_blank(),
              panel.background = element_rect(fill = "transparent", colour = "transparent"),
              plot.background = element_rect(fill = "transparent", color = "transparent"),
              aspect.ratio = 1) +
        facet_rep_grid(session~parameter, scales = "free",
                       labeller = label_parsed)
  )
dev.off()
```


# ---------------------------------------
# Test-Retest Reliability
```{r}
  tiff(here("1_IGT_PP", "Figs_Tables", "Manuscript_Plots", "reliability_coefficients.tiff"),
       width = 15, height = 6.25, units = "cm", res = 300)
  bind_rows(data.frame(parameter = "Arew", r = orl_posteriors$R_Arew[,2,1]),
            data.frame(parameter = "Apun", r = orl_posteriors$R_Apun[,2,1]),
            data.frame(parameter = "betaF", r = orl_posteriors$R_betaF[,2,1]),
            data.frame(parameter = "betaP", r = orl_posteriors$R_betaP[,2,1]),
            data.frame(parameter = "K", r = orl_posteriors$R_K[,2,1])) %>% 
    mutate(parameter = factor(parameter,
                              levels = c("Arew", "Apun", "betaF", "betaP", "K"),
                              labels = c(expression(paste(italic(A),"+",sep="")),
                                         expression(paste(italic(A),"-",sep="")),
                                         expression(paste("\u03B2",italic(f),sep="")),
                                         expression(paste("\u03B2",italic(p),sep="")),
                                         expression(italic(K))))) %>% 
    group_by(parameter) %>% 
    mutate(mu_r = mean(r), lower = HDIofMCMC(r)[1], upper = HDIofMCMC(r)[2],
           mu_r_lab = paste(ifelse(sign(round(mu_r,2))==1," ","-"),
                            stri_pad_right(str_remove(abs(round(mu_r,2)), "^0+"),
                                           width = 3, pad = "0"),sep=""), 
           lower = as.numeric(str_remove(lower, "\\(")),
           upper = as.numeric(str_remove(upper, "\\(")),
           
           lower_lab = paste(ifelse(sign(round(lower,2))==1,"","-"),
                             stri_pad_right(str_remove(abs(round(lower,2)), "^0+"),
                                            width = 3, pad = "0"),sep=""), 
           upper_lab = paste(ifelse(sign(round(upper,2))==1,"","-"),
                             stri_pad_right(str_remove(abs(round(upper,2)), "^0+"),
                                            width = 3, pad = "0"),sep=""),
           upper_lab = case_when(round(upper,2) == 1 ~ "1.00", T ~ upper_lab),
           mu_rCI = paste("=",mu_r_lab," (",lower_lab,",",upper_lab,")",sep="")) %>% 
    ggplot(aes(x = r)) +
      # geoms
      geom_histogram(aes(y = ..density..), color = "black", fill = "gray45",
                     linewidth = .1, bins = 50) +
      geom_text_npc(aes(npcx = "left", npcy = "top"), label = expression(italic(r)),
                    size = 2, hjust = -3, vjust = -1.425) +
      geom_text_npc(aes(npcx = "middle", npcy = "top",
                        label = mu_rCI), size = 2, vjust = -1) +
      geom_hline(yintercept = 0) +
      geom_vline(aes(xintercept = mu_r), color = "red2") +
      # scales
      scale_x_continuous(limits = c(-1,1), expand = c(0,0), breaks = seq(-1,1,.5),
                         labels = c("-1","-.5","0",".5", "1")) +
      scale_y_continuous(limits = c(0,NA), expand = c(0,0), n.breaks = 3) +
      # themes
      labs(x = "Reliability Coefficient", y = "Density") +
      coord_cartesian(clip = "off") +
      theme_classic() +
      theme(axis.text.x = element_text(color = "black"),
            axis.text.y = element_text(color = "black"),
            axis.ticks = element_line(color = "black"),
            axis.line.x = element_line(color = "transparent"),
            plot.margin = unit(c(.3, .3, .3, .3), "cm"),
            panel.spacing = unit(.25, "cm"),
            strip.background = element_rect(fill = "transparent", colour = "transparent"),
            strip.text.x = element_text(size = 12, vjust = 1.5),
            strip.text.y = element_blank(),
            panel.background = element_rect(fill = "transparent", colour = "transparent"),
            plot.background = element_rect(fill = "transparent", color = "transparent"),
            aspect.ratio = 1) +
      facet_rep_grid(.~parameter, scales = "free",
                     labeller = label_parsed) +
      geom_segment(aes(x = lower, xend = upper, y = .025, yend = .025), size = 1, color = "red2", linewidth = .5)
dev.off()
```



# ---------------------------------------
















