---
title: "Evaluating Group-Based Covariate Model"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
library(grid)
library(zoo)
library(ggh4x)
```



## RMD Setup
```{r}
groups = c("Anx", "Dep", "SUD")
model_name = "Covariate_Joint_ORL_Bias"
sample = "T1_parent_Anx_Dep_SUD"


focal_parameters = c(
  "mu_Arew", "mu_Apun", "mu_betaF", "mu_betaB", 
  "sigma_Arew", "sigma_Apun", "sigma_betaF", "sigma_betaB", 
  "Arew", "Apun", "betaF", "betaB", 
  "beta_Arew", "beta_Apun", "beta_betaF", "beta_betaB", 
  "R_Arew", "R_Apun", "R_betaF", "R_betaB"
)


group_parameters <- grep("mu|sigma|R|beta_", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma|R|beta_", focal_parameters, value=TRUE, invert=TRUE)
```



## Load Data
```{r}
# -----------------------------------------------------------------------------------
# read in raw data
stan_data = readRDS(here("1_TADS_Parents_PP", "Data", "1_Stan",
                         paste("design", sample, "IGT.RDS", sep = "_")))


# -----------------------------------------------------------------------------------
# subset participant to exclude
sub_keep = stan_data$ID_participant[stan_data$X[,1,] == 0]


# -----------------------------------------------------------------------------------
# read in model fit
orl_fit = readRDS(here("1_TADS_Parents_PP", "Data", "2_Fitted",
                       model_name,
                       paste(sample, model_name, "fit.rds", sep = "_")))


# -----------------------------------------------------------------------------------
# read in posteriors
orl_posteriors = readRDS(here("1_TADS_Parents_PP", "Data", "2_Fitted",
                              model_name,
                              paste(sample, model_name, "posteriors.rds", sep = "_")))


# -----------------------------------------------------------------------------------
# read in rhats
orl_rhats = readRDS(here("1_TADS_Parents_PP", "Data", "2_Fitted",
                         model_name,
                         paste(sample, model_name, "rhats.rds", sep = "_")))


# -----------------------------------------------------------------------------------
# read in BIS/BAS
bis_bas = bind_rows(select(readRDS(here("1_TADS_Parents_PP", "Data", "0_Raw",
                       "T1_dad_BIS_BAS.rds")), -c(sex, session)),
                    select(readRDS(here("1_TADS_Parents_PP", "Data", "0_Raw",
                       "T1_mom_BIS_BAS.rds")), -c(sex, session)))
```



# -------------------------------------------
# Model Diagnostics
## Traceplots
```{r, eval = F}
tiff(here("1_TADS_Parents_PP", "Figs_Tables",
          model_name, 
          sample,
          "group_traceplots.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  traceplot(
    orl_fit,
    pars = group_parameters
)
dev.off()


for(i in person_parameters){
  tiff(here("1_TADS_Parents_PP", "Figs_Tables",
            model_name,
            sample,
            paste(i, "traceplots.tiff")),
       width = 100, height = 100, units = "cm", res = 300)
    traceplot(orl_fit,
              pars = i
              ) %>% print()
    dev.off()
}
```



## PPC Plots
### Prep Data
```{r, eval = F}
source(here("1_TADS_Parents_PP", "Code", "R", "3_other", "helpful_functions.R"))


# get indices for each group-membership
g_indices = list()
g_indices[["Anx"]] = stan_data$X[,2,1] == 1
g_indices[["Dep"]] = stan_data$X[,3,1] == 1
g_indices[["SUD"]] = stan_data$X[,4,1] == 1
g_indices[["Con"]] = g_indices$Anx + g_indices$Dep + g_indices$SUD == 0


# calculate posterior predictions and choice proportions
PPCs = data.frame()
for(g in names(g_indices)){
  PPCs = calculate_PPCs(cards = stan_data$card[g_indices[[g]],,],
                            trials = stan_data$Tsubj[g_indices[[g]]],
                            predicted_choices = orl_posteriors$choice_pred[,g_indices[[g]],,], 
                            observed_choices = stan_data$choice[g_indices[[g]],,]) %>% 
    mutate(group = factor(g, levels = c("Con", groups[1], groups[2],
                                        groups[3]), ordered = T)) %>% 
    bind_rows(PPCs)
}


# save data
saveRDS(PPCs,
        here("1_TADS_Parents_PP", "Data", "2_Fitted",
             model_name,
             paste(sample, model_name, "PPCs.rds", sep = "_")))
```



```{r}
PPCs = readRDS(here("1_TADS_Parents_PP", "Data", "2_Fitted",
                    model_name,
                    paste(sample, model_name, "PPCs.rds", sep = "_")))
```



### Within-Group PPC Plot
```{r, eval = F}
bin_width = 3
tiff(here("1_TADS_Parents_PP", "Figs_Tables",
          model_name, sample, "Within-Group PPCs.tiff"),
     width = 7, height = 5.25, units = "cm", res = 300)

  # simplify data
  PPCs %>% 
    group_by(trial, deck, group) %>% 
    summarise(observed = mean(observed), mu = mean(mu),
              lower50 = mean(lower50), upper50 = mean(upper50),
              lower95 = mean(lower95), upper95 = mean(upper95)) %>%
    ungroup() %>% group_by(deck, group) %>% 
    # calculate rolling averages
    mutate(observed = rollapply(observed, width = bin_width, FUN = mean,
                                na.rm = TRUE, fill = NA, partial = T),
           mu = rollapply(mu, width = bin_width, FUN = mean,
                          na.rm = TRUE, fill = NA, partial = T),
           lower50 = rollapply(lower50, width = bin_width, FUN = mean,
                               na.rm = TRUE, fill = NA, partial = T),
           upper50 = rollapply(upper50, width = bin_width, FUN = mean,
                               na.rm = TRUE, fill = NA, partial = T),
           lower95 = rollapply(lower95, width = bin_width, FUN = mean,
                               na.rm = TRUE, fill = NA, partial = T),
           upper95 = rollapply(upper95, width = bin_width, FUN = mean,
                               na.rm = TRUE, fill = NA, partial = T)) %>% 
    # plotting
    ggplot(aes(x = trial, color = deck)) +
      # geoms
      geom_ribbon(aes(ymin = lower95, ymax = upper95, fill = deck), color = "transparent",
                  alpha = .25) +
      geom_ribbon(aes(ymin = lower50, ymax = upper50, fill = deck), color = "transparent",
                  alpha = .5) +
      geom_line(aes(y = mu), linewidth = .25) +
      geom_point(aes(y = observed, fill = deck), color = "black",
                 shape = 21, size = .75) +
      geom_vline(xintercept = c(10.5, 20.5), linewidth = .25, linetype = "dashed") +
      geom_text_npc(aes(npcx = "left", npcy = "top", label = group),
                    hjust = .1, vjust = .675) +
      # scales
      scale_y_continuous(limits = c(.5,1),
                         breaks = seq(0,1,.25)) +
      scale_color_manual(values = c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
      scale_fill_manual(values = c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
      # theme
      labs(x = "Trial", y = "Proportion Play",
           color = "Deck:", fill = "Deck:") +
      theme_classic() +
      theme(legend.title = element_text(size = 8),
            legend.background = element_rect(fill = "white", colour = "white"),
            legend.position = c(.5, 1.05), 
            legend.spacing.x = unit(0, 'cm'),
            legend.spacing.y = unit(-.25, 'cm'),
            legend.text = element_text(size = 8),
            legend.direction = "horizontal",
            legend.margin = margin(t = .01, b = .01, r = .01, unit = 'cm'),
            legend.key.size = unit(.25, "cm"),
            axis.text = element_text(color = "black"),
            plot.margin = margin(t = .5, r = .1, unit = 'cm'),
            strip.text = element_blank(),
            strip.background = element_blank(),
            panel.spacing.x = unit(-.5,"lines"),
            panel.spacing.y = unit(-.25,"lines")
            ) +
      guides(color = guide_legend(override.aes = list(size = 1.25), nrow = 1)) +
      facet_rep_wrap(group~.)
dev.off()
```



### Person-Level PPC Plot
#### Subset Persons
```{r}
ind_parameters = data.frame(ID = stan_data$ID_participant,
                            anx = stan_data$X[,2,],
                            dep = stan_data$X[,3,],
                            sud = stan_data$X[,4,],
                            # group-level parameter means
                            con_Arew = apply(orl_posteriors$mu_Arew, 3, mean)[1],
                            con_Apun = apply(orl_posteriors$mu_Apun, 3, mean)[1],
                            con_betaF = apply(orl_posteriors$mu_betaF, 3, mean)[1],
                            con_betaB = apply(orl_posteriors$mu_betaB, 3, mean)[1],
                            
                            anx_Arew = apply(orl_posteriors$mu_Arew, 3, mean)[2],
                            anx_Apun = apply(orl_posteriors$mu_Apun, 3, mean)[2],
                            anx_betaF = apply(orl_posteriors$mu_betaF, 3, mean)[2],
                            anx_betaB = apply(orl_posteriors$mu_betaB, 3, mean)[2],
                            
                            dep_Arew = apply(orl_posteriors$mu_Arew, 3, mean)[3],
                            dep_Apun = apply(orl_posteriors$mu_Apun, 3, mean)[3],
                            dep_betaF = apply(orl_posteriors$mu_betaF, 3, mean)[3],
                            dep_betaB = apply(orl_posteriors$mu_betaB, 3, mean)[3],
                            
                            sud_Arew = apply(orl_posteriors$mu_Arew, 3, mean)[4],
                            sud_Apun = apply(orl_posteriors$mu_Apun, 3, mean)[4],
                            sud_betaF = apply(orl_posteriors$mu_betaF, 3, mean)[4],
                            sud_betaB = apply(orl_posteriors$mu_betaB, 3, mean)[4],
                            # ind-level parameter means
                            ind_Arew = apply(orl_posteriors$Arew, 2, mean),
                            ind_Apun = apply(orl_posteriors$Apun, 2, mean),
                            ind_betaF = apply(orl_posteriors$betaF, 2, mean),
                            ind_betaB = apply(orl_posteriors$betaB, 2, mean)) %>% 
  pivot_longer(c(starts_with("con"), starts_with("anx_"), starts_with("dep_"), starts_with("sud_")),
               names_to = c("diag", "parameter"), names_sep = "_", values_to = "mu") %>% 
  mutate(con = case_when(anx + dep + sud == 0 ~ 1, T ~ 0),
         diff_Arew = (mu - ind_Arew)^2,
         diff_Apun = (mu - ind_Apun)^2,
         diff_betaF = (mu - ind_betaF)^2,
         diff_betaB = (mu - ind_betaB)^2)

con_index = ind_parameters %>% 
  filter(con == 1, diag == "con") %>% 
  mutate(z_diff_Arew = (diff_Arew - mean(diff_Arew)) / sd(diff_Arew),
         z_diff_Apun = (diff_Apun - mean(diff_Apun)) / sd(diff_Apun),
         z_diff_betaF = (diff_betaF - mean(diff_betaF)) / sd(diff_betaF),
         z_diff_betaB = (diff_betaB - mean(diff_betaB)) / sd(diff_betaB),
         combined_z = (z_diff_Arew + z_diff_Apun + z_diff_betaF + z_diff_betaB) / 4,
         min_z = min(combined_z),
         closest_to_mean = min_z == combined_z) %>% 
  filter(closest_to_mean) %>% .$ID

anx_index = ind_parameters %>% 
  filter(anx == 1, diag == "anx") %>% 
  mutate(z_diff_Arew = (diff_Arew - mean(diff_Arew)) / sd(diff_Arew),
         z_diff_Apun = (diff_Apun - mean(diff_Apun)) / sd(diff_Apun),
         z_diff_betaF = (diff_betaF - mean(diff_betaF)) / sd(diff_betaF),
         z_diff_betaB = (diff_betaB - mean(diff_betaB)) / sd(diff_betaB),
         combined_z = (z_diff_Arew + z_diff_Apun + z_diff_betaF + z_diff_betaB) / 4,
         min_z = min(combined_z),
         closest_to_mean = min_z == combined_z) %>% 
  filter(closest_to_mean) %>% .$ID

dep_index = ind_parameters %>% 
  filter(dep == 1, diag == "dep") %>% 
  mutate(z_diff_Arew = (diff_Arew - mean(diff_Arew)) / sd(diff_Arew),
         z_diff_Apun = (diff_Apun - mean(diff_Apun)) / sd(diff_Apun),
         z_diff_betaF = (diff_betaF - mean(diff_betaF)) / sd(diff_betaF),
         z_diff_betaB = (diff_betaB - mean(diff_betaB)) / sd(diff_betaB),
         combined_z = (z_diff_Arew + z_diff_Apun + z_diff_betaF + z_diff_betaB) / 4,
         min_z = min(combined_z),
         closest_to_mean = min_z == combined_z) %>% 
  filter(closest_to_mean) %>% .$ID

sud_index = ind_parameters %>% 
  filter(sud == 1, diag == "sud") %>% 
  mutate(z_diff_Arew = (diff_Arew - mean(diff_Arew)) / sd(diff_Arew),
         z_diff_Apun = (diff_Apun - mean(diff_Apun)) / sd(diff_Apun),
         z_diff_betaF = (diff_betaF - mean(diff_betaF)) / sd(diff_betaF),
         z_diff_betaB = (diff_betaB - mean(diff_betaB)) / sd(diff_betaB),
         combined_z = (z_diff_Arew + z_diff_Apun + z_diff_betaF + z_diff_betaB) / 4,
         min_z = min(combined_z),
         closest_to_mean = min_z == combined_z) %>% 
  filter(closest_to_mean) %>% .$ID
```



#### Calculate PPCs
```{r, eval = T}
ind_PPCs = data.frame(ID = stan_data$ID_participant,
                      deck = stan_data$card,
                      choice = ifelse(stan_data$choice == 1, 1, 0),
                      pred = apply(ifelse(orl_posteriors$choice_pred == 1, 1, 0), c(2, 3), mean)) %>% 
  pivot_longer(c(starts_with("deck"), starts_with("choice"), starts_with("pred")),
               names_to = c("dv", "trial"), names_sep = "\\.", values_to = "value",
               names_transform = list(trial = as.numeric)) %>% 
  pivot_wider(names_from = "dv", values_from = "value")


# save data
saveRDS(ind_PPCs,
        here("1_TADS_Parents_PP", "Data", "2_Fitted",
             model_name,
             paste(sample, model_name, "ind_PPCs.rds", sep = "_")))
```



```{r}
ind_PPCs = readRDS(here("1_TADS_Parents_PP", "Data", "2_Fitted",
                        model_name,
                        paste(sample, model_name, "ind_PPC_data.rds", sep = "_")))
```



#### Con v Anx PPC Plots
```{r, eval = T}
bin_width = 6
tiff(here("1_TADS_Parents_PP", "Figs_Tables",
          model_name, sample, "Person-Level PPCs.tiff"),
     width = 7, height = 5.5, units = "cm", res = 300)

  # simplify data
  ind_PPCs %>% 
    filter(ID %in% c(con_index, anx_index, dep_index)) %>% 
    mutate(group = case_when(ID == con_index ~ "Con", ID == anx_index ~ "Anx", ID == dep_index ~ "Dep"),
           group = factor(group, levels = c("Con", groups[1], groups[2],
                                            groups[3]), ordered = T),
           deck = chartr("1234", "ABCD", as.character(deck)),
           deck = paste("Deck", deck)) %>% 
    group_by(ID, group, deck) %>%
    arrange(trial) %>% 
    mutate(trial = 1:30,
           # pred = rollapply(pred, width = bin_width, FUN = mean,
           #                  na.rm = TRUE, fill = NA, partial = T),
           observed = rollapply(choice, width = bin_width, FUN = mean,
                                na.rm = TRUE, fill = NA, partial = T)) %>% 
    # plotting
    ggplot(aes(x = trial, color = group, fill = group)) +
      # geoms
      geom_line(aes(y = pred), linewidth = .5) +
      geom_point(aes(y = observed), color = "black",
                  shape = 21, size = .75) +
      geom_vline(xintercept = c(10.5, 20.5), linewidth = .25, linetype = "dashed") +
      # scales
      scale_y_continuous(limits = c(0,1),
                         breaks = seq(0,1,.25)) +
      scale_color_manual(values = c("black", "#D81B60", "#068C75"),
                         limits = c("Con", "Anx", "Dep")) +
      scale_fill_manual(values = c("black", "#D81B60", "#068C75"),
                        limits = c("Con", "Anx", "Dep")) +
      # theme
      labs(x = "Trial", y = "Proportion Play") +
      theme_classic() +
      theme(legend.title = element_blank(),
            legend.background = element_rect(fill = "transparent", colour = "transparent"),
            legend.position = c(.5, 1.15), 
            legend.spacing.x = unit(0, 'cm'),
            legend.spacing.y = unit(-.25, 'cm'),
            legend.text = element_text(size = 8),
            legend.direction = "horizontal",
            legend.margin = margin(t = .05, b = .01, r = .01, unit = 'cm'),
            legend.key.size = unit(.25, "cm"),
            axis.text = element_text(color = "black"),
            plot.margin = margin(t = .25, r = .1, unit = 'cm'),
            strip.text = element_text(vjust = -1.5),
            strip.background = element_blank(),
            panel.spacing.x = unit(-.5,"lines"),
            panel.spacing.y = unit(-1,"lines")
            ) +
      guides(color = guide_legend(override.aes = list(size = 1.25), nrow = 1)) +
      facet_rep_wrap(deck~.)
dev.off()
```



#### Con v Dep PPC Plots
```{r, eval = T}
bin_width = 6
tiff(here("1_TADS_Parents_PP", "Figs_Tables",
          model_name, sample, "Person-Level Con v Dep PPCs.tiff"),
     width = 7, height = 4, units = "cm", res = 300)

  # simplify data
  ind_PPCs %>% 
    filter(ID %in% c(con_index, dep_index)) %>% 
    mutate(group = case_when(ID == con_index ~ "Con", ID == dep_index ~ "Dep"),
           group = factor(group, levels = c("Con", groups[1], groups[2],
                                            groups[3]), ordered = T),
           deck = chartr("1234", "ABCD", as.character(deck))) %>% 
    group_by(ID, group, deck) %>%
    arrange(trial) %>% 
    mutate(trial = 1:30,
           # pred = rollapply(pred, width = bin_width, FUN = mean,
           #                  na.rm = TRUE, fill = NA, partial = T),
           observed = rollapply(choice, width = bin_width, FUN = mean,
                                na.rm = TRUE, fill = NA, partial = T)) %>% 
    # plotting
    ggplot(aes(x = trial, color = deck, fill = deck)) +
      # geoms
      geom_line(aes(y = pred), linewidth = .5) +
      geom_point(aes(y = observed), color = "black",
                 shape = 21, size = .75) +
      geom_text_npc(aes(npcx = .3875, npcy = "top", label = group),
                    hjust = .1, vjust = .675) +
      geom_vline(xintercept = c(10.5, 20.5), linewidth = .25, linetype = "dashed") +
      # scales
      scale_y_continuous(limits = c(0,1),
                         breaks = seq(0,1,.25)) +
      scale_color_manual(values = c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
      scale_fill_manual(values = c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
      # theme
      labs(x = "Trial", y = "Proportion Play",
           color = "Deck:", fill = "Deck:") +
      theme_classic() +
      theme(legend.title = element_text(size = 8),
            legend.background = element_rect(fill = "white", colour = "white"),
            legend.position = c(.5, 1.05), 
            legend.spacing.x = unit(0, 'cm'),
            legend.spacing.y = unit(-.25, 'cm'),
            legend.text = element_text(size = 8),
            legend.direction = "horizontal",
            legend.margin = margin(t = .01, b = .01, r = .01, unit = 'cm'),
            legend.key.size = unit(.25, "cm"),
            axis.text = element_text(color = "black"),
            plot.margin = margin(t = .5, r = .1, unit = 'cm'),
            strip.text = element_blank(),
            strip.background = element_blank(),
            panel.spacing.x = unit(-.5,"lines"),
            panel.spacing.y = unit(-.25,"lines")
            ) +
      guides(color = guide_legend(override.aes = list(size = 1.25), nrow = 1)) +
      facet_rep_wrap(group~.)
dev.off()
```



# -------------------------------------------
# Posterior Distributions
## Prep Data
```{r, eval = T}
orl_grp_parameters = data.frame(
  iteration = 1:((orl_fit@sim$iter -
                    orl_fit@sim$warmup) *
                   orl_fit@sim$chains),
  Arew_mu = orl_posteriors$mu_Arew,
  Apun_mu = orl_posteriors$mu_Apun,
  betaF_mu = orl_posteriors$mu_betaF,
  betaB_mu = orl_posteriors$mu_betaB,
  Arew_beta.1.2 = orl_posteriors$beta_Arew[,2],
  Arew_beta.1.3 = orl_posteriors$beta_Arew[,3],
  Arew_beta.1.4 = orl_posteriors$beta_Arew[,4],
  Apun_beta.1.2 = orl_posteriors$beta_Apun[,2],
  Apun_beta.1.3 = orl_posteriors$beta_Apun[,3],
  Apun_beta.1.4 = orl_posteriors$beta_Apun[,4],
  betaF_beta.1.2 = orl_posteriors$beta_betaF[,2],
  betaF_beta.1.3 = orl_posteriors$beta_betaF[,3],
  betaF_beta.1.4 = orl_posteriors$beta_betaF[,4],
  betaB_beta.1.2 = orl_posteriors$beta_betaB[,2],
  betaB_beta.1.3 = orl_posteriors$beta_betaB[,3],
  betaB_beta.1.4 = orl_posteriors$beta_betaB[,4]) %>% 
  pivot_longer(starts_with(c("Arew", "Apun", "betaF", "betaB")),
               names_to = c("orl_par", "session", "group"),
               values_to = "estimate", names_sep = "\\.") %>% 
  mutate(grp_parameter = case_when(str_detect(orl_par, "mu") ~ "mu",
                                   str_detect(orl_par, "_beta") ~ "beta"),
         orl_parameter = str_remove(orl_par, "_mu|_beta")) %>% 
  select(-c(session, orl_par)) %>% 
  mutate(group = case_when(group == 1 & grp_parameter == "mu" ~ "Con",
                           group == 2 & grp_parameter == "mu" ~ "Anx",
                           group == 3 & grp_parameter == "mu" ~ "Dep",
                           group == 4 & grp_parameter == "mu" ~ "SUD",
                           group == 2 & grp_parameter == "beta" ~ "Anx",
                           group == 3 & grp_parameter == "beta" ~ "Dep",
                           group == 4 & grp_parameter == "beta" ~ "SUD"),
         orl_parameter = factor(orl_parameter, ordered = T,
                                levels = c("Arew", "Apun", "betaF", "betaB")),
         grp_parameter = factor(grp_parameter, levels = c("mu", "beta"), ordered = T,
                         labels = c("Mu", "Beta")),
         group = factor(group, levels = c("Con", "Anx", "Dep", "SUD"),
                        ordered = T))
```



## Descriptives
```{r}
orl_grp_parameters %>% 
  group_by(group, grp_parameter, orl_parameter) %>% 
  summarise(mu = mean(estimate),
            lower = HDIofMCMC(estimate)[1],
            upper = HDIofMCMC(estimate)[2],
            sig = case_when(lower < 0 & upper < 0 ~ "*", lower > 0 & upper > 0 ~ "*",
                            T ~ "")) %>% ungroup() %>% 
  mutate(sig = case_when(grp_parameter == "Mu" ~ "", T ~ sig),
         mu = round(mu, 2), lower = round(lower, 2), upper = round(upper,2),
         combined = paste0(mu, " [", lower, ",", upper, "]", sig)) %>% 
  select(-c(mu, lower, upper, sig)) %>% 
  pivot_wider(names_from = "group", values_from = "combined") %>% 
  mutate(order_grp = case_when(grp_parameter == "Mu" ~ 1, T ~ 2),
         order_orl = match(orl_parameter, c("Arew", "Apun", "betaF", "betaB")[1:4])) %>% 
  arrange(order_orl, order_grp) %>% 
  write.csv(here("1_TADS_Parents_PP", "Figs_Tables",
               model_name, sample,
               "Covariate_ORL_Descriptives.csv"))
```



## X-Axis
```{r}
x_scaling = list(grp_parameter == "Mu" & orl_parameter == "Arew" ~
                   scale_x_continuous(limits = c(0, .2), breaks = seq(0, .2, length.out = 3),
                                      expand = expansion(mult = .05)),
                 grp_parameter == "Mu" & orl_parameter == "Apun" ~
                   scale_x_continuous(limits = c(0, .2), breaks = seq(0, .2, length.out = 3),
                                      expand = expansion(mult = .05)),
                 grp_parameter == "Mu" & orl_parameter == "betaF" ~
                   scale_x_continuous(limits = c(1, 6), breaks = seq(1, 6, length.out = 3),
                                      expand = expansion(mult = .05)),
                 grp_parameter == "Mu" & orl_parameter == "betaB" ~
                   scale_x_continuous(limits = c(0, 1.5), breaks = seq(0, 1.5, length.out = 3),
                                      expand = expansion(mult = .05)),
                 
                 grp_parameter == "Beta" & orl_parameter == "Arew" ~
                   scale_x_continuous(limits = c(-.4, .4), breaks = seq(-.4, .4, length.out = 3),
                                      expand = expansion(mult = .05)),
                 grp_parameter == "Beta" & orl_parameter == "Apun" ~
                   scale_x_continuous(limits = c(-.4, .4), breaks = seq(-.4, .4, length.out = 3),
                                      expand = expansion(mult = .05)),
                 grp_parameter == "Beta" & orl_parameter == "betaF" ~
                   scale_x_continuous(limits = c(-2.5, 2.5), breaks = seq(-2.5, 2.5, length.out = 3),
                                      expand = expansion(mult = .05)),
                 grp_parameter == "Beta" & orl_parameter == "betaB" ~
                   scale_x_continuous(limits = c(-.75, .75), breaks = seq(-.8, .8, length.out = 3),
                                      expand = expansion(mult = .05))
                 )
```



## Make Plots
```{r}
horizontal_lab = data.frame(
  grp_parameter = factor(c("mu", "beta"), levels = c("mu", "beta"), ordered = T,
                         labels = c("Mu", "Beta")),
  lab_ = c("Mu", "Beta"),
  orl_parameter = factor("Arew", ordered = T,
                         levels = c("Arew", "Apun", "betaF", "betaB")))


  # build plot
tiff(here("1_TADS_Parents_PP", "Figs_Tables",
          model_name, sample,
          "Covariate_ORL_Plots.tiff"),
     width = 7, height = 7, units = "cm", res = 300)
  orl_grp_parameters %>% 
    ggplot(aes(x = estimate, fill = group)) +
      # geoms
      geom_text_npc(data = horizontal_lab, aes(label = lab_),
                    npcx = "left", npcy = "top", size = 4, vjust = 1) +
      geom_density(alpha = .5, linewidth = .25) +
      geom_hline(yintercept = 0) +
      # scales
      scale_y_continuous(limits = c(0,NA), expand = expansion(mult = c(0, .05)), n.breaks = 3) +
      scale_color_manual(values = c("black", "#D81B60", "#068C75", "#FFC107"),
                         limits = c("Con", "Anx", "Dep", "SUD")) +
      scale_fill_manual(values = c("black", "#D81B60", "#068C75", "#FFC107"),
                        limits = c("Con", "Anx", "Dep", "SUD")) +
      # themes
      labs(x = "Estimate") +
      coord_cartesian(clip = "off") +
      theme_classic() +
      theme(axis.text.x = element_text(color = "black", size = 8),
            axis.ticks.x = element_line(color = "black"),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.line.y = element_blank(),
            axis.title.y = element_blank(),
            legend.text = element_text(size = 6),
            legend.spacing.x = unit(.05, 'cm'),
            legend.key.size = unit(.5, "lines"), legend.spacing.y = unit(.05, "lines"),
            legend.position = c(.125, .125),
            legend.background = element_rect(fill = "transparent", colour = "transparent"),
            legend.title = element_blank(),
            plot.margin = unit(c(.05, .2, 0, .1), "cm"),
            panel.spacing.x = unit(.25, "cm"),
            panel.spacing.y = unit(.1, "cm"),
            strip.text = element_blank(),
            strip.background = element_rect(fill = "transparent", colour = "transparent"),
            panel.background = element_rect(fill = "transparent", colour = "transparent"),
            plot.background = element_rect(fill = "transparent", color = "transparent")) +
      facet_rep_wrap(orl_parameter~grp_parameter, nrow = 4, ncol = 2,
                     scales = "free") +
      facetted_pos_scales(x = x_scaling) +
      guides(fill = guide_legend(nrow = 2))
  
    grid.text(c(expression(paste(italic(A),"+",sep="")),
                expression(paste(italic(A),"-",sep="")),
                expression(paste("\u03B2",italic(f),sep="")),
                expression(paste("\u03B2",italic(b),sep=""))),
              x = rep(.93, 4), y = c(.92, .68, .45, .21),
              gp = gpar(fontsize = 9.5))
dev.off()
```



# -------------------------------------------
# Correlations with BIS/BAS
## Calculate Cors
```{r, eval = F}
ORL_BIS_BAS = data.frame()

for(p in c("Arew", "Apun", "betaF", "betaB")) {
  for(i in 1:nrow(orl_posteriors$Arew)){
    cur_data = data.frame(ID = stan_data$ID_OG,
                          participant = ifelse(stan_data$participant_number == 2, "dad", "mom"),
                          estimate = orl_posteriors[[p]][i,,]) %>% 
      left_join(bis_bas) %>% 
      filter(!is.na(bas_drive))
    
    ORL_BIS_BAS = data.frame(iteration = i,
                             parameter = p,
                             bas_drive = cor(cur_data$estimate, cur_data$bas_drive),
                             bas_fun = cor(cur_data$estimate, cur_data$bas_fun),
                             bas_rew = cor(cur_data$estimate, cur_data$bas_rew),
                             bas_tot = cor(cur_data$estimate, cur_data$bas_tot),
                             bis = cor(cur_data$estimate, cur_data$bis)) %>% 
      bind_rows(ORL_BIS_BAS)
  }
}

saveRDS(ORL_BIS_BAS,
        here("1_TADS_Parents_PP", "Data", "2_Fitted", model_name,
             paste(sample, "ORL_BIS_BAS.RDS", sep = "_")))
```



```{r}
ORL_BIS_BAS = readRDS(here("1_TADS_Parents_PP", "Data", "2_Fitted", model_name,
                           paste(sample, "ORL_BIS_BAS.RDS", sep = "_")))
```



## Results
```{r}
BIS_BAS_results = data.frame()

for(scale in c("bas_drive", "bas_fun", "bas_rew", "bas_tot", "bis")){
  for(p in c("Arew", "Apun", "betaF", "betaB")){
    cur_cor = filter(ORL_BIS_BAS, parameter == p)
    
    BIS_BAS_results = data.frame(
      parameter = p,
      scale = scale,
      mu = mean(cur_cor[[scale]]),
      lower = HDIofMCMC(cur_cor[[scale]])[1],
      upper = HDIofMCMC(cur_cor[[scale]])[2]) %>% 
      bind_rows(BIS_BAS_results)
  }
}

BIS_BAS_results = BIS_BAS_results %>% 
  mutate(sig = case_when(lower < 0 & upper < 0 ~ "*",
                         lower > 0 & upper > 0 ~ "*",
                         T ~ ""))
write.csv(BIS_BAS_results, here("1_TADS_Parents_PP", "Figs_Tables",
                                model_name, sample,
                                paste(sample, "BIS_BAS_correlations.csv", sep = "_")))
```



# -------------------------------------------
