---
title: "Fitting ORL"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
source(here("Code", "R", "3_Other", "helpful_functions.R"))
```



## Load Data
```{r}
model_name = "ORL"
samples = c("T1_parent", "T2_parent", "T3_parent", 
            "T4_parent", "T5_parent")

stan_data = list()

for(sample in samples){
  stan_data[[sample]] = readRDS(here("Data", "1_Stan",
                           paste(sample, "IGT.RDS", sep = "_")))
  
  stan_data[[sample]]$ID = stan_data$ID_part # set ID variable to use in stan code
}

focal_parameters = c(
  "mu_Arew", "mu_Apun", "mu_K", "mu_betaF", "mu_betaP",
  "Arew", "Apun", "K", "betaF", "betaP"
)


group_parameters <- grep("mu", focal_parameters, value=TRUE)
person_parameters <- grep("mu", focal_parameters, value=TRUE, invert=TRUE)
```



# -------------------------------------------
# Choice Proportions Across Time
```{r}
# stan_data
```



# -------------------------------------------
# ORL Mus Across Time
## Import Posteriors
```{r}
orl_posteriors = list()

for(sample in samples){
  orl_posteriors[[sample]] = readRDS(here("Data", "2_Fitted",
                                          model_name,
                                          paste(sample, model_name, "posteriors.rds", sep = "_")))
}
```



## Process Posteriors
```{r}
orl_mus = data.frame()

for(sample in samples){
  for(p in group_parameters){
    cur_hdi_50 = HDIofMCMC(orl_posteriors[[sample]][[p]], credMass = .50)
    cur_hdi_95 = HDIofMCMC(orl_posteriors[[sample]][[p]], credMass = .95)
    orl_mus = data.frame(time = as.numeric(substr(sample, 2, 2)),
                         parameter = p,
                         mu = mean(orl_posteriors[[sample]][[p]]),
                         lower50 = cur_hdi_50[1],
                         upper50 = cur_hdi_50[2],
                         lower95 = cur_hdi_95[1],
                         upper95 = cur_hdi_95[2]) %>% 
      bind_rows(orl_mus)
  }
}
```



## Plot ORL Mus
```{r, eval = T}
tiff(here("Figs_Tables", model_name, "longitudinal_ORL.tiff"),
     width = 5, height = 9, units = "cm", res = 300)

  orl_mus %>%
    # plotting
    ggplot(aes(x = time)) +
      geom_line(aes(y = mu), color = "goldenrod3") +
      geom_linerange(aes(ymin = lower95, ymax = upper95),
                     linewidth = .35, color = "goldenrod3", alpha = .35) +
      geom_linerange(aes(ymin = lower50, ymax = upper50),
                     linewidth = .35, color = "goldenrod3") +
      geom_point(aes(y = mu), shape = 21, size = 1,
                 color = "goldenrod3", fill = "white") +
      labs(x = "Session", y = "Posterior Mean +/- HDI") +
      theme_classic() +
      theme(axis.text = element_text(color = "black"),
            strip.background = element_blank(),
            panel.spacing.x = unit(-.5,"lines"),
            panel.spacing.y = unit(0,"lines")) +
      facet_rep_grid(parameter~., scales = "free",
                     labeller = labeller(parameter = c("mu_Arew" = "A+",
                                                       "mu_Apun" = "A-",
                                                       "mu_K" = "K",
                                                       "mu_betaF" = "BetaF",
                                                       "mu_betaP" = "BetaP")))
  
dev.off()
```



# -------------------------------------------
```{r}

```











