---
title: "Evaluating Longitudinal Covariate Model"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
library(grid)
# source(here("Code", "R", "3_Other", "helpful_functions.R"))
```



## RMD Setup
```{r}
model_name = "Covariate_Joint_ORL"
sample = "T12345_parent"

stan_data = readRDS(here("1_TADS_Parents_PP", "Data", "1_Stan",
                         paste("design", sample, "IGT.RDS", sep = "_")))

focal_parameters = c(
  "mu_Arew", "mu_Apun", "mu_K", "mu_betaF", "mu_betaP", 
  "sigma_Arew", "sigma_Apun", "sigma_K", "sigma_betaF", "sigma_betaP", 
  "Arew", "Apun", "K", "betaF", "betaP", 
  "R_Arew", "R_Apun", "R_K", "R_betaF", "R_betaP"
)


group_parameters <- grep("mu|sigma|R", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma|R", focal_parameters, value=TRUE, invert=TRUE)
```



## Load Data
```{r}
orl_fit = readRDS(here("1_TADS_Parents_PP", "Data", "2_Fitted",
                       model_name,
                       paste(sample, model_name, "fit.rds", sep = "_")))


orl_posteriors = readRDS(here("1_TADS_Parents_PP", "Data", "2_Fitted",
                              model_name,
                              paste(sample, model_name, "posteriors.rds", sep = "_")))


orl_rhats = readRDS(here("1_TADS_Parents_PP", "Data", "2_Fitted",
                         model_name,
                         paste(sample, model_name, "rhats.rds", sep = "_")))
```



# -------------------------------------------
# Model Diagnostics
## Traceplots
```{r, eval = F}
tiff(here("1_TADS_Parents_PP", "Figs_Tables",
          model_name, sample,
          "group_traceplots.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  traceplot(
    orl_fit,
    pars = group_parameters
)
dev.off()


for(i in person_parameters){
  tiff(here("1_TADS_Parents_PP", "Figs_Tables",
            model_name, sample,
            "traceplots.tiff"),
       width = 100, height = 100, units = "cm", res = 300)
    traceplot(orl_fit,
              pars = i
              ) %>% print()
    dev.off()
}
```



## PPC Plots
### Prep Data
```{r}
source(here("1_TADS_Parents_PP", "Code", "R", "3_other", "helpful_functions.R"))

PPC_data = data.frame()

for(s in 1:stan_data$S){
  PPC_data = calculate_PPCs(posteriors = orl_posteriors$choice_pred[,,,s], 
                            stan_data = stan_data$choice[,,s],
                            data_type = "data.frame") %>% 
    mutate(session = s) %>% 
    bind_rows(PPC_data)
}
```



### Plot
```{r, eval = F}
tiff(here("1_TADS_Parents_PP", "Figs_Tables",
          model_name, sample,
          "PPC.tiff"),
     width = 15, height = stan_data$S*3.5, units = "cm", res = 300)

  # simplify data
  PPC_data %>% 
    group_by(trial, deck, session) %>% 
    summarise(observed = mean(observed), mu = mean(mu),
              lower50 = mean(lower50), upper50 = mean(upper50),
              lower95 = mean(lower95), upper95 = mean(upper95)) %>%
    # plotting
    ggplot(aes(x = trial,
               group = trial)) +
    # geoms
    geom_linerange(aes(ymin = lower95, ymax = upper95),
                   linewidth = .35, color = "goldenrod3", alpha = .35) +
    geom_linerange(aes(ymin = lower50, ymax = upper50),
                   linewidth = .35, color = "goldenrod3") +
    geom_point(aes(y = mu, color = "Predicted", fill = "Predicted"),
               shape = 21, size = .75) +
    geom_point(aes(y = observed, color = "Observed", fill = "Observed"),
               shape = 21, size = .75) +
    # scales
    scale_y_continuous(limits = c(0,1),
                       breaks = seq(0,1,.25)) +
    scale_color_manual(name = "hello", values = c("Observed" = "black", "Predicted" = "goldenrod3")) +
    scale_fill_manual(name = "hello", values = c("Observed" = "black", "Predicted" = "white")) +
    # theme
    labs(x = "Trial", y = "Proportion Play") +
    theme_classic() +
    theme(axis.text = element_text(color = "black"),
          legend.title = element_blank(),
          legend.background = element_rect(fill = "transparent", colour = "transparent"),
          legend.position = c(.84,.59), 
          legend.spacing.x = unit(0, 'cm'),
          legend.spacing.y = unit(-.25, 'cm'),
          legend.text = element_text(size = 8),
          strip.background = element_blank(),
          panel.spacing.x = unit(-.5,"lines"),
          legend.key.size = unit(.25, "cm"),
          panel.spacing.y = unit(0,"lines")) +
    guides(color = guide_legend(override.aes = list(size = 1.25))) +
    facet_rep_grid(session~deck,
                   labeller = labeller(deck = c("A" = "Deck A", "B" = "Deck B",
                                                "C" = "Deck C", "D" = "Deck D")))
dev.off()
```



# -------------------------------------------
# NEEDS WORK
# Change-Over-Time
## Process Posteriors
```{r, eval = T}
orl_mus = data.frame()

for(sample in samples){
  for(p in group_parameters){
    cur_hdi_50 = HDIofMCMC(orl_posteriors[[sample]][[p]], credMass = .50)
    cur_hdi_95 = HDIofMCMC(orl_posteriors[[sample]][[p]], credMass = .95)
    orl_mus = data.frame(time = as.numeric(substr(sample, 2, 2)),
                         parameter = p,
                         mu = mean(orl_posteriors[[sample]][[p]]),
                         lower50 = cur_hdi_50[1],
                         upper50 = cur_hdi_50[2],
                         lower95 = cur_hdi_95[1],
                         upper95 = cur_hdi_95[2]) %>% 
      bind_rows(orl_mus)
  }
}
```



## Plot
```{r, eval = T}
tiff(here("1_TADS_Parents_PP", "Figs_Tables",
          model_name, sample,
          "Change-Over-Time.tiff"),
     width = 5, height = 9, units = "cm", res = 300)

  orl_mus %>%
    # plotting
    ggplot(aes(x = time)) +
      geom_line(aes(y = mu), color = "goldenrod3") +
      geom_linerange(aes(ymin = lower95, ymax = upper95),
                     linewidth = .35, color = "goldenrod3", alpha = .35) +
      geom_linerange(aes(ymin = lower50, ymax = upper50),
                     linewidth = .35, color = "goldenrod3") +
      geom_point(aes(y = mu), shape = 21, size = 1,
                 color = "goldenrod3", fill = "white") +
      labs(x = "Session", y = "Posterior Mean +/- HDI") +
      theme_classic() +
      theme(axis.text = element_text(color = "black"),
            strip.background = element_blank(),
            panel.spacing.x = unit(-.5,"lines"),
            panel.spacing.y = unit(0,"lines")) +
      facet_rep_grid(parameter~., scales = "free",
                     labeller = labeller(parameter = c("mu_Arew" = "A+",
                                                       "mu_Apun" = "A-",
                                                       "mu_K" = "K",
                                                       "mu_betaF" = "BetaF",
                                                       "mu_betaP" = "BetaP")))
  
dev.off()
```



# -------------------------------------------
# Between-Session Correlations
## Make Plot
```{r, eval = T}
correlations_plot =  bind_rows(data.frame(parameter = "Arew", r = orl_posteriors$R_Arew[,2,1]),
            data.frame(parameter = "Apun", r = orl_posteriors$R_Apun[,2,1]),
            data.frame(parameter = "betaF", r = orl_posteriors$R_betaF[,2,1]),
            data.frame(parameter = "betaP", r = orl_posteriors$R_betaP[,2,1]),
            data.frame(parameter = "K", r = orl_posteriors$R_K[,2,1])) %>% 
    mutate(parameter = factor(parameter,
                              levels = c("Arew", "Apun", "betaF", "betaP", "K"),
                              labels = c(expression(paste(italic(A),"+",sep="")),
                                         expression(paste(italic(A),"-",sep="")),
                                         expression(paste("\u03B2",italic(f),sep="")),
                                         expression(paste("\u03B2",italic(p),sep="")),
                                         expression(italic(K))))) %>% 
    group_by(parameter) %>% 
    mutate(mu_r = mean(r),
           estimate_lab = paste("r=", ifelse(sign(round(mu_r,2))==1," ","-"), stri_pad_right(str_remove(abs(round(mu_r,2)), "^0+"),
                                                                                             width = 3, pad = "0"),sep=""),
           lower = HDIofMCMC(r)[1], upper = HDIofMCMC(r)[2],
           below_0 = paste0(round(mean(r<0)*100), "% < 0"), above_0 = paste0(round(mean(r>0)*100), "% > 0"),
           height_ci = max(density(r)$x)*.025, height_m = max(density(r)$x)*.35) %>% 
    ggplot(aes(x = r)) +
      # geoms
      geom_histogram(aes(y = ..density..), color = "black", fill = "gray45",
                     linewidth = .1, bins = 50) +
      geom_text_npc(aes(npcx = "left", npcy = "top", label = below_0),
                    size = 2, vjust = -1.43) +
      geom_text_npc(aes(npcx = "right", npcy = "top", label = above_0),
                    size = 2, vjust = -1.43) +
      geom_text(aes(x = -.925, y = height_m, label = estimate_lab),
                    size = 2) +
      geom_hline(yintercept = 0) +
      geom_vline(aes(xintercept = mu_r), color = "red2", linewidth = .4) +
      geom_errorbarh(aes(xmin = lower, xmax = upper,
                         y = height_ci),
                         color = "red", linewidth = .4) +
      # scales
      scale_x_continuous(limits = c(-1,1), expand = c(0,0), breaks = seq(-1,1,.5),
                         labels = c("-1","-.5","0",".5", "1")) +
      scale_y_continuous(limits = c(0,NA), expand = c(0,0), n.breaks = 3) +
      # themes
      labs(x = "Correlation", y = "Density") +
      coord_cartesian(clip = "off") +
      theme_classic() +
      theme(axis.text.x = element_text(color = "black"),
            axis.ticks.x = element_line(color = "black"),
            axis.line.x = element_line(color = "transparent"),
            axis.text.y = element_blank(),
            axis.ticks.y = element_blank(),
            axis.line.y = element_blank(),
            plot.margin = unit(c(.1, .3, .1, .3), "cm"),
            panel.spacing = unit(.25, "cm"),
            strip.background = element_rect(fill = "transparent", colour = "transparent"),
            strip.text.x = element_text(size = 12, vjust = 1.5),
            strip.text.y = element_blank(),
            panel.background = element_rect(fill = "transparent", colour = "transparent"),
            plot.background = element_rect(fill = "transparent", color = "transparent")) +
      facet_rep_grid(.~parameter, scales = "free",
                     labeller = label_parsed)
```



## Save Plot
```{r, eval = T}
tiff(here("1_TADS_Parents_PP", "Figs_Tables",
          model_name, sample,
          "Between-Session Correlations.tiff"),
     width = 14.6, height = 4, units = "cm", res = 300)

  grid.newpage()
  pushViewport(viewport(x = .5, y = .5, width = 1, height = 1))
  grid.draw(correlations_plot)
  
dev.off()
```



# -------------------------------------------



















