---
title: "Manuscript Plots"
output: html_document
date: "2023-03-09"
---



# ---------------------------------------
# Setup
## Loading Packages
```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(foreach)
library(tidybayes)
library(patchwork)
library(abind)
library(zoo)
library(here)
library(ggpubr)
library(egg)
library(grid)
library(tidyverse)
library(lemon)
library(ggpp)
library(wBoot)
library(stringi)
library(ggh4x)
library(hBayesDM)
source(here("1_IGT_PP", "Code", "R", "3_other", "helpful_functions.R"))
```



## Load Stan Data
```{r include=FALSE}
sample = "T5_parent"

stan_data = readRDS(here("1_TADS_Parents_PP", "Data", "1_Stan",
                         paste("design", sample, "IGT.RDS", sep = "_")))
```



# ---------------------------------------
# Prep Data
```{r}
bin_width = 5

data = data.frame(stan_data) %>%
  pivot_longer(cols = c(starts_with("card"), starts_with("choice"),
                        starts_with("outcome"), starts_with("sign")), 
               names_to = c("variable", "trial"), names_sep = "\\.") %>%
  pivot_wider(names_from = "variable", values_from = "value") %>% 
  filter(Tsubj == 120) %>% 
  select(ID_participant, ID_OG, ID_number, participant_number, card, trial, choice) %>% 
  group_by(ID_participant, ID_OG, ID_number, participant_number, card) %>% 
  arrange(trial) %>% 
  mutate(card_trial = 1:n(),
         choice = case_when(choice == 1 ~ 1, T ~ 0)) %>%  
  mutate(participant = case_when(participant_number == 1 ~ "child", 
                                 participant_number == 2 ~ "dad",
                                 participant_number == 3 ~ "mom"),
         choice = case_when(choice == 1 ~ 1, T ~ 0)) %>% 
  group_by(ID_participant, ID_OG, ID_number, participant_number, card) %>% 
  arrange(card_trial) %>%
  mutate(prop = rollapply(choice, width = bin_width, FUN = mean,
                          na.rm = TRUE, fill = NA, partial = T))
```




# ---------------------------------------
# Person-Level Plots
```{r}
row_length = 25
ID_groups = list()
for(i in 1:ceiling(stan_data$N/row_length)){
  ID_groups[[as.character(i)]] =
    stan_data$ID_participant[((i-1)*row_length+1):min(i*row_length, stan_data$N)]
}

for(cur_IDs in ID_groups){
  
  # simplify data
  cur_plot = data %>% 
    filter(ID_participant %in% cur_IDs) %>% 
    mutate(id = paste0("ID #", ID_OG, " (", ID_participant, ")"),
           deck = chartr("1234", "ABCD", as.character(card))) %>%
    # plotting
    ggplot(aes(x = card_trial, y = prop)) +
      # geoms
    geom_line(aes(color = deck), linewidth = .25) +
    geom_point(aes(color = deck), size = .75) +
    geom_vline(xintercept = c(10.5, 20.5), linewidth = .25, linetype = "dashed") +
    # scales
    scale_x_continuous(limits = c(0, 25), expand = c(.0175, .0175), breaks = seq(0, 25, 5)) +
    scale_y_continuous(limits = c(0, 1), expand = c(.015, .015), breaks = seq(0, 1, .25),
                       labels = c("0", ".25", ".50", ".75", "1")) +
    scale_color_manual(values = c("#999999", "#E69F00", "#56B4E9", "#009E73")) +
    # theme
    labs(x = "Trial", y = "Proportion Play") +
    theme_classic() +
    theme(axis.text = element_text(color = "black"),
          strip.background = element_blank(),
          panel.spacing.x = unit(-.5,"lines"),
          legend.title = element_blank(),
          legend.background = element_rect(fill = "transparent", colour = "transparent"),
          legend.position = "top",
          legend.spacing.x = unit(.15, 'cm'),
          legend.text = element_text(size = 8),
          legend.key.size = unit(.35, "cm"),
          panel.spacing.y = unit(0,"lines")) +
    guides(color = guide_legend(override.aes = list(size = 1.25))) +
    facet_rep_wrap(id~.)
    
    
  tiff(here("1_TADS_Parents_PP", "Figs_Tables", "Raw_data", sample,
            paste0("ID #", min(cur_IDs), "-", max(cur_IDs), " PPCs.tiff")),
       width = 15, height = 14, units = "cm", res = 300)
      print(cur_plot)
  dev.off()
}
```



























