---
title: "Fitting Self-Report Ind-Mu Binomial Model"
output: html_document
---



# -----------------------------------------------
# Setup
## Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)
library(here)
library(wBoot)
library(rstan)
library(foreach)
library(abind)
library(bayesplot)
```



## Load Data
```{r}
selfreport = readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "stan_ready_binomial_selfreport.rds"))
```



## Scales
```{r}
# scales = "prdep_tot" # For testing
scales = c(# Session 1 only
           "prdep_tot", "masqGDA", "masqAA", "masqGDD",
           # "masqAD", # Removed
           # Both Sessions
           "bastot", "basdrive", "basfunsk", "basrewres",
           "bis", "panas_pa", "panas_na", "shaps_tot")
```



# -----------------------------------------------
# Model
## Simulate Priors
```{r}
set.seed(20230607)
sim_kappa = rgamma(16000, shape = 2, rate = .05)
hist(sim_kappa, breaks = 50)
abline(v = mean(sim_kappa), col = "red")

sim_omega = rbeta(16000, shape1 = 1, shape2 = 1)
hist(sim_omega, breaks = 50)
abline(v = mean(sim_omega), col = "red")

sim_theta = rbeta(16000, shape1 = mean(sim_omega)*mean(sim_kappa),
                  shape2 = (1-mean(sim_omega))*mean(sim_kappa))
hist(sim_theta, breaks = 50, xlim = c(0,1))
abline(v = mean(sim_omega), col = "red")
```



## Fitting
```{r, eval = T}
stan_model = stan_model(here("1_IGT_PP", "Code", "Stan", "binomial_selfreport_indMu.stan"))

models = list()

for(scale in scales){
  print(paste("Begin fitting model for", scale))
  models[[scale]] =
    sampling(stan_model,
             data = selfreport[[scale]],
             iter = 5000, warmup = 1000,
             chains = 8, cores = 8,
             seed = 20230601)
  print(paste("End fitting model for", scale))
}
saveRDS(models, here("1_IGT_PP", "Data", "2_Fitted", "binomial_selfreport_indMu_fits.RDS"))
```



```{r}
models = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "binomial_selfreport_indMu_fits.RDS"))
```



## Diagnostics
```{r}
for(scale in scales){
  View(as.data.frame(rhat(models[[scale]])), title = scale)
}
```



```{r}
for(scale in scales){
 pairs(models[[scale]], pars = c("kappa", "omega"))
}
```



```{r}
for(scale in scales){
  tiff(here("1_IGT_PP", "Figs_Tables", "Binomial_SelfReport_IndMu",
            paste(scale, "grp_traceplot.tiff", sep = "_")),
       width = 15, height = 5, units = "cm", res = 300)
    traceplot(models[[scale]], pars = c("kappa", "omega")) %>% print()
  dev.off()
  
  tiff(here("1_IGT_PP", "Figs_Tables", "Binomial_SelfReport_IndMu",
            paste(scale, "thetas_traceplot.tiff", sep = "_")),
       width = 25, height = 20, units = "cm", res = 300)
    traceplot(models[[scale]], pars = "theta") %>% print()
  dev.off()
}
```



## PPCs
```{r}
set.seed(20230606)
for(scale in scales){
  posteriors = extract(models[[scale]])
  
  # Group-level means
  obs_grp_mean = mean(replace(selfreport[[scale]]$score, selfreport[[scale]]$score == -999, NA), na.rm = T)
  est_grp_mean = rbeta(10000,
                       shape1 = sample(posteriors$omega*posteriors$kappa, 10000, T),
                       shape2 = sample((1-posteriors$omega)*posteriors$kappa, 10000, T))*
                 selfreport[[scale]]$M
  
  # Person-level means
  obs_ind_mean = apply(replace(selfreport[[scale]]$score, selfreport[[scale]]$score == -999, NA), 1, mean, na.rm = T)
  est_ind_mean = apply(posteriors$theta*selfreport[[scale]]$M, 2, mean)
  
  correlations = vector()
  
  for(i in 1:length(posteriors$kappa)){
    correlations[i] = cor(obs_ind_mean, posteriors$theta[i,]*selfreport[[scale]]$M)
  }
  
  r_value = mean(correlations)
  
  xlimit = c(floor(min(c(obs_ind_mean, y = est_ind_mean))),
             ceiling(max(c(obs_ind_mean, y = est_ind_mean))))
  ylimit = c(floor(min(c(obs_ind_mean, y = est_ind_mean))),
             ceiling(max(c(obs_ind_mean, y = est_ind_mean))))
  
  par(pty="s")
  plot(x = obs_ind_mean, y = est_ind_mean,
       main = paste(scale, ", r = ", round(r_value, 2),"\n",
                    "Obs M = ", round(obs_grp_mean, 2), ", Est M = ", round(mean(est_grp_mean), 2), sep = ""),
       xlim = xlimit, xlab = "Observed",
       ylim = ylimit, ylab = "Estimated")
    abline(0,1)
    lines(x = c(obs_grp_mean, obs_grp_mean), y = c(-100, mean(est_grp_mean)))
    lines(x = c(-100, obs_grp_mean), y = c(mean(est_grp_mean), mean(est_grp_mean)))
}
```















