---
title: "Demographics"
output: html_document
---



# -----------------------------------------------
# Setup
## Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)
library(here)
library(wBoot)
```



## Set Seed
```{r}
set.seed(20230320)
```



## Self-Report Data
```{r}
sr_sess1 = read_sav(here("1_IGT_PP", "Data", "0_Raw", "MergedQuest_3.21.16-Session1.sav"),
                    col_select = c("ID", "PartDate", "DOB", "sex", "race", "Ethnicity")) %>% 
  # mutate(session = 1) %>%
  filter(ID >= 2049,                          # Subset PP participants
         ID != 2059,                          # Remove participant that played old IFT
         ID != 2083)                          # Remove participant that had no task data
```



## Calculate Demos
```{r}
demos = sr_sess1 %>% 
  mutate(PartDate = as.Date(PartDate, format = "%m/%d/%Y"),
         DOB = str_replace_all(DOB, "-", "/"),
         DOB = case_when(ID %in% c(2050, 2069, 2073, 2087) ~ as.Date(DOB, format = "%d/%b/%y"),
                         T ~ as.Date(DOB, format = "%m/%d/%Y")),
         age = time_length(difftime(PartDate, DOB), "years"),
         sex = case_when(sex == 1 ~ "Male", sex == 2 ~ "Female"),
         race = case_when(race == 1 ~ "Black/AA",
                          race == 2 ~ "Asian",
                          race == 3 ~ "White",
                          race == 4 ~ "Native Hawaiian/Pacific Islander",
                          race == 5 ~ "Native Alaskan",
                          race == 6 ~ "Other"))
```



# -----------------------------------------------
# Sex
```{r}
demos %>% 
  group_by(sex) %>% 
  summarise(n = n(),
            percent = n / 49,
            percent_round = round(n / 49, 2))
```



# Race
```{r}
demos %>% 
  group_by(race) %>% 
  summarise(n = n(),
            percent = n / 49,
            percent_round = round(n / 49, 2))
```



# Age
```{r}
demos %>% 
  filter(ID != 2068) %>% 
  summarise(M = round(mean(age, na.rm = T), 2),
            SD = round(sd(age, na.rm = T), 2),
            range(age, na.rm = T))
```




```{r}

```












