---
title: "Fitting Joint Test-Retest ORL"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(wBoot)
library(haven)
```



## Load Data
```{r}
stan_data <- readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "stan_ready_ORL_joint_retest.rds"))
full_data <- readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "Dataframe_Sess1&2.rds"))
```



# -------------------------------------------
# Fit Model
```{r, eval = F}
orl_model <- stan_model(here("1_IGT_PP", "Code", "Stan", "igt_orl_joint_indMu.stan"))

# Fit model
orl_fit <- sampling(
  orl_model, 
  data = stan_data,
  iter = 5000,
  warmup = 1000,
  chains = 4,
  cores = 4,
  seed = 43210
)



#save the fitted model as an .rds file
saveRDS(orl_fit, here("1_IGT_PP", "Data", "2_Fitted", "Joint", "orl_pp_joint_indMu.rds"))
```



```{r}
orl_fit <- readRDS(here("1_IGT_PP", "Data", "2_Fitted", "Joint", "orl_pp_joint_indMu.rds"))

iterations = orl_fit@sim$chains * (orl_fit@sim$iter - orl_fit@sim$warmup)
```



# -------------------------------------------
# Model Diagnostics
```{r}
posterior <- extract(orl_fit)

focal_parameters <- c(
  "mu_Arew", "mu_Apun", "mu_K",
  "mu_betaF", "mu_betaP", 
  "sigma_Arew", "sigma_Apun", "sigma_K",
  "sigma_betaF", "sigma_betaP", 
  "Arew", "Apun",
  "K", "betaF", "betaP"
)

group_parameters <- grep("mu|sigma", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma", focal_parameters, value=TRUE, invert=TRUE)
```



## Rhat
```{r}
rhats <- rhat(
  orl_fit,
  pars = focal_parameters
) %>% 
  as.data.frame() %>%
  mutate(parameter = rownames(.))
```



## Traceplots
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "Joint",
          "orl_pp_joint_indMu_group_traceplots.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  traceplot(
    orl_fit,
    pars = group_parameters
)
dev.off()

labels <- person_parameters

for(i in labels){
  tiff(here("1_IGT_PP", "Figs_Tables", "Joint",
            paste("orl_pp_joint_indMu_", i, "_traceplots.tiff", sep = "")),
       width = 35, height = 25, units = "cm", res = 300)
    traceplot(orl_fit,
              pars = i
              ) %>% print()
    dev.off()
  
}
```



# -------------------------------------------
# Inspect Parameters
## Means +/- PI
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "Joint",
          "orl_pp_joint_indMu_posterior_means.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  plot(orl_fit, pars = group_parameters)
dev.off()
```



## Posterior Distributions
```{r}
# Extract posterior distributions
parameters <- rstan::extract(orl_fit, pars = group_parameters) %>%
  data.frame()

tiff(here("1_IGT_PP", "Figs_Tables", "Joint",
          "orl_pp_joint_indMu_posterior_distributions.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  par(mfrow = c(5, 5)) # Create 5 x 5 facetted plot
  # Make a density plot of the posterior distributions for the focal parameters using a for loop
  for(i in colnames(parameters)){
    plot(density(parameters[ , i]), main = i)
    abline(v = mean(parameters[ , i]))
  }
dev.off()
```



# -------------------------------------------
## Results
### Test-Retest Correlations
```{r}
source(here("1_IGT_PP", "Code", "R", "1_Analyses", "plausible_correlations.R"))
```



```{r}
set.seed(20230525)
UT_Arew_Rs = matrix(data = NA, nrow = iterations)
UT_Apun_Rs = matrix(data = NA, nrow = iterations)
UT_K_Rs = matrix(data = NA, nrow = iterations)
betaF_Rs = matrix(data = NA, nrow = iterations)
betaP_Rs = matrix(data = NA, nrow = iterations)

for(i in 1:iterations){
  UT_Arew_Rs[i] = cor(posterior$Arew[i,,1], posterior$Arew[i,,2])
  UT_Apun_Rs[i] = cor(posterior$Apun[i,,1], posterior$Apun[i,,2])
  UT_K_Rs[i] = cor(posterior$K[i,,1], posterior$K[i,,2])
  betaF_Rs[i] = cor(posterior$betaF[i,,1], posterior$betaF[i,,2]) 
  betaP_Rs[i] = cor(posterior$betaP[i,,1], posterior$betaP[i,,2]) 
}
Arew_Rs = pop_correct_MCMC(UT_Arew_Rs, n_subj = 49, kappa = 1)
Apun_Rs = pop_correct_MCMC(UT_Apun_Rs, n_subj = 49, kappa = 1)
K_Rs = pop_correct_MCMC(UT_K_Rs, n_subj = 49, kappa = 1)

mean(Arew_Rs)
mean(Apun_Rs)
mean(K_Rs)
mean(betaF_Rs)
mean(betaP_Rs)

par(mfrow = c(2, 3))
plot(density(Arew_Rs), main = "A+")
abline(v = mean(Arew_Rs))
plot(density(Apun_Rs), main = "A-")
abline(v = mean(Apun_Rs))
plot(density(K_Rs), main = "K")
abline(v = mean(K_Rs))
plot(density(betaF_Rs), main = expression(paste(beta, italic(f), sep = "")))
abline(v = mean(betaF_Rs))
plot(density(betaP_Rs), main = expression(paste(beta, italic(p), sep = "")))
abline(v = mean(betaP_Rs))
```



### Session 1/2 Differences
```{r}
par(mfrow = c(2, 3))
plot(density(posterior$mu_pr[,2,1]), main = "A+")
abline(v = mean(posterior$mu_pr[,2,1]))
abline(v = HDIofMCMC(posterior$mu_pr[,2,1]), col = "red")

plot(density(posterior$mu_pr[,2,2]), main = "A-")
abline(v = mean(posterior$mu_pr[,2,2]))
abline(v = HDIofMCMC(posterior$mu_pr[,2,2]), col = "red")

plot(density(posterior$mu_pr[,2,3]), main = "K")
abline(v = mean(posterior$mu_pr[,2,3]))
abline(v = HDIofMCMC(posterior$mu_pr[,2,3]), col = "red")

plot(density(posterior$mu_pr[,2,4]), main = expression(paste(beta, italic(f), sep = "")))
abline(v = mean(posterior$mu_pr[,2,4]))
abline(v = HDIofMCMC(posterior$mu_pr[,2,4]), col = "red")

plot(density(posterior$mu_pr[,2,5]), main = expression(paste(beta, italic(p), sep = "")))
abline(v = mean(posterior$mu_pr[,2,5]))
abline(v = HDIofMCMC(posterior$mu_pr[,2,5]), col = "red")
```



### Self-Report Correlations
#### Load SR Data
```{r}
sr_sess1 = read_sav(here("1_IGT_PP", "Data", "0_Raw", "MergedQuest_3.21.16-Session1.sav"),
                    col_select = c("ID", "sex", "race", "Ethnicity",
                                   "bastot", "basdrive", "basfunsk",
                                   "basrewres", "bis", "panas_pa",
                                   "panas_na", "masqGDA", "masqAA", "masqGDD",
                                   "masqAD", "shaps_tot", "prdep_tot")) %>% 
  mutate(session = 1) %>%
  filter(ID >= 2049,                          # Subset PP participants
         ID != 2059,                          # Remove participant that played old IFT
         ID != 2083)                          # Remove participant that had no task data
scale_sess1 = c("bastot", "basdrive", "basfunsk", "basrewres", "bis",
                "panas_pa", "panas_na", "masqGDA", "masqAA", "masqGDD",
                "masqAD", "shaps_tot", "prdep_tot")

sr_sess2 = read_sav(here("1_IGT_PP", "Data", "0_Raw", "MergedQuest_3.21.16-Session2.sav"),
                    col_select = c("ID", "bastot", "basdrive", "basfunsk",
                                   "basrewres", "bis", "panas_pa",
                                   "panas_na", "shaps_tot")) %>% 
  mutate(session = 2) %>%
  filter(ID >= 2049,                          # Subset PP participants
         ID != 2059,                          # Remove participant that played old IFT
         ID != 2083,                          # Remove participant that had no task data
         !ID %in% c(2057, 2063, 2064,         # Remove participants that didn't do session 2
                    2067, 2086, 2090,
                    2093, 2094, 2096, 2098))
scale_sess2 = c("bastot", "basdrive", "basfunsk", "basrewres", "bis",
                "panas_pa", "panas_na", "shaps_tot")
```



#### Correlation Function
```{r}
get_SR_corrs = function(p_session, parameter, p_name, scale, scale_names){
  corrs = matrix(data = NA, nrow = iterations, ncol = length(scale_names),
                 dimnames = list(c(1:iterations), c(unique(scale_names))))
  
  for(scale_name in scale_names){
    for(i in 1:iterations){
      corrs[i, scale_name] = cor(posterior[[p_name]][i,,p_session], scale[[scale_name]])
    }
  }
  return(corrs)
}
```



#### ORL 1 vs SR 1
```{r}
print("Arew")
Arew1_SR1_Rs = get_SR_corrs(p_session = 1, parameter = posterior$Arew,
                            p_name = "Arew", scale = sr_sess1, scale_names = scale_sess1)
apply(Arew1_SR1_Rs, 2, mean)

print("Apun")
Apun1_SR1_Rs = get_SR_corrs(p_session = 1, parameter = posterior$Apun,
                            p_name = "Apun", scale = sr_sess1, scale_names = scale_sess1)
apply(Apun1_SR1_Rs, 2, mean)

print("K")
K1_SR1_Rs = get_SR_corrs(p_session = 1, parameter = posterior$K,
                         p_name = "K", scale = sr_sess1, scale_names = scale_sess1)
apply(K1_SR1_Rs, 2, mean)

print("BetaF")
betaF1_SR1_Rs = get_SR_corrs(p_session = 1, parameter = posterior$betaF,
                             p_name = "betaF", scale = sr_sess1, scale_names = scale_sess1)
apply(betaF1_SR1_Rs, 2, mean)

print("BetaP")
betaP1_SR1_Rs = get_SR_corrs(p_session = 1, parameter = posterior$betaP,
                             p_name = "betaP", scale = sr_sess1, scale_names = scale_sess1)
apply(betaP1_SR1_Rs, 2, mean)
```



#### ORL 1 vs SR 2
```{r, eval = F}
print("Arew")
Arew1_SR2_Rs = get_SR_corrs(p_session = 1, parameter = posterior$Arew,
                            p_name = "Arew", scale = sr_sess2, scale_names = scale_sess2)
apply(Arew1_SR2_Rs, 2, mean)

print("Apun")
Apun1_SR2_Rs = get_SR_corrs(p_session = 1, parameter = posterior$Apun,
                            p_name = "Apun", scale = sr_sess2, scale_names = scale_sess2)
apply(Apun1_SR2_Rs, 2, mean)

print("K")
K1_SR2_Rs = get_SR_corrs(p_session = 1, parameter = posterior$K,
                         p_name = "K", scale = sr_sess2, scale_names = scale_sess2)
apply(K1_SR2_Rs, 2, mean)

print("BetaF")
betaF1_SR2_Rs = get_SR_corrs(p_session = 1, parameter = posterior$betaF,
                             p_name = "betaF", scale = sr_sess2, scale_names = scale_sess2)
apply(betaF1_SR2_Rs, 2, mean)

print("BetaP")
betaP1_SR2_Rs = get_SR_corrs(p_session = 1, parameter = posterior$betaP,
                             p_name = "betaP", scale = sr_sess2, scale_names = scale_sess2)
apply(betaP1_SR2_Rs, 2, mean)
```



#### ORL 2 vs SR 1
```{r, eval = F}
print("Arew")
Arew2_SR1_Rs = get_SR_corrs(p_session = 2, parameter = posterior$Arew,
                            p_name = "Arew", scale = sr_sess1, scale_names = scale_sess1)
apply(Arew2_SR1_Rs, 2, mean)

print("Apun")
Apun2_SR1_Rs = get_SR_corrs(p_session = 2, parameter = posterior$Apun,
                            p_name = "Apun", scale = sr_sess1, scale_names = scale_sess1)
apply(Apun2_SR1_Rs, 2, mean)

print("K")
K2_SR1_Rs = get_SR_corrs(p_session = 2, parameter = posterior$K,
                         p_name = "K", scale = sr_sess1, scale_names = scale_sess1)
apply(K2_SR1_Rs, 2, mean)

print("BetaF")
betaF2_SR1_Rs = get_SR_corrs(p_session = 2, parameter = posterior$betaF,
                             p_name = "betaF", scale = sr_sess1, scale_names = scale_sess1)
apply(betaF2_SR1_Rs, 2, mean)

print("BetaP")
betaP2_SR1_Rs = get_SR_corrs(p_session = 2, parameter = posterior$betaP,
                             p_name = "betaP", scale = sr_sess1, scale_names = scale_sess1)
apply(betaP2_SR1_Rs, 2, mean)
```



#### ORL 2 vs SR 2
```{r}
print("Arew")
Arew2_SR2_Rs = get_SR_corrs(p_session = 2, parameter = posterior$Arew,
                            p_name = "Arew", scale = sr_sess2, scale_names = scale_sess2)
apply(Arew2_SR2_Rs, 2, mean)

print("Apun")
Apun2_SR2_Rs = get_SR_corrs(p_session = 2, parameter = posterior$Apun,
                            p_name = "Apun", scale = sr_sess2, scale_names = scale_sess2)
apply(Apun2_SR2_Rs, 2, mean)

print("K")
K2_SR2_Rs = get_SR_corrs(p_session = 2, parameter = posterior$K,
                         p_name = "K", scale = sr_sess2, scale_names = scale_sess2)
apply(K2_SR2_Rs, 2, mean)

print("BetaF")
betaF2_SR2_Rs = get_SR_corrs(p_session = 2, parameter = posterior$betaF,
                             p_name = "betaF", scale = sr_sess2, scale_names = scale_sess2)
apply(betaF2_SR2_Rs, 2, mean)

print("BetaP")
betaP2_SR2_Rs = get_SR_corrs(p_session = 2, parameter = posterior$betaP,
                             p_name = "betaP", scale = sr_sess2, scale_names = scale_sess2)
apply(betaP2_SR2_Rs, 2, mean)
```



# -------------------------------------------
#### Nothing done below here

#### Run Correlations
```{r}
# Loop through each scale from session 1
for(scale in c("bastot", "basdrive", "basfunsk",
               "basrewres", "bis", "panas_pa",
               "panas_na", "masqGDA", "masqAA", "masqGDD",
               "masqAD", "shaps_tot", "prdep_tot")){
  # Loop through each parameter from session 1
  for(param in unique(orl_blups$parameter)){
    
    curr_data = orl_blups %>%
      filter(parameter == param) %>%             # Subset orl parameter
      left_join(sr_sess1) %>%                    # Join scales to orl parameter
      select(-c(sex, race, Ethnicity)) %>%       # Remove columns that we don't need
      na.omit()                                  # Remove rows with NAs
    
    curr_scale = curr_data[[scale]]              # Subset scale data
    curr_estimate = curr_data[["blup_session1"]] # Subset estimate for parameter
    # Run the boot-strapped correlation between the current scale and the current parameter
    curr_cor = boot.cor.bca(x = curr_scale, y = curr_estimate,
                            null.hyp = NULL,
                            alternative = c("two.sided", "less", "greater"),
                            conf.level = 0.95, type = NULL, R = 9999)
    
    curr_ci = data.frame(data = curr_cor$Confidence.interval) %>%       # Get the confidence interval of the current correlation (this is a string)
      separate(col = data, sep = ",", into = c("lower", "upper")) %>%   # Separate confidence interval string into lower and upper CI columns
      # Remove parentheses and turn CIs into numerics
      mutate(lower = as.numeric(str_remove(lower, "[(]")),
             upper = as.numeric(str_remove(upper, "[)]")))
    
    # Bind the current correlation to the correlations dataframe while also detailing what the correlation is from (e.g., session, parameter, etc.)
    correlations = bind_rows(correlations,
                             data.frame(parameter_session = 1,
                                        scale_session = 1,
                                        parameter = param,
                                        scale = scale,
                                        r = curr_cor$Observed,
                                        lower_ci = curr_ci$lower[1],
                                        upper_ci = curr_ci$upper[1]))
  }
  
  # Loop through each parameter from session 2
  for(param in unique(orl_blups$parameter)){
    
    curr_data = orl_blups %>%
      filter(parameter == param) %>%             # Subset orl parameter
      left_join(sr_sess1) %>%                    # Join scales to orl parameter
      select(-c(sex, race, Ethnicity)) %>%       # Remove columns that we don't need
      na.omit()                                  # Remove rows with NAs
    
    curr_scale = curr_data[[scale]]              # Subset scale data
    curr_estimate = curr_data[["blup_session2"]] # Subset estimate for parameter
    # Run the boot-strapped correlation between the current scale and the current parameter
    curr_cor = boot.cor.bca(x = curr_scale, y = curr_estimate,
                            null.hyp = NULL,
                            alternative = c("two.sided", "less", "greater"),
                            conf.level = 0.95, type = NULL, R = 9999)
    
    curr_ci = data.frame(data = curr_cor$Confidence.interval) %>%       # Get the confidence interval of the current correlation (this is a string)
      separate(col = data, sep = ",", into = c("lower", "upper")) %>%   # Separate confidence interval string into lower and upper CI columns
      # Remove parentheses and turn CIs into numerics
      mutate(lower = as.numeric(str_remove(lower, "[(]")),
             upper = as.numeric(str_remove(upper, "[)]")))
    
    # Bind the current correlation to the correlations dataframe while also detailing what the correlation is from (e.g., session, parameter, etc.)
    correlations = bind_rows(correlations,
                             data.frame(parameter_session = 2,
                                        scale_session = 1,
                                        parameter = param,
                                        scale = scale,
                                        r = curr_cor$Observed,
                                        lower_ci = curr_ci$lower[1],
                                        upper_ci = curr_ci$upper[1]))
  }
}
```




```{r}
posterior_df <- posterior %>% data.frame()
# Get point estimates from the posterior for each parameter
posterior_means <- data.frame(estimate = colMeans(posterior_df)) %>% # Means
# posterior_means = data.frame(estimate = colMedians(posterior)) %>% # Medians
  mutate(col_name = rownames(.))


# Calculate overall BLUP for each participant
posterior_blups <- posterior_df %>% 
  select(starts_with("Arew"), starts_with("Apun"),
         starts_with("K"), starts_with("betaF"),
         starts_with("betaP"))
  # Use the values of col_name in ind_columns to select columns in posterior dataframe
  select(ind_columns$col_name) %>% 
  # Create a column with iteration number for each parameter
  mutate(iteration = rownames(.)) %>% 
  # Pivot data longer so that it's easier to separate what is the parameter, subject, and session from the posterior columns
  pivot_longer(cols = -iteration, names_to = "param_ID_sess", values_to = "estimate") %>% 
  separate(col = param_ID_sess, into = c("parameter", "ID", "session"), sep = "\\.") %>%
  # Pivot wider so that we can calculate the mean of session 1 and session 2 estimate on each iteration of the posterior
  pivot_wider(names_from = "session", values_from = "estimate", names_prefix = "session_") %>%
  mutate(overall_estimate = (session_1 + session_2)/2,
         ID = as.numeric(ID))

blups = posterior_blups %>% 
  # Calculate posterior means for individual subjects by session and overall
  group_by(parameter, ID) %>% 
  reframe(blup_session1 = mean(session_1),
          blup_session2 = mean(session_2),
          blup_overall = mean(overall_estimate)) %>% 
  left_join(reframe(full_data, subject = unique(subject), ID = unique(ID)))


# Bind posterior means for correlations
  # Note, these are not population-corrected - We do this in joint_test_retest_plots.Rmd
  # Create dataframe with names of correlations of interest
correlations = data.frame(parameter = c("Arew", "Apun", "K", "betaF", "betaP")) %>% 
  # Make a new column that has elements we can match to in the posterior_means dataframe
  mutate(col_name = paste("R_", parameter, ".2.1", sep = "")) %>% 
  # Join only the posterior means that have a matching row name in col_name, then remove col_name
  left_join(posterior_means) %>% select(-col_name)


# Save data
write.csv(mus, here("1_IGT_PP", "Data", "2_Fitted", "Joint_indMu",
                    "orl_pp_joint_indMu_mus.csv"))
write.csv(blups, here("1_IGT_PP", "Data", "2_Fitted", "Joint_indMu",
                      "orl_pp_joint_indMu_blups.csv"))
write.csv(correlations, here("1_IGT_PP", "Data", "2_Fitted", "Joint_indMu",
                             "orl_pp_joint_indMu_model_correlations.csv"))

saveRDS(mus, here("1_IGT_PP", "Data", "2_Fitted", "Joint_indMu",
                  "orl_pp_joint_indMu_mus.rds"))
saveRDS(blups, here("1_IGT_PP", "Data", "2_Fitted", "Joint_indMu",
                    "orl_pp_joint_indMu_blups.rds"))
saveRDS(posterior_blups, here("1_IGT_PP", "Data", "2_Fitted", "Joint_indMu",
                              "orl_pp_joint_indMu_posterior_blups.rds"))
saveRDS(correlations, here("1_IGT_PP", "Data", "2_Fitted", "Joint_indMu",
                           "orl_pp_joint_indMu_model_correlations.rds"))
```

# -------------------------------------------



















