---
title: "Fitting Joint Ind-Mu ORL"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(wBoot)
library(haven)
```



## Load Data
```{r}
igt_data = readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "stan_ready_ORL_IGT.rds"))
selfreport = readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "stan_ready_binomial_selfreport.rds"))
```



## Prep Stan Data
```{r}
# SPECIFY SCALE
# finished = "prdep_tot", "masqGDA", "masqAA", "masqGDD", "bastot", "basdrive"
#            "basrewres","panas_pa", "panas_na", "shaps_tot"

#            "bis" There was a problem with this one
#            "masqAD" was removed
scale = "basfunsk" # There was a problem with this one

# Change name of ID variable to make it more clear for checking order of IDs in next chunk
names(igt_data)[names(igt_data) == "subjIDs"] <- "igt_IDs"

stan_data = igt_data
stan_data$SR_sess = selfreport[[scale]]$S
stan_data$missing = selfreport[[scale]]$missing
stan_data$score = selfreport[[scale]]$score
stan_data$M = selfreport[[scale]]$M
stan_data$sr_IDs = selfreport[[scale]]$IDs
```



```{r}
# Check that orl and self-report IDs are in same order between data fed to models
ifelse(mean(stan_data$igt_IDs == stan_data$sr_IDs) == 1, "EQUAL", "NOT EQUAL")
```



# -------------------------------------------
# Fit Model
```{r, eval = F}
orl_model <- stan_model(here("1_IGT_PP", "Code", "Stan", "igt_selfreport_orl_binomial_joint_indMu.stan"))

# Fit model
orl_fit <- sampling(
  orl_model, 
  data = stan_data,
  iter = 5000,
  warmup = 1000,
  chains = 4,
  cores = 4,
  seed = 43210
)



#save the fitted model as an .rds file
saveRDS(orl_fit, here("1_IGT_PP", "Data", "2_Fitted", "Joint_ORL_Binomial",
                      paste("igt_", scale, "_orl_binomial_joint_indMu_fit.rds", sep = "")))
```



```{r}
orl_fit <- readRDS(here("1_IGT_PP", "Data", "2_Fitted", "Joint_ORL_Binomial",
                        paste("igt_", scale, "_orl_binomial_joint_indMu_fit.rds", sep = "")))

iterations = orl_fit@sim$chains * (orl_fit@sim$iter - orl_fit@sim$warmup)
```



# -------------------------------------------
# Model Diagnostics
```{r}
# orl_posteriors <- extract(orl_fit)
# saveRDS(orl_posteriors, here("1_IGT_PP", "Data", "2_Fitted", "Joint_ORL_Binomial",
#                              paste("igt_", scale, "_orl_binomial_joint_indMu_posteriors.rds", sep = "")))
orl_posteriors = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "Joint_ORL_Binomial",
                              paste("igt_", scale, "_orl_binomial_joint_indMu_posteriors.rds", sep = "")))

focal_parameters <- c(
  # group-level parameters
  "mu_Arew", "mu_Apun", "mu_K",
  "mu_betaF", "mu_betaP", "mu_theta",
  "sigma", "R",
  # person-level parameters
  "Arew", "Apun",
  "K", "betaF", "betaP",
  "theta"
)

group_parameters <- grep("mu|sigma|R", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma", focal_parameters, value=TRUE, invert=TRUE)
```



## Rhat
```{r}
rhats = rhat(orl_fit, pars = focal_parameters) %>%
  data.frame() %>% mutate(parameter = rownames(.))

saveRDS(rhats, here("1_IGT_PP", "Data", "2_Fitted", "Joint_ORL_Binomial",
                    paste("igt_", scale, "_orl_binomial_joint_indMu_rhats.rds", sep = "")))
rhats = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "Joint_ORL_Binomial",
                     paste("igt_", scale, "_orl_binomial_joint_indMu_rhats.rds", sep = "")))
```



## Traceplots
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "Joint_ORL_Binomial", scale,
          paste("igt_", scale, "_orl_binomial_joint_indMu_group_traceplots.tiff", sep = "")),
     width = 35, height = 25, units = "cm", res = 300)
  traceplot(
    orl_fit,
    pars = group_parameters
)
dev.off()


for(i in person_parameters){
  tiff(here("1_IGT_PP", "Figs_Tables", "Joint_ORL_Binomial", scale,
            paste("igt_", scale, "_orl_binomial_joint_indMu_", i, "_traceplots.tiff", sep = "")),
       width = 35, height = 25, units = "cm", res = 300)
    traceplot(orl_fit,
              pars = i
              ) %>% print()
    dev.off()
}
```



# -------------------------------------------
# Inspect Parameters
## Means +/- PI
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "Joint_ORL_Binomial", scale, 
          paste("igt_", scale, "_orl_binomial_joint_indMu_posterior_means.tiff", sep = "")),
     width = 35, height = 25, units = "cm", res = 300)
  plot(orl_fit, pars = group_parameters)
dev.off()
```



## Posterior Distributions
```{r}
labs = c("Arew", "Apun", "K", "betaF", "betaP", "theta")
R_labs = matrix(nrow = 6, ncol = 6)
for(i in 1:6){
  for(k in seq(1, 6)){
    R_labs[k,i] = paste(labs[i], " vs ", labs[k], sep = "")
  }
}
tiff(here("1_IGT_PP", "Figs_Tables", "Joint_ORL_Binomial", scale,
          paste("igt_", scale, "_orl_binomial_joint_indMu_posterior_distributions.tiff", sep = "")),
     width = 35, height = 25, units = "cm", res = 300)
  par(mfrow = c(4, 7))
  for(i in grep("mu", group_parameters, value = T)){
      plot(density(orl_posteriors[[i]]), main = i)
      abline(v = mean(orl_posteriors[[i]]))
  }
  for(i in 1:6){
      plot(density(orl_posteriors[["sigma"]][,i]), main = "sigma")
      abline(v = mean(orl_posteriors[["sigma"]][,i]))
  }
  for(i in 1:5){
    for(k in seq(i+1, 6)){
      plot(density(orl_posteriors[["R"]][,k,i]),
           main = paste(R_labs[k,i], "\nR = ", round(mean(orl_posteriors[["R"]][,k,i]), 2), sep = ""))
      abline(v = mean(orl_posteriors[["R"]][,k,i]))
    }
  }
dev.off()
```



# -------------------------------------------
# Correlation Table
```{r}
scales = c("prdep_tot", "masqGDA", "masqAA", "masqGDD", "bastot", "basdrive",
           "basrewres","panas_pa", "panas_na", "shaps_tot",
           "bis", "basfunsk")

correlations = data.frame()
for(sc in scales){
  
  posteriors = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "Joint_ORL_Binomial",
                            paste("igt_", sc, "_orl_binomial_joint_indMu_posteriors.rds", sep = "")))
  
  for(i in 1:5){
    for(k in seq(i+1, 6)){
      correlations = data.frame(scale = sc,
                                correlation = R_labs[k,i],
                                r = mean(posteriors[["R"]][,k,i]),
                                lower = HDIofMCMC(posteriors[["R"]][,k,i])[1],
                                upper = HDIofMCMC(posteriors[["R"]][,k,i])[2]) %>% 
        bind_rows(correlations)
    }
  }
}
View(filter(correlations, str_detect(correlation, "theta")), title = "thetas only")

write.csv(correlations, here("1_IGT_PP", "Figs_Tables", "Joint_ORL_Binomial",
                             "Joint_ORL_Binomial_correlations.csv"))

write.csv(filter(correlations, str_detect(correlation, "theta")),
          here("1_IGT_PP", "Figs_Tables", "Joint_ORL_Binomial",
               "Joint_ORL_Binomial_correlations_thetas_only.csv"))
```



# -------------------------------------------


```{r}
for(sc in scales){
  print(paste(sc, selfreport[[sc]]$M, sep = ": "))
}
```

















