---
title: "Fitting Ind-Mu ORL"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(wBoot)
library(haven)
library(foreach)
library(abind)
library(egg)
library(grid)
```



## Load Data
```{r}
stan_data <- readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "stan_ready_ORL_IGT.rds"))
```



# -------------------------------------------
# Fit Model
```{r, eval = F}
orl_model <- stan_model(here("1_IGT_PP", "Code", "Stan", "igt_orl_indMu.stan"))

# Fit model
orl_fit <- sampling(
  orl_model, 
  data = stan_data,
  iter = 5000,
  warmup = 1000,
  chains = 4,
  cores = 4,
  seed = 43210
)



#save the fitted model as an .rds file
saveRDS(orl_fit, here("1_IGT_PP", "Data", "2_Fitted", "ORL_indMu", "orl_pp_indMu_fit.rds"))
```



```{r}
orl_fit <- readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_indMu", "orl_pp_indMu_fit.rds"))

iterations = orl_fit@sim$chains * (orl_fit@sim$iter - orl_fit@sim$warmup)
```



# -------------------------------------------
# Model Diagnostics
```{r}
# orl_posteriors <- extract(orl_fit)
# saveRDS(orl_posteriors, here("1_IGT_PP", "Data", "2_Fitted", "ORL_indMu", "orl_pp_indMu_posteriors.rds"))
orl_posteriors = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_indMu", "orl_pp_indMu_posteriors.rds"))

focal_parameters <- c(
  "mu_Arew", "mu_Apun", "mu_K",
  "mu_betaF", "mu_betaP", 
  "sigma_Arew", "sigma_Apun", "sigma_K",
  "sigma_betaF", "sigma_betaP", 
  "Arew", "Apun",
  "K", "betaF", "betaP"
)

group_parameters <- grep("mu|sigma", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma", focal_parameters, value=TRUE, invert=TRUE)
```



## Rhat
```{r}
# rhats = rhat(orl_fit, pars = focal_parameters) %>%
#   data.frame() %>% mutate(parameter = rownames(.))

# saveRDS(rhats, here("1_IGT_PP", "Data", "2_Fitted", "ORL_indMu", "orl_pp_indMu_rhats.rds"))
rhats = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_indMu", "orl_pp_indMu_rhats.rds"))
```



## Traceplots
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "ORL_indMu",
          "orl_pp_indMu_group_traceplots.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  traceplot(
    orl_fit,
    pars = group_parameters
)
dev.off()


for(i in person_parameters){
  tiff(here("1_IGT_PP", "Figs_Tables", "ORL_indMu",
            paste("orl_pp_indMu_", i, "_traceplots.tiff", sep = "")),
       width = 35, height = 25, units = "cm", res = 300)
    traceplot(orl_fit,
              pars = i
              ) %>% print()
    dev.off()
}
```



# -------------------------------------------
# Inspect Parameters
## Means +/- PI
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "ORL_indMu",
          "orl_pp_indMu_posterior_means.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  plot(orl_fit, pars = group_parameters)
dev.off()
```



## Posterior Distributions
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "ORL_indMu",
          "orl_pp_indMu_posterior_distributions.tiff"),
     width = 35, height = 10, units = "cm", res = 300)
  par(mfrow = c(2, 5))
  for(i in group_parameters){
      plot(density(orl_posteriors[[i]]), main = i)
      abline(v = mean(orl_posteriors[[i]]))
  }
dev.off()
```



# -------------------------------------------
# Results
## Self-Report Correlations
```{r}
selfreport_models = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "binomial_selfreport_indMu_fits.rds"))
selfreport = readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "stan_ready_binomial_selfreport.rds"))
```



```{r}
# Check that orl and self-report IDs are in same order between data fed to models
for(scale in names(selfreport)){
  data.frame(orl_IDs = stan_data$subjIDs,
             selfreport_IDs = as.numeric(selfreport[[scale]]$IDs)) %>% 
    mutate(not_equal = ifelse(orl_IDs == selfreport_IDs, 0, 1)) %>% 
    reframe(ID_Check = ifelse(sum(not_equal) == 0, "EQUAL", "NOT EQUAL")) %>% 
    print()
}
```



```{r}
scales = c(# Session 1 only
           "prdep_tot", "masqGDA", "masqAA", "masqGDD",
           # "masqAD", # Removed
           # Both Sessions
           "bastot", "basdrive", "basfunsk", "basrewres",
           "bis", "panas_pa", "panas_na", "shaps_tot")


selfreport_posteriors = list()
sr_posterior_means = list()

for(scale in scales){
  selfreport_posteriors[[scale]] = extract(selfreport_models[[scale]], par = "theta")
  sr_posterior_means[[scale]] = apply(selfreport_posteriors[[scale]]$theta*selfreport[[scale]]$M, 2, mean)
}

orl_posterior_means = list()

for(parameter in person_parameters){
  orl_posterior_means[[parameter]] = apply(orl_posteriors[[parameter]], 2, mean)
}
```



```{r}
for(parameter in person_parameters){
  for(scale in scales){
    print(paste(parameter, " vs ", scale, ": r = ",
                round(cor(orl_posterior_means[[parameter]], sr_posterior_means[[scale]]), 2),
                sep = ""))
  }
}
```



## Relations to Behavior
### Calculate Choice Proportions
```{r}
choice = ifelse(stan_data$choice == 1, 1, ifelse(stan_data$choice == 2, 0, NA))

card_proportions = matrix(data = NA, nrow = 49, ncol = 4)
good_proportions = vector()

for(i in 1:49){
  good_proportions[i] = mean(choice[i,,][stan_data$card[i,,] == 3 | stan_data$card[i,,] == 4])
  for(c in 1:4){
    card_proportions[i,c] = mean(choice[i,,][stan_data$card[i,,] == c])
  }
}
```



### Correlations w/Card Proportions
```{r}
for(parameter in person_parameters){
  print(parameter)
  for(c in 1:4){
    card = ifelse(c == 1, "  Net = -750, Win Freq = 15, Lose Freq = 15",
                  ifelse(c == 2, "  Net = -750, Win Freq = 27, Lose Freq = 3",
                         ifelse(c == 3, "  Net = +600, Win Freq = 15, Lose Freq = 6",
                                "  Net = +750, Win Freq = 27, Lose Freq = 3")))
    print(paste(card, ": r = ",
                round(cor(orl_posterior_means[[parameter]], card_proportions[,c],
                          use = "pairwise.complete.obs"), 2),
                sep = ""))
  }
}
```



### Correlations w/Good Proportions
```{r}
for(parameter in person_parameters){
      print(paste("  ", parameter, " vs Proportion Good Cards: r = ",
                  round(cor(orl_posterior_means[[parameter]], good_proportions,
                            use = "pairwise.complete.obs"), 2),
                  sep = ""))
}
```



### Correlations w/Net Gain
```{r}
net_gains = apply(stan_data$outcome, 1, sum)

for(parameter in person_parameters){
  print(paste(parameter, " vs Net Gain: r = ",
              round(cor(orl_posterior_means[[parameter]], net_gains,
                        use = "pairwise.complete.obs"), 2),
              sep = ""))
}
```



# -------------------------------------------
# PPCs
## Prep Data
```{r}
# Card matrix
cards = stan_data$card
# Recode choice data
choices = ifelse(stan_data$choice == 2, 0, 1)
# Trial matrix (to skip when participant wasn't there)
trials = stan_data$Tsubj
# Extract parameters
model_parameters = extract(orl_fit)
predicted_values = ifelse(model_parameters$choice_pred == 2, 0, 1)
# For binding together posterior predictions
acomb = function(...) abind(..., along=3)
bcomb = function(...) abind(..., along=4)
```



```{r}
# Calculates group-level choice proportions into a 30 (trial) x 4 (card) x 2 (session) matrix
choice_proportions = foreach(s = 1:2, .combine = "acomb") %do% {
  foreach(c = 1:4, .combine = "cbind") %do% {
    temp = foreach(i = 1:49, .combine = "rbind") %do% {
        choices[i, cards[i, , s] == c, s]
    } %>% colMeans()
  }
}
```



```{r}
predicted_proportions = foreach(s = 1:2, .combine = "bcomb") %do% {
  foreach(c = 1:4, .combine = "acomb") %do% {
    foreach(i = 1:49, .combine = "acomb") %do% {
      if(trials[i, s] > 0){
        predicted_values[ , i, cards[i, , s] == c, s]
      }
    } %>% 
      apply(., c(1,2), mean)
  }
}
```



## Plotting
```{r}
# Set color scheme for bayesplot (it is a global setting)
color_scheme_set("viridisC")
```



```{r}
make_plot = function(y_data, yrep_data, top, right,
                     x_axis_txt, y_axis_txt, deck){
  if(top){
    custom_margin = margin(t = 1, r = -.5, b = -.5, l = -.5, unit = "lines")
  } else {
    custom_margin = margin(t = -.5, r = -.5, b = 1, l = -.5, unit = "lines")
  }
  if(right == 1 | right == 2){
    session_text = paste("Session", right)
  } else {
    session_text = ""
  }
  
  ppc_intervals(x = 1:length(y_data),
                y = y_data,
                yrep = yrep_data,
                prob = 0.50, 
                prob_outer = .80) +
    geom_text(aes(x = 30, y = .05, label = session_text),
              color = "black", hjust = 1, vjust = 0, check_overlap = T) +
    scale_x_continuous(expand = c(0, 0), limits = c(0, 31), breaks = seq(0, 30, 5)) +
    scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = seq(0, 1, .25)) +
    theme_classic() +
    labs(x = "Trial", y = "Proportion/Probability of Playing", title = deck) +
    theme(legend.position = "none",
          axis.title = element_blank(),
          axis.text.x = element_text(color = x_axis_txt, size = 12),
          axis.text.y = element_text(color = y_axis_txt, size = 12),
          plot.title = element_text(hjust = .5, size = 12),
          plot.margin = custom_margin,
          plot.background = element_rect(fill = "transparent", colour = "transparent"))
}
```



```{r}
plots = ggarrange(make_plot(choice_proportions[, 1, 1], predicted_proportions[,, 1, 1],
                            T, 0, "transparent", "black", "Deck A"),
                  make_plot(choice_proportions[, 2, 1], predicted_proportions[,, 2, 1],
                            T, 0, "transparent", "transparent", "Deck B"),
                  make_plot(choice_proportions[, 3, 1], predicted_proportions[,, 3, 1],
                            T, 0, "transparent", "transparent", "Deck C"),
                  make_plot(choice_proportions[, 4, 1], predicted_proportions[,, 4, 1],
                            T, 1, "transparent", "transparent", "Deck D"),
                  
                  make_plot(choice_proportions[, 1, 2], predicted_proportions[,, 1, 2],
                            F, 0, "black", "black", ""),
                  make_plot(choice_proportions[, 2, 2], predicted_proportions[,, 2, 2],
                            F, 0, "black", "transparent", ""),
                  make_plot(choice_proportions[, 3, 2], predicted_proportions[,, 3, 2],
                            F, 0, "black", "transparent", ""),
                  make_plot(choice_proportions[, 4, 2], predicted_proportions[,, 4, 2],
                            F, 2, "black", "transparent", ""),
                  nrow = 2, ncol = 4)
```



```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "ORL_indMu", "PPC.tiff"),
# tiff(here("1_IGT_PP", "Figs_Tables", "Joint", "PPC_indMu.tiff"),
     width = 25, height = 10, units = "cm", res = 300)

  grid.newpage()
  pushViewport(viewport(x = .5, y = .5, width = .9, height = .9))
  grid.draw(plots)
  popViewport()
  
  
  # x axis
  grid.text("Trial",
            x = .5125, y = .05,
            gp = gpar(fontsize = 16))
  # y axis
  grid.text("Proportion/Probability Play",
            x = .0225, y = .5,
            gp = gpar(fontsize = 16),
            rot = 90)
dev.off()
```
















