---
title: "Fitting Joint Test-Retest Binomial"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(wBoot)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
source(here("1_IGT_PP", "Code", "R", "3_other", "helpful_functions.R"))
```



## Load Data
```{r}
stan_data = readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "stan_ready_binomial_IGT.rds"))
```



# -------------------------------------------
# Check Model
```{r, eval = F}
model_code = cmdstan_model(here("1_IGT_PP", "Code", "Stan", 
                                "igt_binomial_joint.stan"), compile = F)

model_code$check_syntax(quiet = T)
```



# Fit Model
```{r, eval = F}
# Compile model
binomial_model = stan_model(here("1_IGT_PP", "Code", "Stan", "igt_binomial_joint.stan"))


# Fit model
binomial_fit = sampling(binomial_model, 
                        data   = stan_data, 
                        iter   = 5000, 
                        warmup = 1000, 
                        chains = 4, 
                        cores  = 4,
                        seed   = 43210)


#save the fitted model as an .rds file
saveRDS(binomial_fit, here("1_IGT_PP", "Data", "2_Fitted",
                           "Binomial_Joint",
                           "binomial_joint_fit.rds"))
```



```{r}
binomial_fit = readRDS(here("1_IGT_PP", "Data", "2_Fitted",
                            "Binomial_Joint",
                            "binomial_joint_fit.rds"))

iterations = binomial_fit@sim$chains * (binomial_fit@sim$iter - binomial_fit@sim$warmup)
```



# -------------------------------------------
# Model Diagnostics
```{r}
binomial_posteriors <- extract(binomial_fit)
saveRDS(binomial_posteriors, here("1_IGT_PP", "Data", "2_Fitted",
                                  "Binomial_Joint",
                                  "binomial_joint_posteriors.rds"))
```



```{r}
binomial_posteriors = readRDS(here("1_IGT_PP", "Data", "2_Fitted",
                                   "Binomial_Joint",
                                   "binomial_joint_posteriors.rds"))


focal_parameters <- c(
  "mu_good_p", "mu_bad_p", "pl_good_p", "pl_bad_p",
  "sigma_good", "sigma_bad",
  "R_good[1,2]", "R_bad[1,2]")

group_parameters <- grep("mu|sigma|R_", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma|R_", focal_parameters, value=TRUE, invert=TRUE)
```



## Rhat
```{r, eval = T}
rhats = rhat(binomial_fit, pars = focal_parameters) %>%
  data.frame() %>% mutate(parameter = rownames(.))
saveRDS(rhats, here("1_IGT_PP", "Data", "2_Fitted", "Binomial_Joint",
                    "binomial_joint_rhats.rds"))
```



```{r, eval = T}
rhats = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "Binomial_Joint",
                     "binomial_joint_rhats.rds"))
```



## Traceplots
```{r, eval = T}
tiff(here("1_IGT_PP", "Figs_Tables", "Binomial_Joint",
          "binomial_joint_group_traceplots.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  traceplot(
    binomial_fit,
    pars = group_parameters
)
dev.off()


for(i in person_parameters){
  tiff(here("1_IGT_PP", "Figs_Tables", "Binomial_Joint",
            paste("binomial_joint_", i, "_traceplots.tiff", sep = "")),
       width = 35, height = 25, units = "cm", res = 300)
    traceplot(binomial_fit,
              pars = i
              ) %>% print()
    dev.off()
}
```



# -------------------------------------------
# Inspect Parameters
## Means +/- PI
```{r, eval = T}
tiff(here("1_IGT_PP", "Figs_Tables", "Binomial_Joint",
          "binomial_joint_posterior_means.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  plot(binomial_fit, pars = group_parameters)
dev.off()
```



## Posterior Distributions
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "Binomial_Joint",
          "binomial_joint_posterior_distributions.tiff"),
     width = 30, height = 20, units = "cm", res = 300)
  par(mfrow = c(5, 5))
  # Mus & Sigmas
  for(s in 1:2){
    for(i in grep("mu|sigma", group_parameters, value = T)){
      plot(density(binomial_posteriors[[i]][,s]), main = paste(i, s))
      abline(v = mean(binomial_posteriors[[i]][,s]))
    }
  }
  
  for(i in grep("R_", group_parameters, value = T)){
    plot(density(binomial_posteriors[[str_remove(i, "\\[1,2\\]")]][,2,1]), main = i)
    abline(v = mean(binomial_posteriors[[i]][,2,1]))
  }
dev.off()
```


```{r}
mean(binomial_posteriors$R_good[,2,1])
mean(binomial_posteriors$R_bad[,2,1])
```




