---
title: "Fitting Joint Test-Retest ORL"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(wBoot)
```



## Load Data
```{r}
stan_data = readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "stan_ready_ORL_IGT.rds"))
```



# -------------------------------------------
# Fit Model
```{r, eval = F}
# Compile model
orl_model = stan_model(here("1_IGT_PP", "Code", "Stan", "igt_orl_joint.stan"))


# Fit model
orl_fit = sampling(orl_model, 
                   data   = stan_data, 
                   iter   = 5000, 
                   warmup = 1000, 
                   chains = 4, 
                   cores  = 4,
                   seed   = 43210)


#save the fitted model as an .rds file
saveRDS(orl_fit, here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint", "orl_pp_joint_fit.rds"))
```



```{r}
orl_fit = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint", "orl_pp_joint_fit.rds"))

iterations = orl_fit@sim$chains * (orl_fit@sim$iter - orl_fit@sim$warmup)
```



# -------------------------------------------
# Model Diagnostics
```{r}
# orl_posteriors <- extract(orl_fit)
# saveRDS(orl_posteriors, here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint", "orl_pp_joint_posteriors.rds"))
orl_posteriors = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint", "orl_pp_joint_posteriors.rds"))


focal_parameters <- c(
  "mu_Arew", "mu_Apun", "mu_K", "mu_betaF", "mu_betaP", 
  "sigma_Arew", "sigma_Apun", "sigma_K", "sigma_betaF", "sigma_betaP", 
  "Arew", "Apun", "K", "betaF", "betaP",
  "R_Arew[1,2]", "R_Apun[1,2]", "R_K[1,2]", "R_betaF[1,2]", "R_betaP[1,2]"
)

group_parameters <- grep("mu|sigma|R_", focal_parameters, value=TRUE)
person_parameters <- grep("mu|sigma|R_", focal_parameters, value=TRUE, invert=TRUE)
```



## Rhat
```{r, eval = F}
# rhats = rhat(orl_fit, pars = focal_parameters) %>% 
#   data.frame() %>% mutate(parameter = rownames(.))

# saveRDS(rhats, here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint", "orl_pp_joint_rhats.rds"))
rhats = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint", "orl_pp_joint_rhats.rds"))
```



## Traceplots
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "ORL_Joint",
          "orl_pp_joint_group_traceplots.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  traceplot(
    orl_fit,
    pars = group_parameters
)
dev.off()


for(i in person_parameters){
  tiff(here("1_IGT_PP", "Figs_Tables", "ORL_Joint",
            paste("orl_pp_joint_", i, "_traceplots.tiff", sep = "")),
       width = 35, height = 25, units = "cm", res = 300)
    traceplot(orl_fit,
              pars = i
              ) %>% print()
    dev.off()
}
```



# -------------------------------------------
# Inspect Parameters
## Means +/- PI
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "ORL_Joint",
          "orl_pp_joint_posterior_means.tiff"),
     width = 35, height = 25, units = "cm", res = 300)
  plot(orl_fit, pars = group_parameters)
dev.off()
```



## Posterior Distributions
```{r}
tiff(here("1_IGT_PP", "Figs_Tables", "ORL_Joint", "orl_pp_joint_posterior_distributions.tiff"),
     width = 30, height = 20, units = "cm", res = 300)
  par(mfrow = c(5, 5))
  # Mus & Sigmas
  for(s in 1:2){
    for(i in grep("mu|sigma", group_parameters, value = T)){
      plot(density(orl_posteriors[[i]][,s]), main = paste(i, s))
      abline(v = mean(orl_posteriors[[i]][,s]))
    }
  }
  
  for(i in grep("R_", group_parameters, value = T)){
    plot(density(orl_posteriors[[str_remove(i, "\\[1,2\\]")]][,2,1]), main = i)
    abline(v = mean(orl_posteriors[[i]][,2,1]))
  }
dev.off()
```



# -------------------------------------------
# Results
## Self-Report Correlations
```{r}
selfreport_models = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "binomial_selfreport_indMu_fits.rds"))
selfreport = readRDS(here("1_IGT_PP", "Data", "1_Preprocessed", "stan_ready_binomial_selfreport.rds"))
```



```{r}
# Check that orl and self-report IDs are in same order between data fed to models
for(scale in names(selfreport)){
  data.frame(orl_IDs = stan_data$subjIDs,
             selfreport_IDs = as.numeric(selfreport[[scale]]$IDs)) %>% 
    mutate(not_equal = ifelse(orl_IDs == selfreport_IDs, 0, 1)) %>% 
    reframe(ID_Check = ifelse(sum(not_equal) == 0, "EQUAL", "NOT EQUAL")) %>% 
    print()
}
```



```{r}
scales = c(# Session 1 only
           "prdep_tot", "masqGDA", "masqAA", "masqGDD",
           # "masqAD", # Removed
           # Both Sessions
           "bastot", "basdrive", "basfunsk", "basrewres",
           "bis", "panas_pa", "panas_na", "shaps_tot")


selfreport_posteriors = list()
sr_posterior_means = list()

for(scale in scales){
  dimensions = c(2,3)
  if(length(dim(selfreport_posteriors[[scale]]$theta)) == 2) dimensions = 2
  
  selfreport_posteriors[[scale]] = extract(selfreport_models[[scale]], par = "theta")
  sr_posterior_means[[scale]] = apply(selfreport_posteriors[[scale]]$theta*selfreport[[scale]]$M, 2, mean)
}

overall_orl_posterior_means = list()

for(parameter in person_parameters){
  overall_orl_posterior_means[[parameter]] = apply(orl_posteriors[[parameter]], 2, mean)
}


session_orl_posterior_means = list()

for(parameter in person_parameters){
  session_orl_posterior_means[[parameter]] = apply(orl_posteriors[[parameter]], c(2,3), mean)
}
```




```{r}
correlations = data.frame()

for(parameter in person_parameters){
  for(scale in scales){
    for(s in 1:ncol(selfreport[[scale]]$score)){
        
      orl = session_orl_posterior_means[[parameter]][,s][selfreport[[scale]]$score[,s] != -999]
      sr = selfreport[[scale]]$score[,s][selfreport[[scale]]$score[,s] != -999]
      
        correlation = boot.cor.bca(x = orl,
                                   y = sr,
                                   null.hyp = NULL,
                                   alternative = c("two.sided", "less", "greater"),
                                   conf.level = 0.95, type = NULL, R = 9999)
        
        correlations = data.frame(parameter = parameter,
                                  scale = scale,
                                  type = "sum-score",
                                  session = s,
                                  r = correlation$Observed,
                                  CI = correlation$Confidence.interval) %>%
          bind_rows(correlations)
    }
  }
}
correlations %>% 
  separate(col = "CI", into = c("lower", "upper"), sep = ",") %>% 
  mutate(lower = as.numeric(str_remove(lower, "\\(")), upper = as.numeric(str_remove(upper, "\\)"))) %>% 
  write.csv(here("1_IGT_PP", "Figs_Tables", "ORL_Joint", "session_orl_sr_correlations.csv"))

# correlations = data.frame()
# 
# for(parameter in person_parameters){
#   for(scale in scales){
#     for(s in 1:ncol(matrix(sr_posterior_means[[scale]]))){
#         
#         correlation = boot.cor.bca(x = orl_posterior_means[[parameter]][,s],
#                                    y = matrix(sr_posterior_means[[scale]])[,s],
#                                    null.hyp = NULL,
#                                    alternative = c("two.sided", "less", "greater"),
#                                    conf.level = 0.95, type = NULL, R = 9999)
#         
#         correlations = data.frame(parameter = parameter,
#                                   scale = scale,
#                                   type = "predicted score",
#                                   session = s,
#                                   r = correlation$Observed,
#                                   CI = correlation$Confidence.interval) %>%
#           bind_rows(correlations)
#     }
#   }
# }
# write.csv(correlations, here("1_IGT_PP", "Figs_Tables", "ORL_Joint", "overall_orl_sr_correlations.csv"))
```



```{r}
session_correlations = data.frame()

for(parameter in person_parameters){
  for(scale in scales){
    for(s in 1:ncol(selfreport[[scale]]$score)){
        
        correlation = boot.cor.bca(x = orl_posterior_means[[parameter]][,s],
                                   y = selfreport[[scale]]$score[,s],
                                   null.hyp = NULL,
                                   alternative = c("two.sided", "less", "greater"),
                                   conf.level = 0.95, type = NULL, R = 9999)
        
        session_correlations = data.frame(parameter = parameter,
                                          scale = scale,
                                          type = "sum-score",
                                          session = s,
                                          r = correlation$Observed,
                                          CI = correlation$Confidence.interval) %>%
          bind_rows(session_correlations)
    }
  }
}
```



## Relations to Behavior
### Calculate Choice Proportions
```{r}
choice = ifelse(stan_data$choice == 1, 1, ifelse(stan_data$choice == 2, 0, NA))

card_proportions = array(data = NA, dim = c(49, 4, 2))
good_proportions = matrix(data = NA, nrow = 49, ncol = 2)
play_proportions = matrix(data = NA, nrow = 49, ncol = 2)

for(i in 1:49){
  for(s in 1:2){
    good_proportions[i,s] = mean(choice[i,,s][stan_data$card[i,,s] == 3 | stan_data$card[i,,s] == 4], na.rm = T)
    play_proportions[i,s] = mean(choice[i,,s] == 1, na.rm = T)
    for(c in 1:4){
      card_proportions[i,c,s] = mean(choice[i,,s][stan_data$card[i,,s] == c], na.rm = T)
    }
  }
}
```



### Correlations w/Card Proportions
```{r}
for(s in 1:2){
  print(paste("Session", s))
  for(parameter in person_parameters){
    print(paste(" ", parameter))
    for(c in 1:4){
      card = ifelse(c == 1, "    Net = -750, Win Freq = 15, Lose Freq = 15",
                    ifelse(c == 2, "    Net = -750, Win Freq = 27, Lose Freq = 3",
                           ifelse(c == 3, "    Net = +600, Win Freq = 15, Lose Freq = 6",
                                  "    Net = +750, Win Freq = 27, Lose Freq = 3")))
      print(paste(card, ": r = ",
                  round(cor(session_orl_posterior_means[[parameter]][,s], card_proportions[,c,s],
                            use = "pairwise.complete.obs"), 2),
                  sep = ""))
    }
  }
}
```



### Correlations w/Good Proportions
```{r}
for(s in 1:2){
  print(paste("Session", s))
  for(parameter in person_parameters){
      print(paste("  ", parameter, " vs Proportion Good Cards: r = ",
                  round(cor(session_orl_posterior_means[[parameter]][,s], good_proportions[,s],
                            use = "pairwise.complete.obs"), 2),
                  sep = ""))
  }
}
```



### Correlations w/Play Proportions
```{r}
for(s in 1:2){
  print(paste("Session", s))
  for(parameter in person_parameters){
      print(paste("  ", parameter, " vs Proportion Played: r = ",
                  round(cor(session_orl_posterior_means[[parameter]][,s], abs(play_proportions[,s]-.5),
                            use = "pairwise.complete.obs"), 2),
                  sep = ""))
  }
}
```



### Correlations w/Net Gain
```{r}
net_gains = apply(stan_data$outcome, c(1,3), sum)

for(s in 1:2){
  print(paste("Session", s))
  for(parameter in person_parameters){
      print(paste("  ", parameter, " vs Net Gain: r = ",
                  round(cor(session_orl_posterior_means[[parameter]][,s], net_gains[,s],
                            use = "pairwise.complete.obs"), 2),
                  sep = ""))
  }
}
print("Change in Gain")
for(parameter in person_parameters){
    print(paste("  ", parameter, " vs Delta Net Gain: r = ",
                round(cor(apply(orl_posteriors[[parameter]], 2, mean), (net_gains[,2]-net_gains[,1]),
                          use = "pairwise.complete.obs"), 2),
                sep = ""))
}
```



# -------------------------------------------



















