---
title: "Model-Comparison"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(loo)
```



# -------------------------------------------
# IGT
```{r}
orl_joint_fit = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint",
                             "orl_pp_joint_fit.rds"))
# orl_joint_playfic_fit = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint_playupdate",
#                                      "orl_pp_joint_playupdate_fit.rds"))
orl_joint_playfic_playupdate_modifiedK_fit = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint_playfic_playupdate_modifiedK",
                                                          "orl_pp_joint_playfic_playupdate_modifiedK_fit.rds"))
orl_updatedfic_fit = readRDS(here("1_IGT_PP", "Data", "2_Fitted", "ORL_Joint_updatedfic",
                                  "orl_pp_joint_updatedfic_fit.rds"))
```



```{r}
log_lik_orl_joint_fit = extract_log_lik(orl_joint_fit)
# log_lik_orl_joint_playupdate = extract_log_lik(orl_joint_playupdate_fit)
log_lik_orl_joint_playfic_playupdate_modifiedK = extract_log_lik(orl_joint_playfic_playupdate_modifiedK_fit)
log_lik_orl_updatedfic_fit = extract_log_lik(orl_updatedfic_fit)
```



```{r}
loo_orl_joint = loo(log_lik_orl_joint_fit)
# loo_orl_orl_joint_playupdate = loo(log_lik_orl_joint_playupdate)
loo_orl_joint_playfic_playupdate_modifiedK = loo(log_lik_orl_joint_playfic_playupdate_modifiedK)
loo_orl_updatedfic = loo(log_lik_orl_updatedfic_fit)
```



```{r}
comparison = loo_compare(list("Joint" = loo_orl_joint,
                              # "Joint Playupdate" = loo_orl_orl_joint_playupdate,
                              "Joint Playfic Playupdate Modified K" = loo_orl_joint_playfic_playupdate_modifiedK,
                              "Updated Fic" = loo_orl_updatedfic
                              ))

print(comparison)
```

# -------------------------------------------
```{r}

```



















