---
title: "Fitting Joint ORL"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(wBoot)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
source(here("1_IGT_PP", "Code", "R", "3_other", "helpful_functions.R"))
library(MASS)
```



## Load Outcomes & Sim Type
```{r}
outcomes = readRDS(here("Simulations","outcomes.RDS"))
sim_type = "TR_Joint_ORL_Bias"
parameter_names = c("Arew", "Apun", "betaF", "betaB")
```



## Functions
```{r, eval = F}
#------------------------------------------------------------------------------
# USE SOFTMAX TO OBTAIN CHOICE PROBABILITIES - USED IN SIMULATIONS
softmax = function(values){
  return(exp(values) / sum(exp(values)))
}


#------------------------------------------------------------------------------
# SIMULATION FUNCTION
simulate_orl = function(parameter_values, N, custom_seed = 20230928) {
  set.seed(seed = custom_seed)
  data = data.frame()
  
  for(s in 1:2){
    for(i in 1:N){
      # parameters for sim
      Arew = filter(parameter_values,
                    parameter == "Arew" & session == s & ID == i)$estimate
      Apun = filter(parameter_values,
                    parameter == "Apun" & session == s & ID == i)$estimate
      betaF = filter(parameter_values,
                     parameter == "betaF" & session == s & ID == i)$estimate
      betaB = filter(parameter_values,
                     parameter == "betaB" & session == s & ID == i)$estimate
      missing = filter(parameter_values,
                       parameter == "Arew" & session == s & ID == i)$missing
      
      utility = rep(0,4)
      ev = rep(0,4)
      ef = rep(0,4)
      
      ef_chosen = 0
      PEval = 0
      PEfreq = 0
      PEfreq_fic = rep(0,4)
      card_trial = rep(0,4)
      
      for(t in 1:120){
        outcome = outcomes$outcome[outcomes$trial == t]
        sign = outcomes$sign[outcomes$trial == t]
        card = outcomes$card[outcomes$trial == t]
        
        utility = ev + ef * betaF + betaB
        prob = softmax(c(utility[card], 0))
        curr_choice = sample(c(1,2), 1, prob = prob)
        
        if(curr_choice==1) {
          PEval = outcome - ev[card]
          PEfreq = sign - ef[card] # ON MAR 4, 2024, JEREMY FIXED THIS FROM "-1*sign - ef[card]" TO "sign - ef[card]"
          PEfreq_fic = -1*sign/3 - ef
          ef_chosen = ef[card]
          
          if(outcome >= 0) {
            ef = ef + Apun * PEfreq_fic
            ef[card] = ef_chosen + Arew * PEfreq
            ev[card] = ev[card] + Arew * PEval
          } else {
            ef = ef + Arew * PEfreq_fic
            ef[card] = ef_chosen + Apun * PEfreq
            ev[card] = ev[card] + Apun * PEval
          }
        }
        
        card_trial[card] = card_trial[card] + 1
        if(missing){
          outcome = choice = -1
        }
        data = data.frame(ID = i,
                          missing = ifelse(s == 2, missing, F),
                          session = s,
                          card = card,
                          trial = t,
                          outcome = outcome,
                          sign = sign,
                          card_trial = card_trial[card],
                          choice = curr_choice) %>% 
          bind_rows(data)
      }
    }
  }
  data %>%
    return()
}
```



# -------------------------------------------
# Set Parameter Values
## Load Posteriors
```{r, eval = F}
TR_orl_posteriors = readRDS(here("1_IGT_PP", "Data", "2_Fitted", 
                                 "Joint_ORL_Bias", "Joint_ORL_Bias_posteriors.rds"))
```



## Set Mus
```{r, eval = F}
mu_p = apply(TR_orl_posteriors$mu_p, c(2, 3), mean) # Untransformed
colnames(mu_p) = parameter_names

vcovs = list() # covariance matrix for simulation
group_parameters = data.frame()

for(p in 1:4){
  # setup covariance matrix
  R = apply(TR_orl_posteriors[[paste0("R_", parameter_names[p])]], c(2, 3), mean)
  SD = diag(apply(TR_orl_posteriors[[paste0("sigma_", parameter_names[p])]], 2, mean))
  vcovs[[parameter_names[p]]] = SD%*%R%*%SD
  
  # setup means
  group_parameters = data.frame(parameter = parameter_names[p],
                                session1_mu = mean(TR_orl_posteriors$mu_p[,1,p]),
                                session2_mu = mean(TR_orl_posteriors$mu_p[,2,p]),
                                session1_lower = HDIofMCMC(TR_orl_posteriors$mu_p[,1,p])[1],
                                session1_upper = HDIofMCMC(TR_orl_posteriors$mu_p[,1,p])[2],
                                session2_lower = HDIofMCMC(TR_orl_posteriors$mu_p[,2,p])[1],
                                session2_upper = HDIofMCMC(TR_orl_posteriors$mu_p[,2,p])[2],
                                R_mu = R[1,2],
                                R_lower = HDIofMCMC(TR_orl_posteriors[[paste0("R_", parameter_names[p])]][,2,1])[1],
                                R_upper = HDIofMCMC(TR_orl_posteriors[[paste0("R_", parameter_names[p])]][,2,1])[2]) %>%
    bind_rows(group_parameters)
  
}
saveRDS(group_parameters, here("Parameter Recovery", 
                               paste0(sim_type, "_sim_group_parameters.RDS")))
```



## Simulate Parameters
```{r, eval = F}
set.seed(20240227)
N = 49
N_missing = 10
missingness = sample(c(rep(F, N-N_missing), # codes present participants
                   rep(T, N_missing)),  # codes missing participants
                 replace = F)

parameters = list(ID = 1:49,
                  missing = missingness)
for(p in parameter_names){
  parameters[[p]] = mvrnorm(N, mu = mu_p[, p], Sigma = vcovs[[p]])
  if(p %in% c("Arew", "Apun")){
    parameters[[paste0(p, "_UT")]] = parameters[[p]]
    parameters[[p]] = pnorm(parameters[[p]])
  }
}
saveRDS(parameters, here("Parameter Recovery", 
                         paste0(sim_type, "_sim_parameters.RDS")))
parameter_values = data.frame(parameters) %>% 
  cbind(data.frame(ID = 1:N, missing = missingness)) %>% 
  pivot_longer(ends_with(c(".1", ".2")), names_to = c("parameter", "session"),
               values_to = "estimate", names_sep = "\\.") %>% 
  mutate(missing = case_when(session == 1 ~ F, T ~ missing))
```



# -------------------------------------------
# Simulation
## Simulate Data
```{r, eval = F}
sim_data = simulate_orl(parameter_values, N, custom_seed = 20240304)

saveRDS(sim_data, here("Parameter Recovery", 
                       paste0(sim_type, "_sim_data.RDS")))
```



```{r}
sim_data = readRDS(here("Parameter Recovery", 
                        paste0(sim_type, "_sim_data.RDS")))
```




## Prep Stan Data
```{r, eval = F}
IDs = unique(sim_data$ID)
N = length(IDs)
Trials = max(sim_data$trial)
S = length(unique(sim_data$session))

Tsubj = array(120, c(N, S))
choice = card = outcome = sign = array(-1, c(N, Trials, S))

for(i in 1:N){
  for(s in 1:S){
    if(missingness[i] & s == 2){
      Tsubj[i,s] = 0
    }
    
    if(Tsubj[i,s] > 0){
      temp_data = sim_data %>% 
        filter(ID == i, session == s) %>% 
        arrange(trial)
      choice[i,,s] = temp_data$choice
      card[i,,s] = temp_data$card
      outcome[i,,s] = temp_data$outcome
      sign[i,,s] = temp_data$sign
    }
  }
}
stan_data = list(
  N = N,
  T = Trials,
  S = S,
  subjIDs = IDs,
  Tsubj = Tsubj,
  choice = choice,
  card = card,
  outcome = outcome,
  sign = sign
)
```



# -------------------------------------------
# Fit Model
```{r, eval = F}
# Compile model
orl_model = stan_model(here("1_IGT_PP", "Code", "Stan", "Joint_ORL_Bias.stan"))


# Fit model
sim_orl_fit = sampling(orl_model,
                       data   = stan_data, 
                       iter   = 2000, 
                       warmup = 1000, 
                       chains = 4, 
                       cores  = 4,
                       seed   = 43210,
                       save_warmup = F)


#save the fitted model as an .rds file
saveRDS(sim_orl_fit, here("Parameter Recovery",
                          paste0(sim_type, "_sim_fit.RDS")))
```



```{r}
sim_orl_fit = readRDS(here("Parameter Recovery",
                           paste0(sim_type, "_sim_fit.RDS")))
```



```{r, eval = F}
sim_orl_posteriors <- extract(sim_orl_fit)
saveRDS(sim_orl_posteriors,
        here("Parameter Recovery",
             paste0(sim_type, "_sim_posteriors.RDS")))
```



```{r}
sim_orl_posteriors =
  readRDS(here("Parameter Recovery",
               paste0(sim_type, "_sim_posteriors.RDS")))
```



# -------------------------------------------
# Group-Level Parameters
## Prep Data
```{r}
group_parameters = readRDS(here("Parameter Recovery", 
                                paste0(sim_type, "_sim_group_parameters.RDS")))


for(p in 1:4){
  group_parameters = data.frame(parameter = paste0("sim_", parameter_names[p]),
                                session1_mu = mean(sim_orl_posteriors$mu_p[,1,p]),
                                session2_mu = mean(sim_orl_posteriors$mu_p[,2,p]),
                                session1_lower = HDIofMCMC(sim_orl_posteriors$mu_p[,1,p])[1],
                                session1_upper = HDIofMCMC(sim_orl_posteriors$mu_p[,1,p])[2],
                                session2_lower = HDIofMCMC(sim_orl_posteriors$mu_p[,2,p])[1],
                                session2_upper = HDIofMCMC(sim_orl_posteriors$mu_p[,2,p])[2],
                                R_mu = mean(sim_orl_posteriors[[paste0("R_", parameter_names[p])]][,2,1]),
                                R_lower = HDIofMCMC(sim_orl_posteriors[[paste0("R_", parameter_names[p])]][,2,1])[1],
                                R_upper = HDIofMCMC(sim_orl_posteriors[[paste0("R_", parameter_names[p])]][,2,1])[2]) %>%
    bind_rows(group_parameters)
}
```



## Plot Posterior Means
```{r}
mus = list()
for(p in 1:4){
  mus[[parameter_names[p]]] = group_parameters %>% 
    dplyr::select(-starts_with("R")) %>%
    filter(str_detect(parameter, parameter_names[p])) %>% 
    pivot_longer(c(everything(), -parameter), names_to = c("session", "type"), names_sep = "_",
                 values_to = "estimate") %>% 
    pivot_wider(names_from = "type", values_from = "estimate") %>% 
    mutate(parameter = case_when(str_detect(parameter, "sim") ~ "sim", T ~ "actual"),
           parameter = factor(parameter, levels = c("actual", "sim"), ordered = T)) %>% 
    ggplot(aes(x = mu, y = parameter)) +
      geom_point() +
      geom_errorbar(aes(xmin = lower, xmax = upper)) +
      labs(x = "Mu Estimate", y = parameter_names[p]) +
      theme_classic() +
      facet_rep_grid(.~session)
  
  mus[[paste0("R_", parameter_names[p])]] = group_parameters %>% 
    dplyr::select(parameter, starts_with("R")) %>%
    filter(str_detect(parameter, parameter_names[p])) %>% 
    mutate(parameter = case_when(str_detect(parameter, "sim") ~ "sim", T ~ "actual"),
           parameter = factor(parameter, levels = c("actual", "sim"), ordered = T)) %>% 
    ggplot(aes(x = R_mu, y = parameter)) +
      geom_point() +
      geom_errorbar(aes(xmin = R_lower, xmax = R_upper)) +
      scale_x_continuous(limits = c(-1, 1)) +
      labs(x = "R Estimate", y = parameter_names[p]) +
      theme_classic()
}

tiff(here("Parameter Recovery",
          paste0(sim_type, "_group_mus.tiff")),
     width = 15, height = 16, units = "cm", res = 300)

  egg::ggarrange(mus$Arew, mus$R_Arew, 
                 mus$Apun, mus$R_Apun, 
                 mus$betaF, mus$R_betaF, 
                 mus$betaB, mus$R_betaB,
                 nrow = 4, widths = c(2, 1))

dev.off()
```



# -------------------------------------------
# Person-Level Parameters
## Prep Data
```{r}
recovered_parameters =
  data.frame(Arew_UT.1 = sim_orl_posteriors$mu_p[,1,1] +
                         sim_orl_posteriors$Arew_tilde[,1,],
             Arew_UT.2 = sim_orl_posteriors$mu_p[,2,1] +
                         sim_orl_posteriors$Arew_tilde[,2,],
             Apun_UT.1 = sim_orl_posteriors$mu_p[,1,2] +
                         sim_orl_posteriors$Apun_tilde[,1,],
             Apun_UT.2 = sim_orl_posteriors$mu_p[,2,2] +
                         sim_orl_posteriors$Apun_tilde[,2,],
             betaF.1 = sim_orl_posteriors$mu_p[,1,3] +
                       sim_orl_posteriors$betaF_tilde[,1,],
             betaF.2 = sim_orl_posteriors$mu_p[,2,3] +
                       sim_orl_posteriors$betaF_tilde[,2,],
             betaB.1 = sim_orl_posteriors$mu_p[,1,4] +
                       sim_orl_posteriors$betaB_tilde[,1,],
             betaB.2 = sim_orl_posteriors$mu_p[,2,4] +
                       sim_orl_posteriors$betaB_tilde[,2,]) %>% 
  pivot_longer(everything(),
               names_to = c("parameter", "session", "ID"),
               values_to = "recovered",
               names_sep = "\\.", names_transform = list(ID = as.numeric)) %>% 
  group_by(parameter, session, ID) %>% 
  summarise(recovered = mean(recovered))


actual_parameters = data.frame(readRDS(here("Parameter Recovery", 
                                            paste0(sim_type, "_sim_parameters.RDS")))) %>%
  pivot_longer(c(everything(), -ID, -missing), 
               names_to = c("parameter", "session"), values_to = "actual",
               names_sep = "\\.") %>% 
  filter(!(parameter %in% c("Arew", "Apun"))) %>% 
  mutate(missing = case_when(session == 1 ~ F, T ~ missing))

combined_parameters = left_join(recovered_parameters, actual_parameters)
```



## Run Correlations
```{r}
PR_correlations = data.frame()

for(p in c("Arew_UT", "Apun_UT", "betaF", "betaB")){
  for(s in 1:2){
    cur_cor = cor.test(~actual + recovered,
                       data = filter(combined_parameters,
                                     !missing,
                                     parameter == p,
                                     session == s))
    PR_correlations = data.frame(parameter = p,
                                 session = s,
                                 r = cur_cor$estimate,
                                 p = cur_cor$p.value,
                                 sig = ifelse(cur_cor$p.value < .05, "*", ""),
                                 lower = cur_cor$conf.int[1],
                                 upper = cur_cor$conf.int[2]) %>% 
      bind_rows(PR_correlations)
  }
}
```



## Plot Parameter Recovery Correlations
```{r}
tiff(here("Parameter Recovery",
          paste0(sim_type, "_PR_correlations.tiff")),
     width = 10, height = 16, units = "cm", res = 300)
  combined_parameters %>% 
    filter(!missing) %>%
    group_by(session, parameter) %>% 
    mutate(z_actual = (actual - mean(actual)) / sd(actual),
           z_recovered = (recovered - mean(recovered)) / sd(recovered)) %>% 
    ggplot(aes(x = z_actual, y = z_recovered)) +
      geom_text_npc(data = PR_correlations, aes(npcx = "left", npcy = "top",
                                                label = paste("r =", round(r, 2)))) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      theme_classic() +
      labs(x = "Actual", y = "Recovered",
           caption = "X- and Y-axis values are z-scored") +
      facet_rep_grid(parameter~session)
dev.off()
```

















