---
title: "Fitting Joint ORL"
output: html_document
date: "2023-03-07"
---



# -------------------------------------------
# Setup
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(hBayesDM)
library(bayesplot)
library(here)
library(miscTools)
library(wBoot)
library(cmdstanr)
library(stringi)
library(ggpp)
library(lemon)
source(here("1_IGT_PP", "Code", "R", "3_other", "helpful_functions.R"))
library(MASS)
```



## Load Outcomes & Sim Type
```{r, eval = T}
outcomes = readRDS(here("Simulations","outcomes.RDS"))
sim_type = "TR"
```



## Functions
```{r, eval = T}
#------------------------------------------------------------------------------
# USE SOFTMAX TO OBTAIN CHOICE PROBABILITIES - USED IN SIMULATIONS
softmax = function(values){
  return(exp(values) / sum(exp(values)))
}


#------------------------------------------------------------------------------
# SIMULATION FUNCTION
simulate_orl = function(parameter_values, N, custom_seed = 20230928) {
  set.seed(seed = custom_seed)
  data = data.frame()
  
  for(s in 1:2){
    for(i in 1:N){
      # parameters for sim
      Arew = filter(parameter_values,
                    parameter == "Arew" & session == s & ID == i)$estimate
      Apun = filter(parameter_values,
                    parameter == "Apun" & session == s & ID == i)$estimate
      K = filter(parameter_values,
                 parameter == "K" & session == s & ID == i)$estimate
      betaF = filter(parameter_values,
                     parameter == "betaF" & session == s & ID == i)$estimate
      betaP = filter(parameter_values,
                     parameter == "betaP" & session == s & ID == i)$estimate
      missing = filter(parameter_values,
                       parameter == "Arew" & session == s & ID == i)$missing
      
      utility = rep(0,4)
      ev = rep(0,4)
      ef = rep(0,4)
      pers = rep(0,4)
      K_tr = 3^(K)-1
      
      ef_chosen = 0
      PEval = 0
      PEfreq = 0
      PEfreq_fic = rep(0,4)
      card_trial = rep(0,4)
      
      for(t in 1:120){
        outcome = outcomes$outcome[outcomes$trial == t]
        sign = outcomes$sign[outcomes$trial == t]
        card = outcomes$card[outcomes$trial == t]
        prob = softmax(c(utility[card], 0))
        curr_choice = sample(c(1,2), 1, prob = prob)
        
        if(curr_choice==1) {
          PEval = outcome - ev[card]
          PEfreq= -1*sign - ef[card]
          PEfreq_fic = -1*sign/3 - ef;
          ef_chosen = ef[card];
          
          if(outcome >= 0) {
            ef = ef + Apun * PEfreq_fic
            ef[card] = ef_chosen + Arew * PEfreq
            ev[card] = ev[card] + Arew * PEval
          } else {
            ef = ef + Arew * PEfreq_fic
            ef[card] = ef_chosen + Apun * PEfreq;
            ev[card] = ev[card] + Apun * PEval;
          }
          pers[card] = 1;
        }
        pers = pers / (1 + K_tr)
        
        utility = ev + ef * betaF + pers * betaP
        card_trial[card] = card_trial[card] + 1
        if(missing){
          outcome = choice = -1
        }
        data = data.frame(ID = i,
                          missing = ifelse(s == 2, missing, F),
                          session = s,
                          card = card,
                          trial = t,
                          outcome = outcome,
                          sign = sign,
                          card_trial = card_trial[card],
                          choice = curr_choice) %>% 
          bind_rows(data)
      }
    }
  }
  data %>%
    return()
}
```



# -------------------------------------------
# Set Parameter Values
## Load Posteriors
```{r, eval = T}
TR_orl_posteriors = readRDS(here("1_IGT_PP", "Data", "2_Fitted", 
                                 "Joint_ORL", "Joint_ORL_posteriors.rds"))
```



## Set Mus
```{r, eval = T}
parameter_names = c("Arew", "Apun", "K", "betaF", "betaP")
mu_p = apply(TR_orl_posteriors$mu_p, c(2, 3), mean) # Untransformed
colnames(mu_p) = parameter_names

vcovs = list()
for(p in parameter_names){
  R = apply(TR_orl_posteriors[[paste0("R_", p)]], c(2, 3), mean)
  SD = diag(apply(TR_orl_posteriors[[paste0("sigma_", p)]], 2, mean))
  vcovs[[p]] = SD%*%R%*%SD
}
```



## Simulate Parameters
```{r, eval = T}
set.seed(20240227)
N = 49
N_missing = 10
missingness = sample(c(rep(F, N-N_missing), # codes present participants
                   rep(T, N_missing)),  # codes missing participants
                 replace = F)

parameters = list(ID = 1:49,
                  missing = missingness)
for(p in parameter_names){
  parameters[[p]] = mvrnorm(N, mu = mu_p[, p], Sigma = vcovs[[p]])
  if(p %in% c("Arew", "Apun", "K")){
    parameters[[paste0(p, "_UT")]] = parameters[[p]]
    parameters[[p]] = pnorm(parameters[[p]])
    if(p == "K"){
    parameters[[p]] = parameters[[p]]*5
    }
  }
}
parameter_values = data.frame(parameters) %>% 
  cbind(data.frame(ID = 1:N, missing = missingness)) %>% 
  pivot_longer(ends_with(c(".1", ".2")), names_to = c("parameter", "session"),
               values_to = "estimate", names_sep = "\\.") %>% 
  mutate(missing = case_when(session == 1 ~ F, T ~ missing))
```



# -------------------------------------------
# Simulation
## Simulate Data
```{r, eval = T}
sim_data = simulate_orl(parameter_values, N, custom_seed = 20240304)

saveRDS(sim_data, here("Parameter Recovery", 
                       paste0(sim_type, "_sim_data.RDS")))
```



```{r}
sim_data = readRDS(here("Parameter Recovery", 
                        paste0(sim_type, "_sim_data.RDS")))
```




## Prep Stan Data
```{r, eval = T}
IDs = unique(sim_data$ID)
N = length(IDs)
Trials = max(sim_data$trial)
S = length(unique(sim_data$session))

Tsubj = array(120, c(N, S))
choice = card = outcome = sign = array(-1, c(N, Trials, S))

for(i in 1:N){
  for(s in 1:S){
    if(missingness[i] & s == 2){
      Tsubj[i,s] = 0
    }
    
    if(Tsubj[i,s] > 0){
      temp_data = sim_data %>% 
        filter(ID == i, session == s) %>% 
        arrange(trial)
      choice[i,,s] = temp_data$choice
      card[i,,s] = temp_data$card
      outcome[i,,s] = temp_data$outcome
      sign[i,,s] = temp_data$sign
    }
  }
}
stan_data = list(
  N = N,
  T = Trials,
  S = S,
  subjIDs = IDs,
  Tsubj = Tsubj,
  choice = choice,
  card = card,
  outcome = outcome,
  sign = sign
)
```



# -------------------------------------------
# Fit Model
```{r, eval = T}
# Compile model
orl_model = stan_model(here("Parameter Recovery", "Joint_ORL.stan"))


# Fit model
sim_orl_fit = sampling(orl_model,
                       data   = stan_data, 
                       iter   = 2000, 
                       warmup = 1000, 
                       chains = 4, 
                       cores  = 4,
                       seed   = 43210,
                       save_warmup = F)


#save the fitted model as an .rds file
saveRDS(sim_orl_fit, here("Parameter Recovery",
                          paste0(sim_type, "_Sim_Joint_ORL_fit.RDS")))
```



```{r}
sim_orl_fit = readRDS(here("Parameter Recovery",
                           paste0(sim_type, "_Sim_Joint_ORL_fit.RDS")))
```



```{r, eval = T}
sim_orl_posteriors <- extract(sim_orl_fit)
saveRDS(sim_orl_posteriors,
        here("Parameter Recovery",
             paste0(sim_type, "_Sim_Joint_ORL_posteriors.RDS")))
```



```{r}
sim_orl_posteriors =
  readRDS(here("Parameter Recovery",
               paste0(sim_type, "_Sim_Joint_ORL_posteriors.RDS")))
```



# -------------------------------------------
# Correlations
## Prep Data
```{r}
recovered_parameters =
  data.frame(Arew_UT.1 = sim_orl_posteriors$mu_p[,1,1] +
                         sim_orl_posteriors$Arew_tilde[,1,],
             Arew_UT.2 = sim_orl_posteriors$mu_p[,2,1] +
                         sim_orl_posteriors$Arew_tilde[,2,],
             Apun_UT.1 = sim_orl_posteriors$mu_p[,1,2] +
                         sim_orl_posteriors$Apun_tilde[,1,],
             Apun_UT.2 = sim_orl_posteriors$mu_p[,2,2] +
                         sim_orl_posteriors$Apun_tilde[,2,],
             K_UT.1 = sim_orl_posteriors$mu_p[,1,3] +
                      sim_orl_posteriors$K_tilde[,1,],
             K_UT.2 = sim_orl_posteriors$mu_p[,2,3] +
                      sim_orl_posteriors$K_tilde[,2,],
             betaF.1 = sim_orl_posteriors$mu_p[,1,4] +
                       sim_orl_posteriors$betaF_tilde[,1,],
             betaF.2 = sim_orl_posteriors$mu_p[,2,4] +
                       sim_orl_posteriors$betaF_tilde[,2,],
             betaP.1 = sim_orl_posteriors$mu_p[,1,5] +
                       sim_orl_posteriors$betaP_tilde[,1,],
             betaP.2 = sim_orl_posteriors$mu_p[,2,5] +
                       sim_orl_posteriors$betaP_tilde[,2,]) %>% 
  pivot_longer(everything(),
               names_to = c("parameter", "session", "ID"),
               values_to = "recovered",
               names_sep = "\\.", names_transform = list(ID = as.numeric)) %>% 
  group_by(parameter, session, ID) %>% 
  summarise(recovered = mean(recovered))


actual_parameters = data.frame(parameters) %>%
  pivot_longer(c(everything(), -ID, -missing), 
               names_to = c("parameter", "session"), values_to = "actual",
               names_sep = "\\.") %>% 
  filter(!(parameter %in% c("Arew", "Apun", "K"))) %>% 
  mutate(missing = case_when(session == 1 ~ F, T ~ missing))

combined_parameters = left_join(recovered_parameters, actual_parameters)
```



## Run Correlations
```{r}
correlations = data.frame()

for(p in c("Arew_UT", "Apun_UT", "K_UT", "betaF", "betaP")){
  for(s in 1:2){
    cur_cor = cor.test(~actual + recovered,
                       data = filter(combined_parameters,
                                     !missing,
                                     parameter == p,
                                     session == s))
    correlations = data.frame(parameter = p,
                              session = s,
                              r = cur_cor$estimate,
                              p = cur_cor$p.value,
                              sig = ifelse(cur_cor$p.value < .05, "*", ""),
                              lower = cur_cor$conf.int[1],
                              upper = cur_cor$conf.int[1]) %>% 
      bind_rows(correlations)
  }
}
```



## Plot Correlations
```{r}
tiff(here("Parameter Recovery",
          paste0(sim_type, "_correlations.tiff")),
     width = 10, height = 16, units = "cm", res = 300)
  combined_parameters %>% 
    filter(!missing) %>%
    group_by(session, parameter) %>% 
    mutate(z_actual = (actual - mean(actual)) / sd(actual),
           z_recovered = (recovered - mean(recovered)) / sd(recovered)) %>% 
    ggplot(aes(x = z_actual, y = z_recovered)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      theme_classic() +
      labs(x = "Actual", y = "Recovered",
           caption = "X- and Y-axis values are z-scored") +
      facet_rep_grid(parameter~session)
dev.off()
```

















