---
title: "Drug Data Preprocessing"
output: html_document
author: "Jeremy Haynes"
---



# --------------------------------------
# Load Packages
```{r}
library(tidyverse)
library(rprime)
library(car)
library(plyr)
```



# --------------------------------------
# SCID Data



## Import Data
```{r, warning=F}
SCID_dad = read.csv("S:/CADEPP/Longitudinal Imaging Project/Finalized Datasets Spring 2022/Finalized Scored Data/T1/Interviews/SCID/Dad/5.23.2022_DadSCIDT1_diagnosesandsymptoms.csv") %>%
    select(ID, participant = Participant,
           current_sub  = csub, # current SUD (everything except marijuana and alcohol)
           past_sub     = psub, # past SUD (everything except marijuana and alcohol)
           lifetime_sub = lsub, # lifetime SUD (everything except marijuana and alcohol)
           current_alc  = calc, # current alcohol use disorder
           past_alc     = palc, # past current alcohol use disorder
           lifetime_alc = lalc, # lifetime current alcohol use disorder
           current_pot  = cpot, # current marijuana use disorder
           past_pot     = ppot, # past marijuana use disorder
           lifetime_pot = lpot, # lifetime marijuana use disorder
           ) %>% 
  mutate(participant = "dad")

SCID_mom = read.csv("S:/CADEPP/Longitudinal Imaging Project/Finalized Datasets Spring 2022/Finalized Scored Data/T1/Interviews/SCID/Mom/5.23.2022_MomSCIDT1_diagnosesandsymptoms.csv") %>% 
    select(ID, participant = Participant,
           current_sub  = csub, # current SUD (everything except marijuana and alcohol)
           past_sub     = psub, # past SUD (everything except marijuana and alcohol)
           lifetime_sub = lsub, # lifetime SUD (everything except marijuana and alcohol)
           current_alc  = calc, # current alcohol use disorder
           past_alc     = palc, # past current alcohol use disorder
           lifetime_alc = lalc, # lifetime current alcohol use disorder
           current_pot  = cpot, # current marijuana use disorder
           past_pot     = ppot, # past marijuana use disorder
           lifetime_pot = lpot, # lifetime marijuana use disorder
           ) %>% 
  mutate(participant = "mom")
```



## Process Data
```{r}
bind_rows(SCID_mom, SCID_dad) %>% #View()
  saveRDS("SCID_SUD_Data.RDS")
```



## Inspect Data
```{r, eval = F}
data.frame(freq = unlist(sapply(select(SCID, depression, anxiety, SU), table)))
```










