---
title: "Drug Data Preprocessing"
output: html_document
author: "Jeremy Haynes"
---



# --------------------------------------
# Load Packages
```{r}
library(tidyverse)
library(rprime)
library(car)
library(plyr)
library(here)
```



# --------------------------------------
# SCID Data
## Select Function
```{r}
custom_select = function(data){
  new_data = data %>% 
    select(ID, session = VisitN, participant = Participant, date = Date,
           # CURRENT
           cdep, # depression
           canx, # anxiety
           csub, # substance use (everything except marijuana and alcohol)
           cpot, # marijuana use
           calc, # alcohol use
           # PAST
           pdep, # depression
           panx, # anxiety
           psub, # substance use (everything except marijuana and alcohol)
           ppot, # marijuana use
           palc, # alcohol use
           # LIFETIME
           ldep, # depression
           lanx, # anxiety
           lsub, # substance use (everything except marijuana and alcohol)
           lpot, # marijuana use
           lalc  # alcohol use
           )
  return(new_data)
}
```



## Import Data
```{r, warning=F}
SCID_dad = read.csv("S:/CADEPP/Longitudinal Imaging Project/Finalized Datasets Spring 2022/Finalized Scored Data/T1/Interviews/SCID/Dad/5.23.2022_DadSCIDT1_diagnosesandsymptoms.csv") %>% 
  custom_select() %>% 
  dplyr::mutate(participant = "dad")
SCID_mom = read.csv("S:/CADEPP/Longitudinal Imaging Project/Finalized Datasets Spring 2022/Finalized Scored Data/T1/Interviews/SCID/Mom/5.23.2022_MomSCIDT1_diagnosesandsymptoms.csv") %>% 
  custom_select() %>% 
  dplyr::mutate(participant = "mom")
```



## Process Data
```{r}
SCID = bind_rows(SCID_mom, SCID_dad)


saveRDS(SCID, here("1_TADS_Parents_PP", "Data", "0_Raw", "SCID_Anx_Dep_SUD.RDS"))
```



## Inspect Data
```{r, eval = F}
data.frame(freq = unlist(sapply(select(SCID, depression, anxiety, SUD), table)))
```










