---
title: "IGT Preprocessing"
output: html_document
author: "Jeremy Haynes"
---



# --------------------------------------
# Setup
## Load Packages
```{r}
library(tidyverse)
library(rprime)
library(car)
library(dplyr)
library(here)
```



## Load Data
```{r}
T1_IGT_parents = readRDS(here("1_TADS_Parents_PP", "Data", "0_Raw", "Processed_Raw_T1_Parents.RDS"))

SCID = readRDS(here("1_TADS_Parents_PP", "Data", "0_Raw", "SCID_Anx_Dep_SUD.RDS"))
```



# --------------------------------------
# Initialize Variables
```{r}
sample = "T1_parent_Anx_Dep_SUD_Female"
# covariates = c("days_pc")
covariates = c("anxiety", "depression", "SUD", "female")

IGT_prepped = T1_IGT_parents %>% 
  group_by(id, participant) %>% 
  mutate(date = as.Date(date, format = "%m-%d-%Y"),
         days_pc = as.numeric(difftime(date, min(date), units = "days"))) %>% 
  select(ID = id, -date, everything())
```



# Prep Data
```{r}
SCID_prepped = SCID %>%
  mutate(participant = tolower(participant)) %>% 
  select(-date)

combined_data = inner_join(IGT_prepped, SCID_prepped) %>% # Note that Mom 5005 does not have SCID data
  # Subset specific diagnostic groups
  # filter(SU == 1) %>% 
  # This ensures that we exclude all non-participant data (e.g., test data)
  filter(ID >= 5000 & ID < 6000) %>%
  # Do some prepartion for creating stan data
  mutate(# fix session variable
         session = as.numeric(str_remove(time, "T")),
         # create variable that assigns numbers to participant types (1 = child, 2 = dad, 3 = mom)
         participant_num = match(participant, c("child", "dad", "mom")[1:3]),
         # create variable that assigns numbers to card types (1 = A, 2 = B, 3 = C, 4 = D)
         card_num = match(str_remove(AB_card, "AB_"), LETTERS[1:4]),
         # create variable indicating gender (0 = male, 1 = female)
         female = case_when(participant == "mom" ~ 1, T ~ 0)) %>% 
  # create new ID variable for consecutive IDs (this is just the "id" variable but with consecutive numbers) 
  group_by(ID) %>% mutate(ID_num = cur_group_id()) %>% 
  # create unique ID for individual participants - this helps make sure that
    # we have a unique ID for moms & dads ("participant" variable) with the
    # same kid ("id" variable)
  group_by(ID, participant) %>% mutate(ID_part = cur_group_id())

saveRDS(combined_data, here("1_TADS_Parents_PP", "Data", "0_Raw", 
                            paste(sample, "IGT.RDS", sep = "_")))
```



# --------------------------------------
# Make ORL Stan Data
## Function
```{r}
# Notes: This creates a stan data list for fitting a mean-based covariate model. That is, a model in which parameters are estimated for each session instead of estimating a difference score between, for example, session 1 to session 2. In addition, the format of the covariates needs to be specified before sending it in with the data
make_ORL_stan_data = function(data, covariate_names){
  library(dplyr)
  library(stringr)
  
  ##################################################################
  # setup stan variables
  ID_participant = sort(unique(data$ID_part)) # vector of unique ID 
  N = length(ID_participant)            # number of unique IDs
  sessions = unique(data$time)          # vector of unique sessions
  S = length(sessions)                  # number of unique sessions
  C = length(covariate_names)           # number of covariates
  D = S + C                             # number of covariates (including sessions)
  Tr = max(data$trial)                  # max number of trials across participants
  

  ID_OG = rep(-1, N)                            # original ID
  ID_number = rep(-1, N)                        # ID number - this links parents of the same 
                                                  # child together in the same way as ID_OG
  participant_number = rep(-1, N)               # child (1), dad (2), or mom (3)
  Tsubj = array(data = 0, dim = c(N,S))         # number of trials by participant
  card = array(data = -1, dim = c(N,Tr,S))      # cards
  choice = array(data = -1, dim = c(N,Tr,S))    # choices made by participant
  outcome = array(data = -999, dim = c(N,Tr,S)) # outcome of choice
  sign = array(data = -999, dim = c(N,Tr,S))    # sign of choice outcome
  X = array(data = 0, dim = c(N,D,S))           # covariates for participants
  pbx = "good to go"                            # indicator for problem in loop
  
  
  ##################################################################
  # fill vectors and arrays with data
  for(i in 1:N){ # loop through persons
    cur_i = filter(data, ID_part == i) # subset individual
    
    # assign original ID & double-check it gives whole number (it should)
    ID_OG[i] = mean(cur_i$ID)
    pbx = ifelse(ID_OG[i]%%1>0, "problem in OG ID", pbx)
    
    # assign ID number that ties parents together & double-check it gives whole number (it should)
    ID_number[i] = mean(cur_i$ID_num)
    pbx = ifelse(ID_OG[i]%%1>0, "problem in OG ID", pbx)
    
    # assign participant type & double-check it gives whole number (it should)
    participant_number[i] = mean(cur_i$participant_num)
    pbx = ifelse(participant_number[i]%%1>0, "problem in participant number", pbx)
    
    for(s in 1:S){ # loop through sessions
      cur_is = filter(cur_i, time == sessions[s]) # subset session within individual
      
      if(nrow(cur_is) > 0 & max(cur_is$trial) == 120){ # check if participant has a full session's
                                                         # worth of data - if not, skip next loop
        
        # assign covariate variables
        X[i,s,s] = 1 # assign a 1 for current session
        if(C>0){
          for(c in 1:C){
            X[i,S+c,s] = mean(cur_is[[covariate_names[c]]])
            pbx = ifelse(X[i,s+c,s]%%1>0, "problem in covariate", pbx)
          }
        }
        
        Tsubj[i,s] = max(cur_is$trial)
        
        for(t in 1:Tsubj[i,s]){ # loop through trials
          cur_ist = filter(cur_is, trial == t) # subset trial within session within individual
          
          # assign card number
          card[i,t,s] = cur_ist$card_num
          
          # assign choice
          choice[i,t,s] = ifelse(cur_ist$card_play == 0, 2, cur_ist$card_play)
          
          # assign outcome
          outcome[i,t,s] = ifelse(is.na(cur_ist$outcome), 0, cur_ist$outcome / 100)
          
          # assign sign of outcome
          sign[i,t,s] = sign(outcome[i,t,s])
        }
      }
    }
  }
  
  stan_data = list(ID_participant = ID_participant,
                   ID_OG = ID_OG,
                   ID_number = ID_number,
                   participant_number = participant_number,
                   N = N,
                   S = S,
                   T = Tr,
                   card = card,
                   Tsubj = Tsubj,
                   choice = choice,
                   outcome = outcome,
                   sign = sign,
                   D = D,
                   X = X)
  
  return(stan_data)
}
```



## Make Parent Data
```{r, eval = T}
parent_stan = make_ORL_stan_data(data = bind_rows(combined_data),
                                 covariate_names = covariates)

saveRDS(parent_stan, here("1_TADS_Parents_PP", "Data", "1_Stan", 
                          paste("design", sample, "IGT.RDS", sep = "_")))
```



# --------------------------------------
# Make Binomial Stan Data
## Function
```{r}
# Notes: This creates a stan data list for fitting a mean-based covariate model. That is, a model in which parameters are estimated for each session instead of estimating a difference score between, for example, session 1 to session 2. In addition, the format of the covariates needs to be specified before sending it in with the data
make_binomial_stan_data = function(data, covariate_names){
  library(dplyr)
  library(stringr)
  
  ##################################################################
  # setup stan variables
  ID_participant = unique(data$ID_part) # vector of unique ID 
  N = length(ID_participant)            # number of unique IDs
  sessions = unique(data$time)          # vector of unique sessions
  S = length(sessions)                  # number of unique sessions
  C = length(covariate_names)           # number of covariates
  D = S + C                             # number of covariates (including sessions)
  

  ID_OG = rep(-1, N)                    # original ID
  ID_number = rep(-1, N)                # ID number - this links parents of the same 
                                          # child together in the same way as ID_OG
  participant_number = rep(-1, N)       # child (1), mom (2), or dad (3)
  # number of trials (regardless of choice) for each deck
  A_trials = rep(-1, N)
  B_trials = rep(-1, N)
  C_trials = rep(-1, N)
  D_trials = rep(-1, N)
  # number of plays for each deck
  A_plays = rep(-1, N)
  B_plays = rep(-1, N)
  C_plays = rep(-1, N)
  D_plays = rep(-1, N)
  X = array(data = 0, dim = c(N,D))           # covariates for participants
  pbx = "good to go"                          # indicator for problem in loop
  
  
  ##################################################################
  # fill vectors and arrays with data
  for(i in 1:N){ # loop through persons
    cur_i = filter(data, ID_part == i) # subset individual
    
    # assign original ID & double-check it gives whole number (it should)
    ID_OG[i] = mean(cur_i$ID)
    pbx = ifelse(ID_OG[i]%%1>0, "problem in OG ID", pbx)
    
    # assign ID number that ties parents together & double-check it gives whole number (it should)
    ID_number[i] = mean(cur_i$ID_num)
    pbx = ifelse(ID_OG[i]%%1>0, "problem in OG ID", pbx)
    
    # assign participant type & double-check it gives whole number (it should)
    participant_number[i] = mean(cur_i$participant_num)
    pbx = ifelse(participant_number[i]%%1>0, "problem in participant number", pbx)
      
    if(nrow(cur_i) > 0 & max(cur_i$trial) == 120){ # check if participant has a full session's
      # worth of data - if not, skip next loop
      
      # assign covariate variables
      X[i,1] = 1 # assign a 1 for current session
      if(C>0){
        for(c in 1:C){
          X[i,1+c] = mean(cur_i[[covariate_names[c]]])
          pbx = ifelse(X[i,1+c]%%1>0, "problem in covariate", pbx)
        }
      }
      A_trials[i] = length(filter(cur_i, card_num == 1)$card_play)
      B_trials[i] = length(filter(cur_i, card_num == 2)$card_play)
      C_trials[i] = length(filter(cur_i, card_num == 3)$card_play)
      D_trials[i] = length(filter(cur_i, card_num == 4)$card_play)
      A_plays[i] = sum(filter(cur_i, card_num == 1)$card_play)
      B_plays[i] = sum(filter(cur_i, card_num == 2)$card_play)
      C_plays[i] = sum(filter(cur_i, card_num == 3)$card_play)
      D_plays[i] = sum(filter(cur_i, card_num == 4)$card_play)
    }
  }
  
  stan_data = list(ID_participant = ID_participant,
                   ID_OG = ID_OG,
                   ID_number = ID_number,
                   participant_number = participant_number,
                   N = N,
                   S = S,
                   A_trials = A_trials,
                   B_trials = B_trials,
                   C_trials = C_trials,
                   D_trials = D_trials,
                   A_plays = A_plays,
                   B_plays = B_plays,
                   C_plays = C_plays,
                   D_plays = D_plays,
                   D = D,
                   X = X)
  
  return(stan_data)
}
```



## Make Parent Data
```{r, eval = F}
binomial_parent_stan = make_binomial_stan_data(data = bind_rows(combined_data),
                                               covariate_names = covariates)

saveRDS(binomial_parent_stan, here("1_TADS_Parents_PP", "Data", "1_Stan", 
                                   paste("design", sample, "Binomial", "IGT.RDS", sep = "_")))
```



# --------------------------------------


























